import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { specs, slugify } from "../../data";
import { Footer, Header } from "../../ui";

const findSpec=(parts:string[])=>specs.find(s=>s.slug===parts.join("/"));
export async function generateMetadata({params}:{params:Promise<{slug:string[]}>}):Promise<Metadata>{const {slug}=await params;const s=findSpec(slug);return s?{title:s.title,description:s.answer}:{title:"Specification not found"}}
export default async function SpecPage({params}:{params:Promise<{slug:string[]}>}){const {slug}=await params;const s=findSpec(slug);if(!s)notFound();const related=specs.filter(x=>x.slug!==s.slug).slice(0,5);return <><Header/><main className="inner-page"><section className="page-hero"><div className="shell"><div className="breadcrumbs"><Link href="/">Home</Link> / <Link href={`/makes/${slugify(s.make)}`}>{s.make}</Link> / {s.model} / {s.category}</div><h1>{s.title}</h1><p>{s.make} {s.model} mechanical reference</p></div></section><section className="shell page-content"><div className="quick-answer"><small>QUICK ANSWER</small><p>{s.answer}</p></div><div className="spec-layout"><div><article className="spec-card"><h2>Specification table</h2><table className="spec-table"><thead><tr><th>ITEM</th><th>VALUE</th><th>DETAIL</th></tr></thead><tbody>{s.values.map(v=><tr key={v.label}><td>{v.label}</td><td>{v.value}</td><td>{v.note}</td></tr>)}</tbody></table><div className="procedure"><h2>Before you begin</h2><p>{s.detail}</p><p>Identify the exact model year, engine code, component revision and fastener condition. Use calibrated tools and follow the current manufacturer procedure for safety-critical work.</p><div className="reviewed">REFERENCE REVIEWED · AUGUST 2026</div></div></article></div><aside className="side-card"><h3>Related references</h3>{related.map(r=><Link key={r.slug} href={`/specs/${r.slug}`}>{r.title} →</Link>)}</aside></div></section></main><Footer/></>}
