/* eslint-disable react/no-unescaped-entities */
import type { Metadata } from "next";
import Link from "next/link";
import { specs } from "../../../data";
import { Footer, Header, LineIcon } from "../../../ui";

export const metadata: Metadata = { title: "Chevy 350 Specifications and Technical Guides", description: "Complete Chevrolet 350 small-block reference: firing order, torque specs, spark plug gap, oil capacity, timing, valve adjustment, and assembly guides.", alternates: { canonical: "https://torquesheet.com/makes/chevrolet/350" } };

export default function Page(){return <><Header/><main className="inner-page"><section className="page-hero engine-hub-hero"><div className="shell"><div className="breadcrumbs"><Link href="/">Home</Link> / <Link href="/makes/chevrolet">Chevrolet</Link> / 350</div><span className="kicker">ENGINE REFERENCE HUB</span><h1>Chevy 350 specifications</h1><p>Source-backed service data for the traditional Chevrolet Gen I 350 small-block V8, organized by component and engine configuration.</p><div className="hub-facts"><span><b>350 cu in</b> displacement</span><span><b>4.00 × 3.48 in</b> bore × stroke</span><span><b>1-8-4-3-6-5-7-2</b> firing order</span></div></div></section><section className="shell page-content"><div className="hub-intro"><div><span className="kicker">START HERE</span><h2>One engine name, many configurations</h2></div><p>The “Chevy 350” spans production engines, crate engines, swaps, and aftermarket builds. These guides identify named Chevrolet Performance examples and explain when the component manufacturer's instructions must take priority.</p></div><div className="hub-grid engine-guide-grid">{specs.map((s,i)=><Link className="hub-card" href={`/specs/${s.slug}`} key={s.slug}><span className="guide-number">{String(i+1).padStart(2,"0")}</span><span className="icon-box"><LineIcon name={s.category.includes("Firing")?"firing":s.category.includes("Fluid")?"fluid":s.category.includes("Timing")?"timing":s.category.includes("Valve")?"valve":"torque"}/></span><small>{s.category}</small><h3>{s.title}</h3><p>{s.answer.split(".")[0]}.</p><span className="mini-link">Open complete guide →</span></Link>)}</div><div className="critical-callout hub-callout"><span>!</span><div><strong>Confirm the exact build before assembly</strong><p>Fastener type, lubricant, cylinder heads, oil pan, ignition and valvetrain can all change a specification. Each guide includes an application note and primary source trail.</p></div></div></section></main><Footer/></>}
