import type { Source, SpecRecord, SpecValue } from "./chevy350-content";
import { firingGuide, sparkGuide } from "./extended-content";

const reviewed="2026-08-14";
const engineImage="/features/shared-firing-engine.png";
const src=(label:string,url:string,note:string):Source=>({label,url,note});
const S={
  mopar:src("Mopar vehicle information","https://vehicleinfo.mopar.com/","Official Dodge and Chrysler model-year information lookup."),
  gm:src("GM service information","https://www.acdelcotds.com/subscriptions","Official GM service-information access for Chevrolet, Pontiac, Oldsmobile and Buick applications."),
  ford:src("Ford service information","https://www.motorcraftservice.com/","Official Ford engine and model-year service-information access."),
  toyota:src("Toyota Technical Information System","https://techinfo.toyota.com/","Official Toyota engine-code and model-year service information."),
  nissan:src("Nissan TechInfo","https://www.nissan-techinfo.com/","Official Nissan engine and vehicle service-information source."),
  honda:src("Honda Service Information System","https://techinfo.honda.com/","Official Honda engine-code and model-year service information."),
  subaru:src("Subaru Technical Information System","https://techinfo.subaru.com/stis/","Official Subaru engine-code-specific service information."),
  mazda:src("Mazda service information","https://www.mazdaserviceinfo.com/","Official Mazda service-information source."),
  mitsubishi:src("Mitsubishi technical information","https://mitsubishitechinfo.com/","Official Mitsubishi model and engine service-information source."),
};
const pontiacAma=src("1972 Pontiac LeMans/GTO AMA specifications","https://autohistorypreservationsociety.org/wp-content/uploads/1972-PONTIAC-AMA-Specs-LeMans-GTO-Pg-1-42.pdf","Original Pontiac AMA specification pages covering the 350, 400 and 455 V8 family, cylinder numbering and production engine data.");
const oldsmobileDistributor=src("Vertex electronic-distributor application instructions","https://fuelinjectionent.com/tech/MagnetoRotation.pdf","Application chart lists Oldsmobile 307/330/350/400/403/425/455 with 1-8-4-3-6-5-7-2 order and counterclockwise distributor rotation.");
const buickAma=src("1970 Buick GS/GS455 AMA specifications","https://over-drive-magazine.com/wp-content/uploads/2022/12/1970-BUICK-GS-GS455-AMA-1-28.pdf","Original Buick AMA specifications explicitly list the 350 and 455, odd/even bank numbering and 1-8-4-3-6-5-7-2 firing order.");
const chevy283Heritage=src("1959 Chevrolet passenger-car and El Camino specifications","https://news.chevrolet.com/content/dam/company/no_search/heritage-archive-docs/vehicle-information-kits/chevrolet/1959-Chevrolet-El-Camino.pdf","Chevrolet heritage specifications identify the 283-cubic-inch V8 and list its production firing order. The page uses that factory sequence while keeping distributor indexing as a separate installation step.");
const chevy327396Heritage=src("1965 Chevrolet Corvette specifications","https://news.chevrolet.com/content/dam/company/no_search/heritage-archive-docs/vehicle-information-kits/chevrolet/1965-Chevrolet-Corvette.pdf","Chevrolet's heritage specification sheet explicitly lists the 327 and 396 V8 engines and the shared 1-8-4-3-6-5-7-2 firing order.");
const chevy427Heritage=src("1967 Chevrolet Corvette specifications","https://news.chevrolet.com/content/dam/company/no_search/heritage-archive-docs/vehicle-information-kits/chevrolet/1967-Chevrolet-Corvette.pdf","Chevrolet heritage material for the 1967 Corvette documents the Mark IV 427 application. This page is limited to the traditional distributor-equipped big-block, not the later LS7 small-block architecture.");
const fordEarlyV8Instruction=src("Ford Performance 289/302 intake-manifold instructions","https://performanceparts.ford.com/download/instructionsheets/FordInstShtM-9424-F302.pdf","Ford Performance explicitly distinguishes the early 289/302 order from the later 302 HO order and instructs technicians to establish cylinder 1 at compression TDC before distributor work.");
const fordV8RockerInstruction=src("Ford Performance V8 rocker-arm instructions","https://performanceparts.ford.com/download/instructionsheets/FordInstShtM-6564-All.pdf","Ford Performance lists the applicable 302/460 and 351C/351W firing orders and uses cylinder 1 compression TDC as the service reference.");
const ford1969ShopManual=src("1969 Ford Car Shop Manual, engine volume","https://fordmanuals.com/product/1969-ford-car-shop-manual-vol-i-v/","Ford-licensed reproduction of the original Ford Motor Company shop manual containing the 390 and 428 FE engine service sections and specifications.");
const toyota1982Specs=src("1982 Toyota product specifications","https://xr793.com/wp-content/uploads/2025/06/1982-Toyota-Product-Specifications.pdf","Factory Toyota product specifications identify the 3T-C, its inline-four layout and its 1-3-4-2 firing order.");
const toyota4ageManual=src("Toyota 4A-FE/4A-GE engine repair manual","https://www.valvulita.com/sites/default/files/toyota_4a-fe_4a-ge_engine_repair_manual_0.pdf","Toyota engine repair-manual pages provide 4A-GE ignition service data, firing order and distributor procedures.");
const toyota2jzManual=src("Toyota 2JZ-GTE engine technical manual","https://www.2jz.se/download_file/388/183","Toyota technical manual pages identify the 2JZ-GTE as an inline six and explicitly list its 1-5-3-6-2-4 firing order.");
const toyota2jzIgnition=src("Toyota 2JZ-GTE repair manual — ignition system","https://2jz.se/application/files/7414/3781/4903/Ignition_Systems_-_2JZ-GTE.pdf","Factory repair-manual extract specifying a 1.1 mm (0.043 in) gap for a new PK20R11/BKR6EP11 plug, a 1.3 mm used-plug maximum, and 18 N·m installation torque.");
const chrysler318Manual=src("Chrysler 318/400 industrial engine service manual","https://www.jensales.com/content/ppp/chrysler-engine-service-manual-cy-s-eng318.pdf","Original Chrysler service-manual scan listing 85 lb-ft for the 318 cylinder-head bolts; vehicle year, head, gasket and replacement-fastener instructions still control.");
const dodge360MagnumHead=src("1994 Dodge 5.9L Magnum service manual — cylinder head","https://charm.li/Dodge%20and%20Ram/1994/B250%203%2F4%20Ton%20Van%20V8-360%205.9L/Repair%20and%20Diagnosis/Engine%2C%20Cooling%20and%20Exhaust/Engine/Cylinder%20Head%20Assembly/Service%20and%20Repair/","Service-manual transcription specifying two sequence passes—50 lb-ft followed by 105 lb-ft—for the covered 5.9L Magnum application.");
const dodge360MagnumSpark=src("1994 Dodge 5.9L Magnum service manual — spark-plug gap","https://charm.li/Dodge%20and%20Ram/1994/1500%204x2%20Pickup%20V8-360%205.9L%20Magnum/Repair%20and%20Diagnosis/Powertrain%20Management/Tune-up%20and%20Engine%20Performance%20Checks/Spark%20Plug/Specifications/Gap%20Specifications/","Service-manual specification identifying Champion RC12YC and a 0.9 mm (0.035 in) gap for the covered 1994 5.9L Magnum truck.");
const dodge318MagnumSpark=src("1994 Dodge 5.2L Magnum service manual — spark-plug gap","https://charm.li/Dodge%20and%20Ram/1994/1500%204x4%20Pickup%20V8-318%205.2L%20Magnum/Repair%20and%20Diagnosis/Specifications/Mechanical%20Specifications/Ignition%20System/Spark%20Plug/Gap%20Specifications/","Service-manual specification identifying Champion RC12YC and a 0.9 mm (0.035 in) gap for the covered 1994 5.2L Magnum truck.");
const ford460_1996Spark=src("1996 Ford F-250 service specifications — 7.5L ignition","https://lemon-manuals.org.ua/Ford/1996/Pickup%20F250%2C%202D%20Pickup%20Extra%20Cab%2C%205.8%20H%2C%204WD%2C%20Automatic%2C%20E4OD/Repair%20and%20Diagnosis%20%28Single%20Page%29/Quick%20Lookups/Common%20Specs%20%26%20Procedures/Specifications%20Index/","Service-manual index listing a 1.07–1.17 mm (0.042–0.046 in) gap and 7–15 lb-ft installation torque for the covered 1996 7.5L F-Series application.");
const chevy1974Corvette454Spark=src("1974 Chevrolet Corvette specifications — LS4 454 ignition","https://corvettestory.com/specs/1974-Corvette-specs-options.php","Model-specific 1974 Corvette specification table identifying the LS4 454, ACR44T spark plug and a 0.033–0.038 inch factory gap range.");
const chevyGen1Head=src("Chevrolet Performance HT383 long-block installation guide","https://www.chevrolet.com/content/dam/chevrolet/na/us/english/index/performance/resources/installation-guides/crate-engines/02-pdf/ht383-long-block-installation-guide-12499101.pdf","Manufacturer guide for a production-style Gen I small-block assembly specifying 25, 40 and 65 lb-ft head-bolt passes with Teflon pipe sealant and a 10-hour recheck for that package.");
const pontiac1968Service=src("1968 Pontiac service manual — V8 cylinder head","https://www.scribd.com/document/526639262/Pontiac-Service-Manual","Original service-manual scan/transcription specifying 95 lb-ft for the covered traditional Pontiac V8 cylinder-head bolts.");
const ford460_1984Head=src("1984 Ford F-250 7.5L service manual — cylinder head","https://charm.li/Ford/1984/F%20250%204WD%20Pickup%20V8-460%207.5L/Repair%20and%20Diagnosis/Engine%2C%20Cooling%20and%20Exhaust/Engine/Cylinder%20Head%20Assembly/Service%20and%20Repair/","Service-manual procedure specifying 80, 110 and 130–140 lb-ft sequence passes for the covered 1984 460, including long-bolt location and no post-operation retorque.");
const ford1966_289Head=src("1966 Ford Comet/Falcon/Fairlane/Mustang shop manual — 289 cylinder head","https://www.scribd.com/document/681430368/1966-Comet-Falcon-Fairlane-Mustang-Manual-301-450","Original Ford shop-manual scan specifying three progressive 289 cylinder-head passes of 50 lb-ft, 60 lb-ft and 65–70 lb-ft in the illustrated sequence.");
const felpro351cHead=src("Fel-Pro complete cylinder-head torque tables — Ford 351 Cleveland","https://cdn.hansenracing.se/images/artiklar/fel-topplocksmoment.pdf","Fel-Pro torque table identifying the 1970–1974 351 Cleveland production head-bolt range as 95–105 lb-ft and distinguishing it from other Ford 351 families.");
const toyota2jzHeadManual=src("1997 Toyota Supra repair manual — 2JZ-GTE cylinder head","https://www.jzgte.com/tech/jza80/manuals/Engine.pdf","Factory repair-manual section specifying oiled factory bolts tightened to 34 N·m, then 90° and another 90° in the illustrated 14-bolt sequence.");
const hondaB18cHeadManual=src("1998 Acura Integra service manual — B18C1 cylinder head","https://charm.li/Acura/1998/Integra%20GS-R%20Sedan%20L4-1797cc%201.8L%20DOHC%20%28VTEC%29%20MFI/Repair%20and%20Diagnosis/Engine%2C%20Cooling%20and%20Exhaust/Engine/Cylinder%20Head%20Assembly/Specifications/Torque%20Specifications/","Factory service-data transcription specifying oiled B18C1 head bolts tightened to 22 lb-ft and then 63 lb-ft in sequence.");
const subaruFa20HeadManual=src("Subaru BRZ FA20 engine service manual — cylinder head assembly","https://www.ft86club.com/files/BRZengine.pdf","Factory-format FA20 service procedure specifying the covered six main bolts at 20 N·m, 100 N·m, loosen 360°, 20 N·m, 42 N·m, then position-specific angle stages.");
const toyotaJzTechnical=src("Haltech Toyota 1JZ/2JZ engine technical reference","https://support.haltech.com/portal/en/kb/articles/2jz-1jz-engine","Engine-management reference covering 1JZ-GTE and 2JZ-GTE variants, cylinder orientation, ignition layouts and the shared mechanical firing order.");
const nissanRb26Manual=src("Nissan R32 engine service manual","https://jpjdm.com/jdmfiles/R32_All_Engine_Manual.pdf","Factory engine-manual pages identify the RB26DETT and explicitly list its 1-5-3-6-2-4 firing order.");
const nissanSr20Manual=src("Nissan S13 SR20DET factory service manual","https://sxoc.co.za/download/s13-factory-service-manual-sr20det-jdm/","Factory S13 service-manual reference for the longitudinal SR20DET engine and its ignition system.");
const nissanS14Sr20Head=src("1994 Nissan S14 workshop manual — SR20DET cylinder head","https://www.onlymanuals.com/nissan/other_model/nissan_s14_series_workshop_manual_1994_1994","Factory workshop-manual transcription for the covered S14 SR20DET specifying 39 N·m, 78 N·m, complete loosening, 34–44 N·m and a final 90–95° turn, plus the 158.2 mm bolt-length limit.");
const nissanKa24Manual=src("2002 Nissan Frontier factory service manual","https://www.nicoclub.com/service-manual?fsm_download=Frontier%2F2002%2Ffoldout.pdf","Factory quick-reference data explicitly lists the KA24DE and its 1-3-4-2 firing order.");
const hondaB16Manual=src("Honda B16A maintenance and workshop manual","https://www.hondacrx.co.uk/FAQ/Manuals/","Honda UK-authorized workshop-manual archive covering B16A service, cylinder orientation and distributor-based ignition procedures.");
const hondaIntegraManual=src("1998–2001 Honda/Acura Integra service manual","https://www.hondacrx.co.uk/FAQ/Manuals/","Factory service-manual archive covering B18C-family Integra applications, specifications and ignition service.");
const hondaK20Manual=src("2002–2006 Acura RSX service manual","https://documents.cdn.ifixit.com/3he6nNYYvG2rrZlF.pdf","Factory-format service data explicitly lists K20A2, K20A3 and K20Z1 ignition specifications and the 1-3-4-2 firing order.");
const hondaK24z7Head=src("Honda Civic service manual transcription — K24Z7 cylinder head","https://www.hocivic.com/cylinder_head_inspection_for_warpage_k24z7_-1045.html","Service-manual procedure for the K24Z7 specifying 39 N·m, two 90° turns, an additional 90° for a new bolt, oiled threads and under-head surfaces, and a 10.6 mm minimum bolt diameter.");
const subaruFaManual=src("Subaru technical specifications — boxer-four engine","https://techinfo.subaru.com/stis/doc/ownerManual/MSA5M1923K_STIS.pdf","Primary Subaru technical documentation listing the horizontally opposed four-cylinder firing order and engine specifications.");
const mitsubishi4g63Manual=src("Mitsubishi 4G63 engine mechanical service manual","https://www.thomas-peterson.de/daten/Mitsubishi/Handbuecher/MSSP-206B-2003/GR00003800-11A.pdf","Factory service-manual section explicitly identifies cylinder 1 at the timing-belt side, numbers cylinders 1-2-3-4 and lists firing order 1-3-4-2.");
const mazda13bManual=src("1993 Mazda RX-7 ignition service information","https://manuals.plus/m/52c776bed18fbd309397360f176b68e2924495e1d55c57eed73dd5326523dd60.pdf","RX-7 service information explains the 13B-REW distributorless system, front/rear rotor housings and separate leading and trailing spark events.");

type FiringJob={slug:string;keyword:string;make:string;model:string;title:string;order:string;numbering:string;scope:string;caution:string;source:Source};
const firingJobs:FiringJob[]=[
  {slug:"pontiac/350/firing-order",keyword:"pontiac 350 firing order",make:"Pontiac",model:"350 V8",title:"Pontiac 350 Firing Order and Distributor Diagram",order:"1-8-4-3-6-5-7-2",numbering:"Driver-side bank is 1-3-5-7 and passenger-side bank is 2-4-6-8, front to rear.",scope:"Covers traditional Pontiac-built 350 V8 engines, not Chevrolet 350 swaps installed in Pontiac vehicles.",caution:"Route the cap counterclockwise on the traditional Pontiac distributor. Confirm the block code and establish cylinder 1 compression TDC before choosing the first tower.",source:pontiacAma},
  {slug:"pontiac/400/firing-order",keyword:"pontiac 400 firing order",make:"Pontiac",model:"400 V8",title:"Pontiac 400 Firing Order and Cylinder Numbering",order:"1-8-4-3-6-5-7-2",numbering:"Driver-side bank carries 1-3-5-7; passenger side carries 2-4-6-8, front to rear.",scope:"Covers traditional Pontiac 400 V8 distributor engines.",caution:"The distributor routes counterclockwise. Establish cylinder 1 compression TDC before assigning cap terminals because cap position can change after distributor service.",source:pontiacAma},
  {slug:"pontiac/455/firing-order",keyword:"pontiac 455 firing order",make:"Pontiac",model:"455 V8",title:"Pontiac 455 Firing Order and Distributor Diagram",order:"1-8-4-3-6-5-7-2",numbering:"Driver bank is 1-3-5-7 and passenger bank is 2-4-6-8, viewed from the driver's seat.",scope:"Covers traditional Pontiac 455 V8 engines and stock-style distributor routing.",caution:"Route wires counterclockwise and do not identify the first cap tower from appearance alone; verify rotor position at cylinder 1 compression TDC.",source:pontiacAma},
  {slug:"oldsmobile/350/firing-order",keyword:"oldsmobile 350 firing order",make:"Oldsmobile",model:"350 Rocket V8",title:"Oldsmobile 350 Firing Order and Cylinder Diagram",order:"1-8-4-3-6-5-7-2",numbering:"Driver bank is 1-3-5-7 and passenger bank is 2-4-6-8, front to rear.",scope:"Covers Oldsmobile-built 350 V8 engines; it does not cover Chevrolet, Buick or Pontiac 350 swaps.",caution:"The traditional Oldsmobile distributor routes counterclockwise. GM divisions produced different 350 engines, so casting identity matters even when combustion order matches.",source:oldsmobileDistributor},
  {slug:"oldsmobile/455/firing-order",keyword:"oldsmobile 455 firing order",make:"Oldsmobile",model:"455 Rocket V8",title:"Oldsmobile 455 Firing Order and Distributor Diagram",order:"1-8-4-3-6-5-7-2",numbering:"Driver-side cylinders are 1-3-5-7; passenger-side cylinders are 2-4-6-8.",scope:"Covers Oldsmobile 455 V8 distributor applications.",caution:"Route the cap counterclockwise. Verify cylinder 1 compression TDC before moving multiple wires or assigning the first tower.",source:oldsmobileDistributor},
  {slug:"buick/350/firing-order",keyword:"buick 350 firing order",make:"Buick",model:"350 V8",title:"Buick 350 Firing Order and Cylinder Numbering",order:"1-8-4-3-6-5-7-2",numbering:"Driver bank is 1-3-5-7 and passenger bank is 2-4-6-8, front to rear.",scope:"Covers Buick-built 350 V8 engines; other GM-division 350 engines are separate applications.",caution:"Traditional Buick distributor routing is counterclockwise. Use block and distributor identity rather than the vehicle badge when an engine swap is possible.",source:buickAma},
  {slug:"buick/455/firing-order",keyword:"buick 455 firing order",make:"Buick",model:"455 V8",title:"Buick 455 Firing Order and Distributor Diagram",order:"1-8-4-3-6-5-7-2",numbering:"Odd cylinders 1-3-5-7 are on the driver side and even cylinders 2-4-6-8 are on the passenger side.",scope:"Covers traditional Buick 455 distributor engines.",caution:"Route wires counterclockwise, photograph the original routing and confirm cylinder 1 at compression TDC before distributor removal.",source:buickAma},
  {slug:"chevrolet/283/firing-order",keyword:"chevy 283 firing order",make:"Chevrolet",model:"283 Small-Block V8",title:"Chevy 283 Firing Order and Distributor Diagram",order:"1-8-4-3-6-5-7-2",numbering:"Viewed from the driver's seat, the left bank is 1-3-5-7 and the right bank is 2-4-6-8; both banks count from the radiator toward the firewall.",scope:"Covers traditional Chevrolet Gen I 283 small-block V8s with a stock-pattern camshaft and distributor ignition.",caution:"Route the cap clockwise, but do not assume a particular cap tower is number 1. Bring cylinder 1 to compression TDC and confirm the rotor position first; a distributor can be installed in more than one indexed position.",source:chevy283Heritage},
  {slug:"chevrolet/327/firing-order",keyword:"chevy 327 firing order",make:"Chevrolet",model:"327 Small-Block V8",title:"Chevy 327 Firing Order and Cylinder Numbering",order:"1-8-4-3-6-5-7-2",numbering:"Viewed from the driver's seat, cylinders 1-3-5-7 are on the left bank and 2-4-6-8 are on the right bank, front to rear.",scope:"Covers production-style Chevrolet Gen I 327 small-block V8s using the standard camshaft firing order and a clockwise distributor.",caution:"Do not confuse cylinder numbering with cap position. Establish cylinder 1 on its compression stroke before identifying the number 1 tower, and follow a replacement camshaft card if the engine has been rebuilt with a nonstandard cam.",source:chevy327396Heritage},
  {slug:"chevrolet/396/firing-order",keyword:"chevy 396 firing order",make:"Chevrolet",model:"396 Big-Block V8",title:"Chevy 396 Firing Order and Distributor Diagram",order:"1-8-4-3-6-5-7-2",numbering:"The driver's-side bank is 1-3-5-7 and the passenger-side bank is 2-4-6-8, with both banks numbered from front to rear.",scope:"Covers traditional Chevrolet Mark IV 396 big-block V8s with distributor ignition and the production firing-order pattern.",caution:"Wire the cap clockwise after locating cylinder 1 at compression TDC. Correct wire order does not prove correct distributor indexing or base ignition timing, so verify those separately after the engine starts.",source:chevy327396Heritage},
  {slug:"chevrolet/427/firing-order",keyword:"chevy 427 firing order",make:"Chevrolet",model:"427 Big-Block V8",title:"Chevy 427 Firing Order and Cylinder Numbering",order:"1-8-4-3-6-5-7-2",numbering:"The left/driver bank carries odd cylinders 1-3-5-7 and the right/passenger bank carries even cylinders 2-4-6-8, front to rear.",scope:"Covers traditional Chevrolet Mark IV 427 big-block V8s with a stock-pattern camshaft and distributor ignition. It does not cover the Gen IV LS7 7.0-liter engine or later coil-on-plug combinations.",caution:"Confirm the engine family before using the diagram. On a Mark IV big-block, identify the first cap tower from cylinder 1 compression TDC, then route the remaining towers clockwise in firing order; do not choose number 1 from cap appearance alone.",source:chevy427Heritage},
  {slug:"ford/390/firing-order",keyword:"ford 390 firing order",make:"Ford",model:"390 FE V8",title:"Ford 390 Firing Order and Cylinder Diagram",order:"1-5-4-2-6-3-7-8",numbering:"Ford numbers the passenger bank 1-2-3-4 and the driver bank 5-6-7-8, with both banks counted from the front of the engine.",scope:"Covers traditional Ford 390 FE-series V8s with distributor ignition and a standard-pattern camshaft.",caution:"The FE order is not the later 351W/5.0 HO sequence. Locate cylinder 1 on its compression stroke, identify the rotor-facing cap tower and then route the remaining towers counterclockwise; cap orientation alone is not a reliable number 1 reference.",source:ford1969ShopManual},
  {slug:"ford/428/firing-order",keyword:"ford 428 firing order",make:"Ford",model:"428 FE V8",title:"Ford 428 Firing Order and Distributor Diagram",order:"1-5-4-2-6-3-7-8",numbering:"The passenger-side bank is 1-2-3-4 and the driver-side bank is 5-6-7-8, front to rear.",scope:"Covers production Ford 428 FE engines, including stock-pattern Cobra Jet applications with distributor ignition.",caution:"Route the distributor counterclockwise only after confirming number 1 at compression TDC. A rebuilt FE can carry a custom camshaft, so use the cam card when it specifies an order different from the factory sequence.",source:ford1969ShopManual},
  {slug:"ford/460/firing-order",keyword:"ford 460 firing order",make:"Ford",model:"460 Lima V8",title:"Ford 460 Firing Order and Cylinder Numbering",order:"1-5-4-2-6-3-7-8",numbering:"Passenger-side cylinders are 1-2-3-4 and driver-side cylinders are 5-6-7-8, numbered from the radiator end toward the firewall.",scope:"Covers production Ford 460 engines in the 385/Lima family using the standard firing-order pattern and distributor ignition.",caution:"Do not transfer a 351W/302 HO diagram to the 460. Establish the first tower from cylinder 1 compression TDC and follow a nonstandard camshaft manufacturer's card when the engine has been modified.",source:fordV8RockerInstruction},
  {slug:"ford/351-cleveland/firing-order",keyword:"ford 351 cleveland firing order",make:"Ford",model:"351 Cleveland V8",title:"Ford 351 Cleveland Firing Order and Diagram",order:"1-3-7-2-6-5-4-8",numbering:"Ford places cylinders 1-2-3-4 on the passenger bank and 5-6-7-8 on the driver bank, front to rear.",scope:"Covers production 351 Cleveland V8s using the standard 351C camshaft order and distributor ignition.",caution:"The 351C order differs from the early 289/302 order even though the engines share Ford's bank-numbering convention. Route the cap counterclockwise and verify number 1 at compression TDC before moving multiple wires.",source:fordV8RockerInstruction},
  {slug:"ford/289/firing-order",keyword:"ford 289 firing order",make:"Ford",model:"289 Small-Block V8",title:"Ford 289 Firing Order and Distributor Diagram",order:"1-5-4-2-6-3-7-8",numbering:"Passenger-side cylinders are 1-2-3-4 and driver-side cylinders are 5-6-7-8, with both banks numbered front to rear.",scope:"Covers original-pattern Ford 289 small-block camshafts and distributor ignition; the camshaft, not the block casting alone, ultimately determines the firing order.",caution:"Many rebuilt 289s receive a 351W/5.0 HO-pattern cam with the alternate 1-3-7-2-6-5-4-8 order. Confirm the camshaft when history is unknown, and locate the number 1 tower from compression TDC before routing the cap counterclockwise.",source:fordEarlyV8Instruction},
  {slug:"toyota/3tc/firing-order",keyword:"toyota 3tc firing order",make:"Toyota",model:"3T-C Inline-Four",title:"Toyota 3T-C Firing Order and Distributor Diagram",order:"1-3-4-2",numbering:"Cylinders 1-2-3-4 run in a straight line from the timing-chain and crank-pulley end toward the transmission.",scope:"Covers Toyota 3T-C 1.8-liter OHV inline-four engines with the original distributor-style ignition arrangement.",caution:"Do not select the first cap terminal by cap position alone. Put cylinder 1 at compression TDC, confirm where the rotor points and preserve the distributor's original rotation and wire routing before disturbing more than one lead.",source:toyota1982Specs},
  {slug:"toyota/4age/firing-order",keyword:"toyota 4age firing order",make:"Toyota",model:"4A-GE Inline-Four",title:"Toyota 4A-GE Firing Order and Cylinder Numbering",order:"1-3-4-2",numbering:"Cylinder 1 is at the timing-belt end; cylinders then count 1-2-3-4 toward the transmission.",scope:"Covers the mechanical firing order shared by Toyota 4A-GE inline-four variants. Distributor, wasted-spark and coil hardware differ between 16-valve and 20-valve generations.",caution:"Treat the sequence and the wiring diagram as separate facts. Identify the exact 4A-GE generation and engine-management system before applying distributor-terminal, igniter or connector details, and verify cylinder 1 compression TDC after distributor removal.",source:toyota4ageManual},
  {slug:"toyota/2jz-gte/firing-order",keyword:"toyota 2jz gte firing order",make:"Toyota",model:"2JZ-GTE Inline-Six",title:"Toyota 2JZ-GTE Firing Order and Coil Diagram",order:"1-5-3-6-2-4",numbering:"Cylinders 1 through 6 run from the timing-belt and crank-pulley end toward the transmission; cylinder 1 is at the front of the engine.",scope:"Covers the production Toyota 2JZ-GTE inline-six mechanical firing order across non-VVT-i and VVT-i versions.",caution:"The firing order stays the same, but coil, igniter and wasted-spark arrangements vary by market and revision. Match electrical testing to the ECU, harness and ignition system actually installed rather than repinning from a generic JZ diagram.",source:toyota2jzManual},
  {slug:"toyota/1jz-gte/firing-order",keyword:"toyota 1jz gte firing order",make:"Toyota",model:"1JZ-GTE Inline-Six",title:"Toyota 1JZ-GTE Firing Order and Coil Diagram",order:"1-5-3-6-2-4",numbering:"Cylinder 1 sits at the timing/front end and the cylinders count consecutively to number 6 at the transmission end.",scope:"Covers the production 1JZ-GTE inline-six mechanical sequence, including common non-VVT-i twin-turbo and VVT-i single-turbo versions.",caution:"Do not assume the same coil control or trigger wiring across JZX revisions. Confirm non-VVT-i versus VVT-i, ECU and harness identity before electrical diagnosis; the mechanical sequence alone does not define ignition-channel wiring.",source:toyotaJzTechnical},
  {slug:"nissan/rb26dett/firing-order",keyword:"nissan rb26dett firing order",make:"Nissan",model:"RB26DETT Inline-Six",title:"Nissan RB26DETT Firing Order and Cylinder Diagram",order:"1-5-3-6-2-4",numbering:"Cylinder 1 is at the timing-belt/front end, followed by cylinders 2 through 6 toward the transmission.",scope:"Covers the production RB26DETT mechanical order used in R32, R33 and R34 Skyline GT-R applications.",caution:"The firing order does not define harness pinout. Match the igniter, coil harness, ECU and cam-angle-sensor procedure to the exact chassis generation, especially when later or standalone components are installed.",source:nissanRb26Manual},
  {slug:"nissan/sr20det/firing-order",keyword:"nissan sr20det firing order",make:"Nissan",model:"SR20DET Inline-Four",title:"Nissan SR20DET Firing Order and Coil Diagram",order:"1-3-4-2",numbering:"Cylinders count 1-2-3-4 from the timing-chain and crank-pulley end toward the transmission.",scope:"Covers the mechanical order shared by common longitudinal and transverse SR20DET variants; ignition hardware varies by chassis.",caution:"Identify S13, S14, S15, GTI-R or other donor configuration before following connector details. Swapped engines often combine harnesses and ECUs, so verify commanded coil channels instead of relying on wire color.",source:nissanSr20Manual},
  {slug:"nissan/ka24de/firing-order",keyword:"nissan ka24de firing order",make:"Nissan",model:"KA24DE Inline-Four",title:"Nissan KA24DE Firing Order and Distributor Diagram",order:"1-3-4-2",numbering:"Cylinder 1 is at the front/timing-chain end, followed in line by 2-3-4 toward the transmission.",scope:"Covers production KA24DE engines; distributor, coil and base-timing procedures differ between 240SX and truck/Frontier applications.",caution:"Use the manual for the actual chassis and year before setting timing or probing connectors. On distributor-equipped versions, establish cylinder 1 compression TDC and rotor position before assigning the first cap tower.",source:nissanKa24Manual},
  {slug:"honda/b18c/firing-order",keyword:"honda b18c firing order",make:"Honda",model:"B18C Inline-Four",title:"Honda B18C Firing Order and Distributor Diagram",order:"1-3-4-2",numbering:"Cylinder 1 is at the timing-belt end; the row then counts 1-2-3-4 toward the transmission and distributor end.",scope:"Covers the mechanical firing order used by Honda/Acura B18C-family engines. Distributor housing, connector and calibration details vary among GSR/GS-R, Type R and market-specific versions.",caution:"Read the block stamp and distributor part number before electrical diagnosis. When leads have been removed, establish cylinder 1 compression TDC and rotor position rather than copying an arbitrary cap drawing from a different B-series distributor.",source:hondaIntegraManual},
  {slug:"honda/b16a/firing-order",keyword:"honda b16a firing order",make:"Honda",model:"B16A Inline-Four",title:"Honda B16A Firing Order and Distributor Diagram",order:"1-3-4-2",numbering:"Cylinder 1 sits at the timing-belt end, followed by 2-3-4 toward the transmission/distributor end.",scope:"Covers Honda B16A-family distributor engines while recognizing that distributor and ignition-control hardware changed across OBD generations and markets.",caution:"Do not choose a cap tower only from its physical height or a photo of another distributor. Confirm cylinder 1 on its compression stroke and the rotor-facing terminal, then follow the correct distributor rotation and exact manual for the installed unit.",source:hondaB16Manual},
  {slug:"honda/k20/firing-order",keyword:"honda k20 firing order",make:"Honda",model:"K20 Inline-Four",title:"Honda K20 Firing Order and Cylinder Numbering",order:"1-3-4-2",numbering:"Cylinder 1 is at the timing-chain end and cylinders count 1-2-3-4 toward the transmission.",scope:"Covers the shared mechanical firing order of common Honda K20-family inline-four engines, including K20A2, K20A3 and K20Z1 service-manual applications. Coil part numbers and ECU strategy remain suffix-specific.",caution:"A coil-on-plug engine has no distributor-cap routing to copy. Do not infer coil number from harness branch length on swapped or modified looms; verify cylinder location, connector identity and ECU pinout for the exact engine and chassis combination.",source:hondaK20Manual},
  {slug:"subaru/fa20/firing-order",keyword:"subaru fa20 firing order",make:"Subaru",model:"FA20 Boxer-Four",title:"Subaru FA20 Firing Order and Boxer Cylinder Diagram",order:"1-3-2-4",numbering:"In common North American installed orientation, cylinders 1 and 3 occupy the passenger/right bank front-to-rear, while 2 and 4 occupy the driver/left bank front-to-rear.",scope:"Covers the mechanical cylinder order shared by Subaru FA20 naturally aspirated and turbocharged boxer-four applications; control systems and service procedures remain engine-code specific.",caution:"Do not number cylinders straight across the engine bay. FA20D/BRZ naturally aspirated and FA20F/DIT turbo systems are different diagnostic applications, so match coil connectors, ECU tests and fuel-system procedures to the exact vehicle.",source:subaruFaManual},
  {slug:"mazda/13b/firing-order",keyword:"mazda 13b firing order",make:"Mazda",model:"13B Rotary",title:"Mazda 13B Firing Sequence: Rotor and Plug Identification",order:"Alternating front- and rear-rotor combustion events; no piston-style cylinder order",numbering:"A 13B has front and rear rotor housings, not numbered piston cylinders. Each housing uses a leading plug and a trailing plug that fire at different points in the same combustion event.",scope:"Covers the firing-sequence concept for two-rotor Mazda 13B engines. Distributor, distributorless, wasted-spark and ECU-controlled arrangements vary substantially from early 13B applications through FC, FD 13B-REW and RENESIS derivatives.",caution:"Do not apply a four-cylinder 1-3-4-2 chart or treat all four plugs as four cylinders. First identify front versus rear housing and L/leading versus T/trailing plugs, then use the workshop diagram for the exact ignition generation; crossed leading and trailing leads can produce a no-start or severe misfire.",source:mazda13bManual},
  {slug:"mitsubishi/4g63/firing-order",keyword:"mitsubishi 4g63 firing order",make:"Mitsubishi",model:"4G63 Inline-Four",title:"Mitsubishi 4G63 Firing Order and Cylinder Diagram",order:"1-3-4-2",numbering:"Mitsubishi numbers the cylinders 1-2-3-4 from the front/timing-belt side toward the transmission.",scope:"Covers the factory mechanical firing order of common naturally aspirated and turbocharged 4G63 inline-four engines; ignition hardware varies by model and generation.",caution:"Keep the mechanical order separate from coil pairing and ECU output order. Wasted-spark systems, later coil-on-plug conversions and different cam-angle-sensor/ECU generations require the diagram for the installed application.",source:mitsubishi4g63Manual},
];

function firingPage(j:FiringJob):SpecRecord{
  const answer=j.order.startsWith("Alternating")?`${j.order}. ${j.numbering}`:`The ${j.model} firing order is ${j.order}. ${j.numbering}`;
  return firingGuide({slug:j.slug,keyword:j.keyword,make:j.make,model:j.model,category:"Firing Order",title:j.title,
    metaDescription:`${j.title} with ${j.order}, physical numbering, identification cautions and routing procedure.`,answer,scope:j.scope,detail:j.caution,
    values:[{label:"Firing order",value:j.order,note:"Confirm exact engine"},{label:"Physical numbering",value:j.numbering,note:"Orient by the timing/front end"}],sources:[j.source],identity:j.model,distinctions:[j.scope,j.caution],featureImage:engineImage,featureOverlay:true});
}

type HeadJob={slug:string;keyword:string;make:string;model:string;title:string;answer:string;scope:string;detail:string;values:SpecValue[];source:Source};
const headJobs:HeadJob[]=[
  {slug:"dodge/318/head-bolt-torque",keyword:"dodge 318 head bolt torque specs",make:"Dodge",model:"318 LA V8",title:"Dodge 318 Head Bolt Torque Specs and Sequence",answer:"The referenced Chrysler 318 service manual specifies 85 lb-ft for production-style cylinder-head bolts. Apply the final value only after matching the LA-era iron head, factory-type fastener, gasket and thread treatment.",scope:"Covers traditional Chrysler LA 318 iron-head combinations; Magnum 5.2L, Poly 318 and aftermarket aluminum heads or stud kits are separate applications.",detail:"Tighten from the center outward in progressive passes, verify whether the exact application calls for sealant, and follow the gasket or replacement-fastener maker when its lubricant or retorque instructions differ.",values:[{label:"Chrysler manual final torque",value:"85 lb-ft",note:"Production-style 318 hardware"},{label:"Suggested staged workflow",value:"30, 60, then 85 lb-ft",note:"Maintain the exact center-out order"},{label:"Aftermarket studs/heads",value:"Component-maker procedure",note:"Do not transfer the stock value"}],source:chrysler318Manual},
  {slug:"dodge/360/head-bolt-torque",keyword:"dodge 360 head bolt torque specs",make:"Dodge",model:"360 / 5.9L Magnum V8",title:"Dodge 360 Head Bolt Torque Specs: LA vs. 5.9 Magnum",answer:"The covered 1994 Dodge 5.9L Magnum service procedure tightens the head bolts in sequence to 50 lb-ft, then repeats the sequence to a final 105 lb-ft. Do not transfer that chart automatically to every earlier LA 360 or an aftermarket head/stud build.",scope:"The numerical chart is for the documented 1994 5.9L Magnum factory-bolt application. Earlier LA passenger, truck and marine engines—and aluminum heads or stud kits—must use their exact casting, gasket and fastener instructions.",detail:"Keep pushrods and rocker assemblies identified, clean the deck and bolt holes, start every bolt by hand, and complete both passes in the service manual's numbered center-out pattern. Fastener lubricant or sealant changes clamping load.",values:[{label:"1994 5.9L Magnum stage 1",value:"50 lb-ft (68 N·m)",note:"Follow the numbered sequence"},{label:"1994 5.9L Magnum stage 2",value:"105 lb-ft (142 N·m)",note:"Repeat the complete sequence"},{label:"Earlier LA 360",value:"Year/casting-specific",note:"Do not assume the Magnum chart"},{label:"Aftermarket heads or studs",value:"Component-maker procedure",note:"Specified lubricant controls"}],source:dodge360MagnumHead},
  {slug:"pontiac/400/head-bolt-torque",keyword:"pontiac 400 head bolt torque specs",make:"Pontiac",model:"400 V8",title:"Pontiac 400 Head Bolt Torque Specs and Pattern",answer:"The cited 1968 Pontiac service manual specifies 95 lb-ft for the traditional Pontiac V8 cylinder-head bolts. Use that value only with the matching production-style iron head, factory-type bolt and manual-specified thread condition.",scope:"Covers the traditional Pontiac-built 400 V8 architecture represented by the 1968 service data. Ram Air variations, later emissions-era revisions, aftermarket aluminum heads, studs and Chevrolet-engine swaps require separate documentation.",detail:"Identify every bracket and bolt position before assembly, prepare the threads exactly as the applicable manual requires, and approach 95 lb-ft through even center-out passes. Aftermarket fastener lubricant can materially change clamp load.",values:[{label:"1968 Pontiac service value",value:"95 lb-ft (129 N·m)",note:"Traditional production-style V8 hardware"},{label:"Tightening order",value:"Center outward",note:"Use the exact numbered Pontiac pattern"},{label:"Aluminum heads or studs",value:"Component-maker chart",note:"Do not reuse the stock value"}],source:pontiac1968Service},
  {slug:"chevrolet/327/head-bolt-torque",keyword:"chevy 327 head bolt torque specs",make:"Chevrolet",model:"327 Small-Block V8",title:"Chevy 327 Head Bolt Torque Specs and Sequence",answer:"A production-style Gen I Chevrolet small-block commonly finishes the head bolts at 65 lb-ft. Chevrolet Performance's documented HT383 procedure reaches that value in three passes—25, 40 and 65 lb-ft—with Teflon pipe sealant for its covered assembly.",scope:"The 65 lb-ft reference is for traditional Gen I iron-block, iron-head, factory-style bolt architecture. The linked HT383 guide corroborates the procedure on a later Chevrolet Performance Gen I package; original 327 year/casting data, aluminum heads and aftermarket studs can differ.",detail:"Clean and dry the blind areas, apply only the specified sealer or lubricant, hand-start every bolt, and use the exact center-out sequence. Chevrolet Performance calls for a 10-hour head-bolt recheck on its HT383 package; apply that recheck only when the exact engine/gasket instructions require it.",values:[{label:"Pass 1",value:"25 lb-ft (34 N·m)",note:"Teflon pipe sealant in cited Gen I guide"},{label:"Pass 2",value:"40 lb-ft (54 N·m)",note:"Maintain the numbered sequence"},{label:"Final pass",value:"65 lb-ft (88 N·m)",note:"Production-style Gen I reference"},{label:"Aluminum head or stud kit",value:"Component-maker procedure",note:"Different lubricant and clamp load"}],source:chevyGen1Head},
  {slug:"ford/460/head-bolt-torque",keyword:"ford 460 head bolt torque specs",make:"Ford",model:"460 / 7.5L Lima V8",title:"Ford 460 Head Bolt Torque Specs and Sequence",answer:"For the covered 1984 Ford F-250 7.5L/460, tighten the factory head bolts in sequence to 80 lb-ft, then 110 lb-ft, and finally 130–140 lb-ft. The manual states that no extended-operation retorque is required when this procedure is followed.",scope:"The numerical stages apply to the documented 1984 truck 460 with production-style iron heads and bolts. Earlier passenger-car 429/460 engines, later EFI revisions, industrial engines, aluminum heads and stud kits require their own instructions.",detail:"Place the longer bolts in the lower-row positions identified by the manual, guide the head over the dowels without coating the gasket faces, and complete every pass in the illustrated sequence. Do not simply choose 140 lb-ft without matching year, bolt position and thread condition.",values:[{label:"Pass 1",value:"80 lb-ft (108 N·m)",note:"Exact Ford sequence"},{label:"Pass 2",value:"110 lb-ft (149 N·m)",note:"Repeat the complete sequence"},{label:"Final pass",value:"130–140 lb-ft (177–189 N·m)",note:"Covered 1984 460 application"},{label:"Long bolts",value:"Lower-row positions",note:"Keep bolt locations correct"},{label:"Aftermarket heads/studs",value:"Component-maker procedure",note:"Do not use the factory range"}],source:ford460_1984Head},
  {slug:"ford/351-cleveland/head-bolt-torque",keyword:"ford 351 cleveland head bolt torque specs",make:"Ford",model:"1970–1974 351 Cleveland V8",title:"Ford 351 Cleveland Head Bolt Torque Specs",answer:"Fel-Pro's production-engine table lists 95–105 lb-ft for the 1970–1974 Ford 351 Cleveland cylinder-head bolts. Reach the final range through progressive center-out passes rather than applying full torque to one bolt at a time.",scope:"The 95–105-lb-ft range is for production-style 351C iron-head combinations. Boss 351 hardware, Australian Cleveland variants, 351M/400 engines, 351 Windsor engines, aluminum heads and aftermarket studs are separate applications even when a catalog calls them all '351.'",detail:"Identify the Cleveland by casting and architecture before assembly, then match the gasket and bolt manufacturer's lubricant requirement. Clean blind holes so trapped oil cannot hydraulically crack the block or give a false reading, install every bolt in its correct location, and finish each progressive pass in the exact factory pattern.",values:[{label:"1970–1974 production 351C",value:"95–105 lb-ft",note:"Fel-Pro application table"},{label:"Recommended working method",value:"Progressive center-out passes",note:"Use exact factory sequence"},{label:"Boss / aftermarket hardware",value:"Separate procedure",note:"Do not transfer production value"},{label:"351W or 351M/400",value:"Different engine family",note:"Identify castings first"}],source:felpro351cHead},
  {slug:"ford/289/head-bolt-torque",keyword:"ford 289 head bolt torque specs",make:"Ford",model:"1966 289 Small-Block V8",title:"Ford 289 Head Bolt Torque Specs and Sequence",answer:"The 1966 Ford shop manual specifies three progressive cylinder-head passes for the 289: 50 lb-ft, 60 lb-ft, and a final 65–70 lb-ft, following the illustrated sequence.",scope:"These stages apply to the documented 1966 production 289 with factory-style iron heads, bolts and gasket. Other model years, Hi-Po combinations, replacement aluminum heads and stud kits must use their matching Ford or component-maker instructions.",detail:"Clean the block's bolt holes and confirm every bolt length before lowering the head over the dowels. Apply only the thread treatment prescribed for the exact gasket and hardware, then complete each pass across the entire head before increasing torque. Do not substitute later 5.0L long-bolt/short-bolt figures for this 1966 procedure.",values:[{label:"Pass 1",value:"50 lb-ft (68 N·m)",note:"1966 Ford sequence"},{label:"Pass 2",value:"60 lb-ft (81 N·m)",note:"Repeat complete pattern"},{label:"Final pass",value:"65–70 lb-ft (88–95 N·m)",note:"Production 1966 289"},{label:"Later 302/5.0L",value:"Different procedure",note:"Do not transfer bolt-group values"},{label:"Aftermarket heads/studs",value:"Component-maker procedure",note:"Lubricant-specific"}],source:ford1966_289Head},
  {slug:"toyota/4age/head-bolt-torque",keyword:"toyota 4age head bolt torque specs",make:"Toyota",model:"4A-GE Inline-Four",title:"Toyota 4A-GE Head Bolt Torque Specs by Generation",answer:"For the later 4A-GE procedure documented in Toyota's repair manual, oil the bolt threads and undersides, tighten the ten bolts to 29 N·m (22 lb-ft), then turn each bolt 90° and another 90° in sequence. Early AE86-era 4A-GE engines can use a different final-torque procedure.",scope:"The numerical torque-angle chart applies to the later factory-bolt 4A-GE revision covered by the linked manual. Early 16-valve engines, 20-valve market variants, 4A-GZE combinations and aftermarket studs must be identified separately.",detail:"Toyota identifies two bolt lengths, requires several even passes for the initial torque, and uses paint marks to verify both angle turns. Inspect the bolts to the manual's dimensional limits and never merge an early single-torque chart with the later angle procedure.",values:[{label:"Later 4A-GE initial torque",value:"29 N·m (22 lb-ft)",note:"Oiled threads and bolt undersides"},{label:"Angle pass 1",value:"90°",note:"Exact ten-bolt sequence"},{label:"Angle pass 2",value:"Additional 90°",note:"Verify with paint marks"},{label:"Early 4A-GE",value:"Different procedure",note:"Confirm engine/year before assembly"},{label:"Bolt locations",value:"Two documented lengths",note:"Do not interchange positions"}],source:toyota4ageManual},
  {slug:"toyota/2jz-gte/head-bolt-torque",keyword:"toyota 2jz gte head bolt torque specs",make:"Toyota",model:"2JZ-GTE Inline-Six",title:"Toyota 2JZ-GTE Head Bolt Torque Specs and Sequence",answer:"The 1997 Toyota Supra 2JZ-GTE repair manual specifies 34 N·m (25 lb-ft) for the oiled factory head bolts, followed by 90° and another 90° in the illustrated 14-bolt sequence.",scope:"Covers the production 2JZ-GTE factory-bolt procedure documented in the 1997 Supra manual. Other market revisions, resurfaced assemblies, nonstandard gaskets and aftermarket stud kits require their matching instructions.",detail:"Install all 14 plate washers, lightly oil the threads and under-head surfaces, reach the initial torque in several passes, then paint-mark the bolt heads before both angle stages. Replace any bolt that breaks, deforms or cannot meet the initial torque requirement.",values:[{label:"Initial torque",value:"34 N·m (25 lb-ft)",note:"Several passes; oiled factory bolts"},{label:"Angle pass 1",value:"90°",note:"Follow the 14-bolt sequence"},{label:"Angle pass 2",value:"Additional 90°",note:"Paint marks finish toward the rear"},{label:"Plate washers",value:"14 required",note:"Install under every bolt head"},{label:"Aftermarket studs",value:"Stud-maker procedure",note:"Factory angle stages do not apply"}],source:toyota2jzHeadManual},
  {slug:"nissan/rb26dett/head-bolt-torque",keyword:"nissan rb26dett head bolt torque specs",make:"Nissan",model:"RB26DETT Inline-Six",title:"Nissan RB26DETT Head Bolt Torque Specs and Sequence",answer:"The Nissan R32 RB26DETT engine manual specifies 29 N·m, then 108 N·m, complete loosening, 29 N·m again, and finally an 85–90° turn for the fourteen M12 head bolts. The manual also gives 103–113 N·m only as the alternative when an angle wrench is not used.",scope:"Covers the production R32 RB26DETT factory-bolt procedure in the linked Nissan engine manual. R33/R34 revisions, N1 parts, resurfaced decks, nonstandard metal gaskets and aftermarket studs require their matching service or fastener documentation.",detail:"Oil the factory bolt threads as specified, work through the exact fourteen-bolt sequence, and never estimate the final angle visually. The small M6 end bolts use a separate 9–12 N·m specification and must not receive the M12 stages.",values:[{label:"M12 stage 1",value:"29 N·m (22 lb-ft)",note:"Exact 14-bolt sequence"},{label:"M12 stage 2",value:"108 N·m (80 lb-ft)",note:"Repeat sequence"},{label:"M12 stage 3",value:"Loosen completely",note:"Return all bolts to zero"},{label:"M12 stage 4",value:"29 N·m (22 lb-ft)",note:"Re-establish base torque"},{label:"M12 stage 5",value:"85–90°",note:"Use an angle wrench"},{label:"M6 end bolts",value:"9–12 N·m",note:"Separate small-fastener value"}],source:nissanRb26Manual},
  {slug:"nissan/sr20det/head-bolt-torque",keyword:"nissan sr20det head bolt torque specs",make:"Nissan",model:"S14 SR20DET Inline-Four",title:"Nissan SR20DET Head Bolt Torque Specs and Sequence",answer:"For the 1994 S14 SR20DET factory-bolt procedure, tighten the ten main head bolts to 39 N·m (29 lb-ft), then 78 N·m (58 lb-ft), loosen them completely, retighten to 34–44 N·m (25–33 lb-ft), and turn each bolt 90–95° in sequence.",scope:"These stages are tied to the S14 SR20DET workshop manual. S13 and S15 market revisions, GTi-R transverse installations, replacement blocks or heads, nonstandard gaskets and aftermarket studs must be checked against their own documentation.",detail:"Oil the factory-bolt threads and seating surfaces as the manual directs, install the washers, and replace any bolt longer than the 158.2 mm (6.228 in) limit. Use an angle wrench for the final turn; if paint marks are used as the manual's alternative, complete one 90–95° pass rather than attempting 180–190° at once.",values:[{label:"Stage 1",value:"39 N·m (29 lb-ft)",note:"Exact ten-bolt sequence"},{label:"Stage 2",value:"78 N·m (58 lb-ft)",note:"Repeat full sequence"},{label:"Stage 3",value:"Loosen completely",note:"All ten bolts"},{label:"Stage 4",value:"34–44 N·m (25–33 lb-ft)",note:"Re-establish base torque"},{label:"Final stage",value:"90–95°",note:"Use angle wrench or manual paint-mark method"},{label:"Maximum bolt length",value:"158.2 mm (6.228 in)",note:"Replace if exceeded"}],source:nissanS14Sr20Head},
  {slug:"honda/b18c/head-bolt-torque",keyword:"honda b18c head bolt torque specs",make:"Honda",model:"B18C1 Inline-Four",title:"Honda B18C Head Bolt Torque Specs and Sequence",answer:"For the 1998 Acura Integra GS-R B18C1, apply clean engine oil to the bolt threads and under-head surfaces, tighten all head bolts in sequence to 29 N·m (22 lb-ft), then repeat the sequence to a final 85 N·m (63 lb-ft).",
    scope:"The numerical procedure applies to the documented U.S.-market 1998 B18C1 GS-R factory-bolt application. B18C5 Type R, Japanese-market B18C variants, B16/B18B engines, swaps and aftermarket studs require their exact manual or fastener chart.",detail:"Use the illustrated center-out Honda sequence for both passes and do not mix cylinder-head values with the separate cam-holder sealing bolts. Inspect the block/head surfaces and preserve each application-specific bracket and bolt position.",values:[{label:"Pass 1",value:"29 N·m (22 lb-ft)",note:"Clean engine oil on threads and under heads"},{label:"Final pass",value:"85 N·m (63 lb-ft)",note:"Repeat exact B18C1 sequence"},{label:"B18C5/JDM variants",value:"Verify separately",note:"Do not assume B18C1 equivalence"},{label:"Aftermarket studs",value:"Fastener-maker procedure",note:"Specified lubricant controls"}],source:hondaB18cHeadManual},
  {slug:"honda/k20/head-bolt-torque",keyword:"honda k20 head bolt torque specs",make:"Honda",model:"K20A2 / K20A3 Inline-Four",title:"Honda K20 Head Bolt Torque Specs and Sequence",answer:"For the early Acura RSX K20 procedure, oil the bolt threads and under-head surfaces, tighten the ten head bolts to 39 N·m (29 lb-ft), then turn each bolt 90° and another 90° in sequence. A new factory bolt receives one additional 90° turn under this procedure.",scope:"The numerical stages apply to the 2002–2005-era K20A2/K20A3 RSX procedure documented by the linked service manual. Later K20Z/K20C turbo engines, swaps, mixed K20/K24 assemblies and aftermarket studs require their exact engine-code and fastener instructions.",detail:"Measure every bolt at the manual's A and B points and replace it if either diameter is below 10.6 mm. If a bolt is turned beyond the specified angle, remove it and restart the installation step; do not back it off to the paint mark.",values:[{label:"Initial torque",value:"39 N·m (29 lb-ft)",note:"Oiled factory bolts; exact sequence"},{label:"Angle pass 1",value:"90°",note:"All ten bolts"},{label:"Angle pass 2",value:"Additional 90°",note:"All ten bolts"},{label:"New factory bolt",value:"One extra 90°",note:"Only where this manual procedure applies"},{label:"Minimum bolt diameter",value:"10.6 mm (0.42 in)",note:"Replace if either measured point is smaller"}],source:hondaK20Manual},
  {slug:"honda/k24/head-bolt-torque",keyword:"honda k24 head bolt torque specs",make:"Honda",model:"K24Z7 Inline-Four",title:"Honda K24 Head Bolt Torque Specs by Engine Code",answer:"For the K24Z7 factory-bolt procedure, apply new engine oil to the threads and under-head surfaces, tighten the ten head bolts to 39 N·m (29 lb-ft), then turn every bolt 90° and another 90° in sequence. A new factory head bolt receives one additional 90° turn.",scope:"The numerical stages on this page apply specifically to the K24Z7 procedure in the cited Civic service information. K24A, K24A2/A4/A8, K24Z2/Z3, Earth Dreams K24W, mixed K20/K24 builds and aftermarket stud kits require the exact engine-code or fastener-maker procedure.",detail:"Measure each factory bolt at both inspection points and replace it if either diameter is below 10.6 mm (0.417 in). Use a beam-type wrench or tighten a click wrench slowly for the 39 N·m stage. If a bolt makes noise or is turned beyond the required angle, remove it and restart the prescribed operation instead of backing it up to the paint mark.",values:[{label:"Initial torque",value:"39 N·m (29 lb-ft)",note:"Oiled threads and under-head surfaces"},{label:"Angle pass 1",value:"90°",note:"All ten bolts in sequence"},{label:"Angle pass 2",value:"Additional 90°",note:"All ten bolts"},{label:"New factory bolt",value:"One extra 90°",note:"K24Z7 manual condition"},{label:"Minimum bolt diameter",value:"10.6 mm (0.417 in)",note:"Measure at both specified points"},{label:"Other K24 variants",value:"Verify separately",note:"Do not generalize this chart"}],source:hondaK24z7Head},
  {slug:"subaru/ej20/head-bolt-torque",keyword:"subaru ej20 head bolt torque specs",make:"Subaru",model:"EJ20 Boxer-Four",title:"Subaru EJ20 Head Bolt Torque Specs by Engine Code",answer:"EJ20 head-bolt procedures vary across SOHC, DOHC, turbo and model-year versions and often include torque, loosen and angle stages.",scope:"Covers EJ20 identification only; use the complete engine code and exact Subaru sequence.",detail:"Boxer heads are serviced separately by bank, and bolt positions may receive different final angle stages.",values:[{label:"Procedure",value:"Torque, loosen and angle",note:"Variant-specific"},{label:"Required identity",value:"SOHC/DOHC/turbo and code",note:"Do not generalize"}],source:S.subaru},
  {slug:"subaru/fa20/head-bolt-torque",keyword:"subaru fa20 head bolt torque specs",make:"Subaru",model:"FA20D BRZ Boxer-Four",title:"Subaru FA20 Head Bolt Torque Specs and Sequence",answer:"For the naturally aspirated BRZ FA20 procedure, oil the six main bolt threads and washers, tighten in order to 20 N·m, then 100 N·m, loosen each 360°, retighten to 20 N·m and 42 N·m, then complete the manual's position-specific angle turns.",scope:"The numerical stages apply to the FA20D/4U-GSE BRZ-style engine covered by the linked service manual. Turbo FA20DIT WRX/Forester engines, later FA24 engines and aftermarket studs use different procedures.",detail:"After the 42 N·m stage, turn all six bolts 100° in sequence; the two designated bolts then receive another 100°, while the other four receive another 50°. Use the factory angle tool/order for each bank and restart the specified preparation if a bolt produces stick-slip noise.",values:[{label:"Stage 1",value:"20 N·m (14.8 lb-ft)",note:"Oiled threads and washers"},{label:"Stage 2",value:"100 N·m (73.8 lb-ft)",note:"Exact six-bolt order"},{label:"Stage 3",value:"Loosen 360°",note:"Each main bolt in order"},{label:"Stages 4 and 5",value:"20 N·m, then 42 N·m",note:"14.8 then 31.0 lb-ft"},{label:"Angle stage",value:"All six +100°",note:"Use angle gauge/SST"},{label:"Position-specific finish",value:"Two +100°; four +50°",note:"Follow the factory bolt map"}],source:subaruFa20HeadManual},
];

function headPage(j:HeadJob):SpecRecord{return {slug:j.slug,keyword:j.keyword,make:j.make,model:j.model,category:"Torque Specs",title:j.title,
  metaDescription:`${j.title} with application boundaries, staged tightening guidance, reuse cautions and official service-information lookup.`,answer:j.answer,scope:j.scope,detail:j.detail,values:j.values,sources:[j.source],reviewed,featureImage:engineImage,featureOverlay:true,
  diagram:{type:"head",title:`Interactive ${j.model} center-out sequence aid`,caption:"This balanced pattern is an orientation aid; use the exact numbered manufacturer diagram for assembly.",points:["1","5","9","7","3","4","8","10","6","2"]},
  intro:[j.answer,j.scope],steps:["Identify the complete engine code, head, gasket and fastener kit.","Verify flatness, surface finish, clean threads and empty bolt holes.","Apply the exact lubricant, torque, loosen and angle stages in the numbered sequence."],
  sections:[{heading:`Application boundaries for ${j.model}`,paragraphs:[j.scope,j.detail]}],faqs:[{q:`What are the ${j.keyword}?`,a:j.answer},{q:"Can the original head bolts be reused?",a:"Only when the exact service procedure permits reuse and the bolts pass its inspection limits."},{q:"Do aftermarket studs use the stock torque?",a:"No assumption is safe. Use the stud maker's value, lubricant and sequence for the exact kit."}]};}

type SparkJob={slug:string;keyword:string;make:string;model:string;title:string;answer:string;scope:string;detail:string;values:SpecValue[];source:Source};
const sparkJobs:SparkJob[]=[
  {slug:"dodge/318/spark-plug-gap",keyword:"dodge 318 spark plug gap",make:"Dodge",model:"318 LA / 5.2L Magnum V8",title:"Dodge 318 Spark Plug Gap by Ignition System and Year",answer:"The cited 1994 Dodge 5.2L Magnum truck service specification lists a 0.9 mm (0.035 in) gap for the Champion RC12YC plug. A 0.035-inch gap is also common on many earlier 318 applications, but year, emissions package and ignition system must be identified.",scope:"The exact part-number row applies to the documented 1994 5.2L Magnum truck. Poly 318, earlier LA engines, industrial/marine versions, later emissions calibrations and modified ignition systems require their own label or manual.",detail:"Gap does not identify the correct plug by itself. Confirm thread reach, seat, heat range and resistor type; measure with a wire gauge, move only the ground strap and discard plugs with a cracked insulator or badly worn electrodes.",values:[{label:"1994 5.2L Magnum",value:"0.035 in (0.9 mm)",note:"Champion RC12YC in cited service data"},{label:"Many earlier LA applications",value:"0.035 in reference",note:"Verify year and emissions label"},{label:"Other 318 families",value:"Application-specific",note:"Poly, industrial and modified engines differ"}],source:dodge318MagnumSpark},
  {slug:"dodge/360/spark-plug-gap",keyword:"dodge 360 spark plug gap",make:"Dodge",model:"360 LA / 5.9L Magnum V8",title:"Dodge 360 Spark Plug Gap by Model Year and Ignition",answer:"The 1994 Dodge 5.9L Magnum truck service specification lists a 0.9 mm (0.035 in) gap for the specified Champion RC12YC plug. A 0.035-inch setting is also common on many earlier distributor-era 360s, but the emissions label and exact manual remain the authority.",scope:"The exact part-number row shown here is for the covered 1994 5.9L Magnum truck. Earlier LA 360, emissions packages, LPG/marine engines, later replacement heads and modified ignition systems can require different plugs or verification.",detail:"Match part number, thread reach, gasket seat and heat range before checking gap. Measure with a wire gauge, move only the ground strap, and replace a damaged fine-wire or badly worn plug instead of forcing it back to size.",values:[{label:"1994 5.9L Magnum",value:"0.035 in (0.9 mm)",note:"Champion RC12YC in cited manual"},{label:"Many earlier LA applications",value:"0.035 in reference",note:"Confirm year and emissions label"},{label:"Plug selection",value:"Application-specific",note:"Gap alone cannot identify the correct plug"}],source:dodge360MagnumSpark},
  {slug:"chevrolet/454/spark-plug-gap",keyword:"chevy 454 spark plug gap",make:"Chevrolet",model:"1974 Corvette LS4 454 V8",title:"Chevy 454 Spark Plug Gap by Ignition Type",answer:"For the 1974 Corvette LS4 454 with the specified ACR44T plug, Chevrolet-era specifications give a 0.033–0.038 in range; 0.035 in is the nominal setting. Other 454 years and ignition systems must be looked up separately.",scope:"The exact range applies to the documented 1974 Corvette LS4 454. Earlier points-equipped cars, Chevrolet and GMC trucks, motorhome chassis, marine 7.4L engines, later HEI systems, EFI 7.4L engines and crate engines can specify a different plug, reach, heat range or gap.",detail:"Read the under-hood emissions label first when the engine and ignition remain original. Confirm the cylinder-head plug seat and thread reach, measure the gap with a wire gauge, and move only the ground electrode. A wider gap sometimes associated with HEI is not automatically correct for every 454, especially when the distributor, coil, heads or plug design has changed.",values:[{label:"1974 Corvette LS4 454",value:"0.033–0.038 in",note:"0.84–0.97 mm; ACR44T"},{label:"Nominal setting",value:"0.035 in",note:"Within the documented range"},{label:"Truck / later HEI / EFI / crate",value:"Application-specific",note:"Use label or exact manual"},{label:"Plug identity",value:"Part, reach and seat must match",note:"Gap alone is insufficient"}],source:chevy1974Corvette454Spark},
  {slug:"ford/460/spark-plug-gap",keyword:"ford 460 spark plug gap",make:"Ford",model:"460 / 7.5L Lima V8",title:"Ford 460 Spark Plug Gap by Ignition System and Model Year",answer:"For the covered 1996 Ford F-Series 7.5L/460, the service specification is 0.042–0.046 in (1.07–1.17 mm). Earlier carbureted and breaker-point 460 applications commonly use narrower settings, so the late EFI range is not a universal 460 specification.",scope:"The numerical range is tied to the 1996 F-Series 7.5L gasoline application. Earlier cars, carbureted trucks and vans, motorhome chassis, industrial engines, replacement cylinder heads and modified ignition systems require their exact year and calibration data.",detail:"Match the Motorcraft-equivalent part number, thread reach, seat and heat range before setting gap. The cited 1996 service data also lists 7–15 lb-ft installation torque for gasoline engines other than the 4.9L; use the exact plug/head procedure and avoid anti-seize unless instructed.",values:[{label:"1996 F-Series 7.5L",value:"0.042–0.046 in",note:"1.07–1.17 mm"},{label:"1996 installation torque",value:"7–15 lb-ft",note:"Service-data range for covered application"},{label:"Earlier carbureted/points 460",value:"Year-specific; often narrower",note:"Do not transfer the 1996 EFI range"},{label:"Modified ignition/head",value:"Component-specific",note:"Plug maker and tuner control"}],source:ford460_1996Spark},
  {slug:"toyota/2jz-gte/spark-plug-gap",keyword:"toyota 2jz gte spark plug gap",make:"Toyota",model:"2JZ-GTE Inline-Six",title:"Toyota 2JZ-GTE Spark Plug Gap: Factory Spec and Modified Engines",answer:"Toyota's 2JZ-GTE repair manual specifies 1.1 mm (0.043 in) for a new stock-type spark plug and 1.3 mm (0.051 in) as the maximum gap for a used plug. Narrower gaps often discussed for high-boost engines are tuning choices, not the stock factory specification.",scope:"Covers the factory PK20R11 or BKR6EP11-style 2JZ-GTE ignition specification. Modified boost, fuel, plug heat range, coils and engine management require tuner and plug-maker guidance.",detail:"Toyota says not to adjust a used plug. When adjusting a new plug, bend only the base of the ground electrode without contacting the tip; install to 18 N·m (13 lb-ft) where this exact factory procedure applies.",values:[{label:"New stock-type plug",value:"1.1 mm (0.043 in)",note:"Toyota repair-manual specification"},{label:"Used-plug maximum",value:"1.3 mm (0.051 in)",note:"Replace rather than readjust a used plug"},{label:"Installation torque",value:"18 N·m (13 lb-ft)",note:"Clean threads; exact factory application"},{label:"Modified/high-boost engine",value:"Calibration-specific",note:"A narrower gap is not the stock spec"}],source:toyota2jzIgnition},
];
function sparkPage(j:SparkJob):SpecRecord{return sparkGuide({slug:j.slug,keyword:j.keyword,make:j.make,model:j.model,category:"Ignition Specs",title:j.title,
  metaDescription:`${j.title} with application chart, ignition-system differences, approved-plug cautions and official service lookup.`,answer:j.answer,scope:j.scope,detail:j.detail,values:j.values,sources:[j.source],identity:j.model,distinctions:[j.scope,j.detail],featureImage:engineImage,featureOverlay:true});}

export const classicPerformanceSpecs:SpecRecord[]=[...firingJobs.map(firingPage),...headJobs.map(headPage),...sparkJobs.map(sparkPage)];
