import type { Source, SpecRecord, SpecValue } from "./chevy350-content";
import { dieselServiceFaqs } from "./diesel-service-faqs";
import { firingGuide, oilGuide } from "./extended-content";

const reviewed="2026-08-14";
const engineImage="/features/shared-firing-engine.png";
const oilImage="/features/shared-lug-suv.png";
const src=(label:string,url:string,note:string):Source=>({label,url,note});
const S={
  gm:src("GM service and owner information","https://experience.gm.com/support/vehicle/manuals-guides","Official Chevrolet and GMC model-year manual lookup; service procedures require engine/RPO matching."),
  ford:src("Ford owner and service information","https://www.ford.com/support/owner-manuals/","Official Ford year/VIN manual lookup."),
  mopar:src("Mopar vehicle information","https://vehicleinfo.mopar.com/","Official Ram, Dodge and Jeep model-year information lookup."),
  cummins:src("Cummins QuickServe Online","https://quickserve.cummins.com/","Official Cummins engine-serial-number service-information source."),
  toyota:src("Toyota owner's manuals","https://www.toyota.com/owners/warranty-owners-manuals/","Official Toyota model-year manual lookup."),
  honda:src("Honda owner's manuals","https://mygarage.honda.com/s/manuals-search","Official Honda model-year and body-style manual lookup."),
  subaru:src("Subaru owner's information","https://manuals.subaru.com/","Official Subaru model-year/VIN manual lookup."),
  nissan:src("Nissan manuals and guides","https://www.nissanusa.com/owners/ownership/manuals-guides.html","Official Nissan model-year manual lookup."),
  hyundai:src("Hyundai owner's manuals","https://ownersmanual.hyundai.com/","Official Hyundai market and model-year manual lookup."),
  kia:src("Kia owner's manuals","https://owners.kia.com/content/owners/en/manuals.html","Official Kia model-year manual lookup."),
  mitsubishi:src("Mitsubishi technical information","https://mitsubishitechinfo.com/","Official Mitsubishi model and engine service-information source."),
};
const ford2015F150=src("2015 Ford F-150 Owner's Manual — capacities and specifications","https://www.fordservicecontent.com/Ford_Content/Catalog/owner_information/2015-F-150-Owners-Manual-version-1_om_EN-US_09_2014.pdf","Primary Ford manual listing 6.0 qt (5.7 L) with filter and SAE 5W-30 meeting WSS-M2C946-A for the 3.5L EcoBoost.");
const ford2016F150=src("2016 Ford F-150 Owner's Manual — 2.7L EcoBoost capacities","https://www.fordservicecontent.com/Ford_Content/Catalog/owner_information/2016-F150-Owner-Manual-version-3_om_EN-US_02_2017.pdf","Primary Ford manual listing 6.0 qt (5.7 L) with filter for the 2.7L EcoBoost and its model-year oil specification.");
const ford2017F150=src("2017 Ford F-150 Owner's Manual — 5.0L capacities","https://www.fordservicecontent.com/Ford_Content/Catalog/owner_information/2017-Ford-F-150-Owners-Manual-version-2_om_EN-US-EN-CA_12_2016.pdf","Primary Ford manual listing 7.7 qt (7.3 L) with filter for the 5.0L V8 and the applicable 5W-20 material specification.");
const chevy2018Silverado=src("2018 Chevrolet Silverado Owner's Manual — capacities","https://experience.gm.com/ownercenter/content/dam/gmownercenter/gmna/dynamic/manuals/2018/Chevrolet/Silverado/2018-chevrolet-silverado-owners-manual.pdf","Primary Chevrolet manual listing 8.0 qt (7.6 L) with filter for the 1500-series 5.3L V8.");
const chevy2019Silverado=src("2019 Chevrolet Silverado 1500 Owner's Manual — capacities","https://www.chevrolet.com/ownercenter/content/dam/gmownercenter/gmna/dynamic/manuals/2019/Chevrolet/silverado-1500/2019-chevrolet-silverado-1500-owners-manual.pdf","Primary Chevrolet manual listing 8.0 qt (7.6 L) with filter for both 5.3L and 6.2L V8 1500-series engines and distinguishing L82, L84 and L87 applications.");
const gmc2019Sierra=src("2019 GMC Sierra 1500 Owner's Manual — capacities","https://www.gmc.com/ownercenter/content/dam/gmownercenter/gmna/dynamic/manuals/2019/GMC/sierra-1500/2019-gmc-sierra-1500-owners-manual.pdf","Primary GMC manual for the new-body 2019 Sierra 1500, including the 8.0-qt 5.3L V8 oil-and-filter capacity and engine-code distinctions.");
const ram2020_1500=src("2020 Ram 1500 Owner's Manual — fluid capacities","https://vehicleinfo.mopar.com/assets/publications/en-us/Ram/2020/1500_DT/5633292_20_DT_OM_EN_USC_DIGITAL_E5.pdf","Primary Ram DT manual listing 7.0 qt (6.6 L) with filter for 5.7L engines and API-certified SAE 5W-20 meeting FCA MS-6395.");
const toyota2021Tacoma=src("2021 Toyota Tacoma Owner's Manual — maintenance data","https://assets.sia.toyota.com/publications/en/om-s/OM04029U/pdf/OM04029U.pdf","Primary Toyota manual listing 6.2 qt (5.9 L) with filter for the 3.5L 2GR-FKS and the model-year oil-selection instructions.");
const toyota2018Camry=src("2018 Toyota Camry Owner's Manual — maintenance data","https://assets.sia.toyota.com/publications/en/om-s/OM06122U/pdf/OM06122U.pdf","Primary Toyota manual listing 4.8 qt (4.5 L) with filter for the gasoline A25A-FKS and distinguishing the Camry Hybrid manual.");
const toyota2019Rav4=src("2019 Toyota RAV4 Owner's Manual — maintenance data","https://assets.sia.toyota.com/publications/en/om-s/OM0R009U/pdf/OM0R009U.pdf","Primary Toyota manual listing 4.8 qt (4.5 L) with filter for the gasoline A25A-FKS and its SAE 0W-16 oil-selection guidance.");
const honda2020Civic=src("2020 Honda Civic Sedan Owner's Manual — specifications","https://techinfo.honda.com/rjanisis/pubs/OM/AH/ATBA2020OM/enu/ATBA2020OM.pdf","Primary Honda manual listing 3.7 qt (3.5 L) including filter for the 1.5L turbo and recommending 0W-20 engine oil.");
const honda2017Crv=src("2017 Honda CR-V Owner's Manual — specifications","https://techinfo.honda.com/rjanisis/pubs/OM/AH/ATLA1717OM/enu/ATLA1717OM.pdf","Primary Honda manual separating the 1.5L turbo and 2.4L engine capacities; the 1.5L oil-and-filter change is 3.7 qt (3.5 L).");
const jeep2018Jl=src("2018 All-New Jeep Wrangler JL Owner's Manual — fluid capacities","https://vehicleinfo.mopar.com/assets/publications/en-us/Jeep/2018/Wrangler_JL/9510.pdf","Primary Mopar JL manual listing 5.0 qt (4.73 L) with filter for the 3.6L and SAE 0W-20 meeting FCA MS-6395.");
const subaru2019Forester=src("2019 Subaru Forester Quick Guide — engine oil","https://techinfo.subaru.com/stis/doc/ownerManual/MSA5B1902A_STIS.pdf","Primary Subaru of America guide listing 4.4 US qt (4.2 L) for the 2019 Forester oil-and-filter change.");
const subaru2020Outback=src("2020 Subaru Outback Getting Started Guide — engine oil","https://techinfo.subaru.com/stis/doc/ownerManual/3906362_2020_Outback_GSG_1st-opt.pdf","Primary Subaru of America guide listing 4.4 US qt for the 2.5L during an oil-and-filter change and separating the 4.8-qt 2.4L turbo.");
const nissan2017Altima=src("2017 Nissan Altima Owner's Manual — capacities","https://www.nissanusa.com/content/dam/Nissan/us/manuals-and-guides/altima/2017/2017-nissan-altima-owner-manual.pdf","Primary Nissan manual listing 4-7/8 qt (4.6 L) with filter for the QR25DE and recommending Nissan 0W-20 SN oil or equivalent.");
const nissan2018Rogue=src("2018 Nissan Rogue Owner's Manual — capacities","https://www.nissanusa.com/content/dam/Nissan/us/manuals-and-guides/rogue/2018/2018-Nissan-Rogue-owner-manual.pdf","Primary Nissan manual listing 4-7/8 qt (4.6 L) with filter and 4-1/2 qt (4.3 L) without filter for the QR25DE.");
const ford2020Explorer=src("2020 Ford Explorer Owner's Manual — 2.3L capacities","https://www.fordservicecontent.com/Ford_Content/Catalog/owner_information/2020-Ford-Explorer-GasHEV-Owners-Manual-version-2_om_EN-US_06_2019.pdf","Primary Ford manual listing 4.9 L (about 5.2 US qt) including filter for the 2.3L EcoBoost and SAE 5W-30 meeting WSS-M2C946-B1.");
const hyundai2018Elantra=src("2018 Hyundai Elantra Owner's Manual — recommended lubricants","https://www.hyundaicanada.com/-/media/hyundai/feature/ownerssection/manuals/english/2018/elantra/ad-can-e-8.pdf","Manufacturer-hosted Elantra specifications listing 4.0 L (4.23 US qt) for a Nu 2.0 MPI drain and refill and separating the turbo engine.");
const kia2019Optima=src("2019 Kia Optima Owner's Manual — recommended lubricants","https://owners.kia.com/content/owners/en/manuals.html","Kia's official model-year manual lookup; the 2019 Optima table lists 4.8 L (5.07 US qt) for the 2.4 GDI drain and refill and separate figures for turbo engines.");
const ford60Tech=src("Ford 6.0L Power Stroke technical training manual — specifications","https://www.manualslib.com/manual/935032/Ford-6-0l-Power-Stroke.html","Ford technical-training manual transcription listing firing order 1-2-7-3-4-5-6-8 and the International-style right/left cylinder-bank layout.");
const ford64Tech=src("Ford 6.4L Power Stroke technical training manual — specifications","https://manualplace.com/lib/ford-6-4l-power-stroke-diesel-2008-service-manual-sample.pdf","Ford technical manual sample listing firing order 1-2-7-3-4-5-6-8 and cylinders 1-3-5-7 on the right bank and 2-4-6-8 on the left bank, front to rear.");
const cumminsFiring=src("Cummins/Jacobs inline-six adjustment sequence","https://www.cummins.com/sites/default/files/jvs/service_literature/42562_PN_28542_Rev_F_2018.pdf","Manufacturer-hosted instructions explicitly direct adjustment through the 1-5-3-6-2-4 engine firing-order sequence.");
const cummins59=src("Cummins QSB5.9 engine configuration","https://www.cummins.com/engines/products/recon-qsb59","Cummins identifies the 5.9L platform as an inline six-cylinder, four-stroke diesel; exact service information remains engine-serial-number specific.");
const gm62Training=src("GM 6.2L Diesel service training manual — engine design","https://www.marinedieselbasics.com/wp-content/uploads/edd/GM-6.2L-Service-Training.pdf","GM training-manual scan listing firing order 1-8-7-2-6-5-4-3, No. 1 at the forward left bank, odd cylinders left and even cylinders right.");
const gm65Military=src("GM/DDA 6.2L and 6.5L military service manual — tabulated data","https://www.dieselbombers.com/attachments/chevy-gmc-6-2l-6-5l/30301d1434862544-6-2-6-5-military-repair-manual-65l-army-repair-manual.pdf","Detroit Diesel Allison service data listing the 90-degree V8 layout and clockwise 1-8-7-2-6-5-4-3 firing order; vehicle-specific pump controls still require the applicable manual.");
const ford73IdiWorkshop=src("1994 Ford 7.3L IDI workshop manual — engine description","https://www.scribd.com/document/466915832/1994-MANUAL-DE-TALLER-BRONCO-ECONOLINE-F-SERIES-pdf","Ford workshop-manual transcription identifying right-bank cylinders 1-3-5-7 and firing order 1-2-7-3-4-5-6-8 for naturally aspirated and factory-turbo IDI engines.");
const ford69IdiWorkshop=src("1985 Ford 6.9L V8 diesel engine service manual — description","https://www.scribd.com/doc/37353496/1985-Ford-6-9L-Diesel-Engine","Original Ford service-manual scan stating the 6.9L IDI firing order is 1-2-7-3-4-5-6-8 and numbering the right/passenger bank 1-3-5-7 from the front.");
const ford73PsdFactory=src("7.3L Power Stroke factory engine specifications","https://73psd.com/factory-specs/engine/","Factory-workshop-manual reference showing order 1-2-7-3-4-5-6-8 and odd cylinders on the passenger bank, even cylinders on the driver bank.");
const ford73PsdSupplement=src("Ford 7.3L DIT Diesel Owner's Guide Supplement","https://www.fordservicecontent.com/Ford_Content/catalog/owner_guides/9973l731e.pdf","Primary Ford supplement identifying the Power Stroke 7.3L direct-injection turbo diesel and its separate engine-care procedures.");
const mitsubishi4g63Head=src("Mitsubishi 4G63 turbo engine overhaul manual — cylinder head","https://www.thomas-peterson.de/daten/Mitsubishi/Handbuecher/MSSP-206B-2003/GR00003800-11A.pdf","Factory service-manual section specifying 78 ± 2 N·m, full loosening, 20 ± 2 N·m, then 90° plus 90° for the covered 4G63 turbo fasteners, with bolt-length inspection and oiled threads/washers.");
const chevy350HoDeluxe=src("Chevrolet Performance 350 HO Deluxe engine specifications","https://www.chevrolet.com/content/dam/chevrolet/na/us/english/index/performance/resources/installation-guides/crate-engines/02-pdf/350-ho-deluxe-engine-12487544.pdf","Primary Chevrolet Performance guide specifying 35 lb-ft for the starter, 97 in-lb for the front cover and oil-pan side rails, 15 lb-ft for the oil-pan corners and drain plug, and 63 lb-ft for the balancer bolt on this package.");
const chevy350HoTurnKey=src("Chevrolet Performance 350 HO Turn Key installation guide","https://www.chevrolet.com/content/dam/chevrolet/na/us/english/index/performance/resources/installation-guides/crate-engines/02-pdf/350-ho-turn-key-engine-kit-19418224.pdf","Primary Chevrolet Performance guide specifying 30 lb-ft (40 N·m) for the supplied starter-motor bolts on the covered Turn Key package.");
const chevy350_265=src("Chevrolet Performance 350/265 HP long-block specifications","https://www.chevrolet.com/content/dam/chevrolet/na/us/english/index/performance/resources/installation-guides/crate-engines/02-pdf/350-265-hp-long-block-crate-engine-19420527.pdf","Primary Chevrolet Performance guide specifying 30 lb-ft (40 N·m) for water-pump bolts and 35 lb-ft (48 N·m) for starter-motor bolts on the covered engine package.");

type FiringJob={slug:string;keyword:string;make:string;model:string;title:string;order:string;numbering:string;scope:string;detail:string;source:Source;sources?:Source[]};
const firingJobs:FiringJob[]=[
  {slug:"chevrolet/6-2-diesel/firing-order",keyword:"chevy 6.2 diesel firing order",make:"Chevrolet",model:"6.2L Detroit Diesel V8",title:"Chevy 6.2 Diesel Firing Order and Injection-Line Diagram",order:"1-8-7-2-6-5-4-3",numbering:"Driver/left bank is 1-3-5-7 and passenger/right bank is 2-4-6-8, front to rear, with cylinder 1 at the forward left position.",scope:"Covers GM 6.2L IDI diesel V8 engines used in light- and heavy-duty truck applications; it does not cover the modern 6.2L gasoline V8 or later Duramax diesels.",detail:"The mechanical order is only the first layer of an injection-line check. Keep the rigid lines in their original clamps, identify every DB2 pump outlet from the exact pump/application diagram, and do not bend lines into a visually convenient route.",source:gm62Training,sources:[gm62Training,S.gm]},
  {slug:"chevrolet/6-5-diesel/firing-order",keyword:"chevy 6.5 diesel firing order",make:"Chevrolet",model:"6.5L Detroit Diesel V8",title:"Chevy 6.5 Diesel Firing Order and Cylinder Numbering",order:"1-8-7-2-6-5-4-3",numbering:"Driver/left bank is 1-3-5-7 and passenger/right bank is 2-4-6-8, front to rear.",scope:"Covers GM 6.5L IDI diesel V8 mechanical-pump and electronic-pump applications after confirming the installed engine, pump and vehicle wiring.",detail:"DB2 mechanical and DS4 electronic pump systems share the engine's mechanical sequence but not its controls, timing method, optical-sensor diagnosis or harness layout. The military manual corroborates the base order; civilian model-year service data controls the exact diagnostic procedure.",source:gm65Military,sources:[gm65Military,S.gm]},
  {slug:"ford/6-9-idi/firing-order",keyword:"ford 6.9 idi firing order",make:"Ford",model:"1983–1987 6.9L IDI Diesel V8",title:"Ford 6.9 IDI Firing Order and Injection-Line Diagram",order:"1-2-7-3-4-5-6-8",numbering:"The passenger/right bank is 1-3-5-7 and the driver/left bank is 2-4-6-8, with both banks numbered from the front of the engine toward the transmission.",scope:"Covers the Ford/International 6.9L indirect-injection V8 used in 1983–1987-era F-Series and E-Series applications. It does not cover the later 7.3L IDI, the 7.3L Power Stroke or gasoline Ford V8 numbering diagrams.",detail:"The firing order identifies combustion sequence, not the physical path of the formed DB2 injection lines. Label every line, match each pump outlet to the exact service diagram and keep all vibration clamps in place; forcing a line into the nearest cylinder can crack it or create a dangerous high-pressure fuel leak.",source:ford69IdiWorkshop,sources:[ford69IdiWorkshop,S.ford]},
  {slug:"ford/7-3-idi/firing-order",keyword:"ford 7.3 idi firing order",make:"Ford",model:"7.3L IDI Diesel V8",title:"Ford 7.3 IDI Firing Order and Cylinder Diagram",order:"1-2-7-3-4-5-6-8",numbering:"Passenger/right bank is 1-3-5-7 and driver/left bank is 2-4-6-8, front to rear.",scope:"Covers naturally aspirated and factory-turbo 7.3L indirect-injection engines used in Ford trucks and vans; it does not cover the later direct-injection 7.3L Power Stroke.",detail:"The IDI and Power Stroke share nominal displacement and the base firing sequence, but not injectors, pump, high-pressure-oil system, wiring or diagnostic method. A DB2 pump and visible hard injector lines identify the IDI architecture; preserve their clamps and match the pump-outlet diagram before disturbing them.",source:ford73IdiWorkshop,sources:[ford73IdiWorkshop,S.ford]},
  {slug:"ford/7-3-power-stroke/firing-order",keyword:"ford 7.3 powerstroke firing order",make:"Ford",model:"7.3L Power Stroke V8",title:"Ford 7.3 Power Stroke Firing Order and Cylinder Numbering",order:"1-2-7-3-4-5-6-8",numbering:"Passenger/right bank is 1-3-5-7 and driver/left bank is 2-4-6-8, front to rear.",scope:"Covers Ford/Navistar 7.3L Power Stroke direct-injection HEUI engines from the 1994.5–2003 light-truck era after confirming the installed calibration and harness generation.",detail:"Cylinder identity, injector-driver electrical order, contribution-test display and firing-event position are related but not interchangeable references. The under-valve-cover harness and external connector arrangement changed during production, so model-year wiring must accompany the physical cylinder diagram.",source:ford73PsdFactory,sources:[ford73PsdFactory,ford73PsdSupplement]},
  {slug:"ford/6-0-power-stroke/firing-order",keyword:"ford 6.0 powerstroke firing order",make:"Ford",model:"6.0L Power Stroke V8",title:"Ford 6.0 Power Stroke Firing Order and Cylinder Diagram",order:"1-2-7-3-4-5-6-8",numbering:"Passenger/right bank is 1-3-5-7 and driver/left bank is 2-4-6-8, front to rear.",scope:"Covers the 6.0L Power Stroke/Navistar VT365 used in Ford applications, including the F-Series, Excursion and E-Series years that received this engine; it does not cover the older 7.3L or later 6.4L service systems.",detail:"Use the physical cylinder number when interpreting power-balance, injector-circuit, contribution and glow-plug faults. The 6.0L's FICM and HEUI high-pressure-oil system make connector identity and hydraulic diagnosis separate from the mechanical firing sequence.",source:ford60Tech,sources:[ford60Tech,S.ford]},
  {slug:"ford/6-4-power-stroke/firing-order",keyword:"ford 6.4 powerstroke firing order",make:"Ford",model:"6.4L Power Stroke V8",title:"Ford 6.4 Power Stroke Firing Order and Cylinder Numbering",order:"1-2-7-3-4-5-6-8",numbering:"Passenger/right bank is 1-3-5-7 and driver/left bank is 2-4-6-8, front to rear.",scope:"Covers the Ford/Navistar 6.4L Power Stroke used in 2008–2010 Super Duty applications with the production camshaft and cylinder numbering.",detail:"Although the sequence matches the 6.0L, the 6.4L uses high-pressure common-rail injection and piezoelectric injectors rather than HEUI. Depressurization, injector coding, fuel-tube replacement and contamination procedures therefore require 6.4L-specific service information.",source:ford64Tech,sources:[ford64Tech,S.ford]},
  {slug:"ram/5-9-cummins-12v/firing-order",keyword:"dodge 5.9 cummins 12v firing order",make:"Ram",model:"5.9L Cummins 12-Valve I6",title:"Dodge 5.9 Cummins 12V Firing Order and Cylinder Diagram",order:"1-5-3-6-2-4",numbering:"Cylinders 1 through 6 run from the front gear/radiator end toward the flywheel and transmission.",scope:"Covers the mechanically injected 5.9L Cummins 6BT 12-valve used in Dodge trucks; industrial and repower installations must be oriented from the engine's gear housing rather than the vehicle body.",detail:"The engine is a single-bank inline six, but injection-pump outlet routing is not established by drawing the shortest line to each cylinder. Match the exact Bosch VE or P7100 pump diagram, keep every formed line in its original support clamps, and identify the engine and pump before loosening a line.",source:cumminsFiring,sources:[cumminsFiring,cummins59,S.cummins]},
  {slug:"ram/5-9-cummins-24v/firing-order",keyword:"dodge 5.9 cummins 24v firing order",make:"Ram",model:"5.9L Cummins 24-Valve I6",title:"Dodge 5.9 Cummins 24V Firing Order and Cylinder Diagram",order:"1-5-3-6-2-4",numbering:"Cylinders 1-2-3-4-5-6 run from the front gear housing toward the flywheel and transmission.",scope:"Covers Dodge/Ram 5.9L Cummins ISB 24-valve truck engines, while separating VP44-era and high-pressure-common-rail versions for fuel-system work.",detail:"The mechanical combustion order stays 1-5-3-6-2-4 across these 24-valve versions, but VP44 and common-rail systems do not share pump, line, injector or electrical procedures. Retrieve serial-number-specific Cummins information before opening the fuel system.",source:cumminsFiring,sources:[cumminsFiring,cummins59,S.cummins]},
];
function firingPage(j:FiringJob):SpecRecord{return firingGuide({slug:j.slug,keyword:j.keyword,make:j.make,model:j.model,category:"Firing Order",title:j.title,
  metaDescription:`${j.title}: ${j.order}, diesel bank numbering, injection-system distinctions and routing cautions.`,answer:`The ${j.model} firing order is ${j.order}. ${j.numbering}`,scope:j.scope,detail:j.detail,
  values:[{label:"Firing order",value:j.order,note:"Verify exact engine"},{label:"Cylinder numbering",value:j.numbering,note:"Orient from engine front"}],sources:j.sources??[j.source],identity:j.model,distinctions:[j.scope,j.detail],featureImage:engineImage,featureOverlay:true});}

type HeadJob={slug:string;keyword:string;make:string;model:string;title:string;answer:string;scope:string;detail:string;values:SpecValue[];source:Source};
const headJobs:HeadJob[]=[
  {slug:"mitsubishi/4g63/head-bolt-torque",keyword:"mitsubishi 4g63 head bolt torque specs",make:"Mitsubishi",model:"4G63 Turbo Inline-Four",title:"Mitsubishi 4G63 Head Bolt Torque Specs and Sequence",answer:"For the 4G63 turbo application covered by the linked Mitsubishi overhaul manual, tighten the oiled factory bolts to 78 ± 2 N·m, loosen them completely, tighten to 20 ± 2 N·m, then turn every bolt 90° and another 90° in sequence.",scope:"This numerical procedure covers the factory-bolt 4G63 turbo revision documented in the linked manual. Earlier 6-bolt engines, naturally aspirated variants, Evolution revisions and aftermarket studs must be matched to their own manual or fastener chart.",detail:"Inspect bolt length before reuse, oil the threads and washer faces as specified, and use paint marks for both angle passes. If an angle is exceeded, the manual directs loosening the bolt completely and restarting the procedure rather than backing it off to the mark.",values:[{label:"Stage 1",value:"78 ± 2 N·m",note:"57.5 ± 1.5 lb-ft; exact sequence"},{label:"Stage 2",value:"Loosen completely",note:"All bolts"},{label:"Stage 3",value:"20 ± 2 N·m",note:"14.8 ± 1.5 lb-ft"},{label:"Stages 4 and 5",value:"90° + 90°",note:"Paint-mark each bolt"},{label:"Fastener condition",value:"Inspect length; oil threads/washer",note:"Use the manual's limit"}],source:mitsubishi4g63Head},
  {slug:"ford/7-3-power-stroke/head-bolt-torque",keyword:"ford 7.3 powerstroke head bolt torque specs",make:"Ford",model:"7.3L Power Stroke V8",title:"Ford 7.3 Power Stroke Head Bolt Torque Specs and Sequence",answer:"The 7.3L Power Stroke uses a staged cylinder-head procedure with position-specific factory fasteners; aftermarket studs require their own lubricant and torque chart.",scope:"Covers 7.3L Power Stroke HEUI engines, not the earlier 7.3L IDI.",detail:"Identify bolt length and position, clear blind holes and follow the exact model-year sequence rather than a single remembered final value.",values:[{label:"Factory procedure",value:"Staged and position-specific",note:"Use exact Ford/Navistar data"},{label:"Aftermarket studs",value:"Kit-specific torque",note:"Specified lube required"}],source:S.ford},
  {slug:"ford/6-0-power-stroke/head-bolt-torque",keyword:"ford 6.0 powerstroke head bolt torque specs",make:"Ford",model:"6.0L Power Stroke V8",title:"Ford 6.0 Power Stroke Head Bolt Torque Specs and Sequence",answer:"The 6.0L Power Stroke uses torque-to-yield head bolts and a multi-stage torque-angle sequence; stud conversions use a different procedure.",scope:"Covers 6.0L Power Stroke engine assembly planning; model year, gasket, head machining and fastener kit must be matched.",detail:"Use new factory bolts when required, measure surface condition and do not combine factory angle stages with an aftermarket stud torque.",values:[{label:"Factory fasteners",value:"Torque plus angle",note:"New TTY bolts commonly required"},{label:"Stud conversion",value:"Fastener-maker chart",note:"Do not use factory angle stages"}],source:S.ford},
  {slug:"ram/5-9-cummins/head-bolt-torque",keyword:"dodge 5.9 cummins head bolt torque specs",make:"Ram",model:"5.9L Cummins I6",title:"Dodge 5.9 Cummins Head Bolt Torque Specs: 12V vs. 24V",answer:"Cummins 5.9L head tightening differs by 12-valve, 24-valve, model year, bolt position and whether factory bolts or studs are used.",scope:"Covers 6BT/ISB 5.9L identification; retrieve the procedure by engine serial number whenever possible.",detail:"A long inline-six head requires verified flatness, correct surface finish and even staged clamping. Do not blend 12V and 24V charts.",values:[{label:"Engine version",value:"12V or 24V required",note:"Also identify serial number"},{label:"Factory procedure",value:"Staged, position-specific",note:"Use Cummins QuickServe"},{label:"Aftermarket studs",value:"Kit-specific",note:"Lube changes clamp load"}],source:S.cummins},
  {slug:"gm/6-6-duramax/head-bolt-torque",keyword:"gm 6.6 duramax head bolt torque specs",make:"GMC",model:"6.6L Duramax V8",title:"GM 6.6 Duramax Head Bolt Torque Specs by Engine RPO",answer:"Duramax head-bolt stages vary among LB7, LLY, LBZ, LMM, LML, L5P and other revisions; there is no safe universal 6.6L chart.",scope:"Covers GM 6.6L Duramax application identification; exact engine RPO, bolt family and service revision are mandatory.",detail:"Main and small bolts may use separate torque-angle stages. Aftermarket studs never inherit the factory TTY procedure automatically.",values:[{label:"Required identity",value:"Duramax engine RPO",note:"LB7 through current revisions"},{label:"Procedure",value:"Staged torque plus angle",note:"Bolt-family specific"}],source:S.gm},
];
function headPage(j:HeadJob):SpecRecord{return {slug:j.slug,keyword:j.keyword,make:j.make,model:j.model,category:"Torque Specs",title:j.title,
  metaDescription:`${j.title} with application boundaries, fastener distinctions, staged sequence guidance and official service lookup.`,answer:j.answer,scope:j.scope,detail:j.detail,values:j.values,sources:[j.source],reviewed,featureImage:engineImage,featureOverlay:true,
  diagram:{type:"head",title:`Interactive ${j.model} head sequence aid`,caption:"Orientation aid only. Use the exact manufacturer bolt map and stages for assembly.",points:["1","5","9","7","3","4","8","10","6","2"]},intro:[j.answer,j.scope],
  steps:["Identify the engine serial/RPO, model year, cylinder head, gasket and fastener kit.","Verify flatness, surface finish, threads and empty bolt holes.","Complete each torque, loosen and angle stage in the exact numbered order."],sections:[{heading:`Application boundaries for ${j.model}`,paragraphs:[j.scope,j.detail]}],
  faqs:dieselServiceFaqs[j.slug]??[{q:`What are the ${j.keyword}?`,a:j.answer},{q:"Can factory head bolts be reused?",a:"Only when the exact service procedure permits it and the bolts pass every inspection limit."},{q:"Can a stud kit use the factory procedure?",a:"No. Use the fastener maker's torque, lubricant and sequence for the exact kit."}]};}

type TorqueJob={slug:string;keyword:string;make:string;model:string;title:string;answer:string;scope:string;detail:string;values:SpecValue[];source:Source;sources?:Source[];diagram?:"intake"|"timing"|"main"};
const torqueJobs:TorqueJob[]=[
  {slug:"chevrolet/350/starter-bolt-torque",keyword:"chevy 350 starter bolt torque spec",make:"Chevrolet",model:"350 Small-Block V8",title:"Chevy 350 Starter Bolt Torque Specs and Fit Checks",answer:"Chevrolet Performance does not publish one universal Chevy 350 starter-bolt number: its 350 HO Turn Key guide specifies 30 lb-ft (40 N·m), while the 350 HO Deluxe and 350/265 HP long-block guides specify 35 lb-ft (48 N·m). Use the value for the installed starter and engine package.",scope:"The 30- and 35-lb-ft figures are package-specific Chevrolet Performance specifications, not permission to average them. Production engines, replacement mini-starters, different bolt diameters and aftermarket nose housings can carry different instructions.",detail:"Use correct shouldered or knurled starter bolts of the prescribed length, install any factory brace, and verify pinion-to-ring-gear engagement before adding shims. A starter that shifts or sits crooked can damage the nose, bolt holes and ring gear even when a torque wrench reaches the nominal number.",values:[{label:"350 HO Turn Key supplied starter",value:"30 lb-ft",note:"40 N·m; package guide"},{label:"350 HO Deluxe / 350-265 long block",value:"35 lb-ft",note:"48 N·m; package guide"},{label:"Aftermarket starter",value:"Manufacturer instructions",note:"Match bolt and nose housing"}],source:chevy350HoTurnKey,sources:[chevy350HoTurnKey,chevy350HoDeluxe,chevy350_265],diagram:"main"},
  {slug:"chevrolet/350/exhaust-manifold-torque",keyword:"chevy 350 exhaust manifold torque spec",make:"Chevrolet",model:"350 Small-Block V8",title:"Chevy 350 Exhaust Manifold Bolt Torque Specs",answer:"Traditional Chevy 350 cast-iron exhaust manifold bolts are commonly tightened around 25 lb-ft, but head material, gasket, fastener and header instructions can change the value.",scope:"Covers common Gen I iron-head cast manifolds; tube headers and aluminum heads require component-specific instructions.",detail:"Start all bolts with the manifold aligned, tighten from the center outward and retorque only if the gasket/header maker requires it.",values:[{label:"Common cast-manifold reference",value:"About 25 lb-ft",note:"Verify exact application"},{label:"Headers/aluminum heads",value:"Component-specific",note:"Usually a different procedure"}],source:S.gm},
  {slug:"chevrolet/350/oil-pan-bolt-torque",keyword:"chevy 350 oil pan bolt torque spec",make:"Chevrolet",model:"350 Small-Block V8",title:"Chevy 350 Oil Pan Bolt Torque Specs by Location",answer:"For the Chevrolet Performance 350 HO Deluxe, tighten the oil-pan side-rail bolts to 97 in-lb (11 N·m) and the corner bolts to 15 lb-ft (20 N·m). The drain plug is also listed at 15 lb-ft (20 N·m).",scope:"These exact values apply to the oil pan and hardware arrangement supplied or specified for the cited 350 HO Deluxe package. Earlier two-piece seals, aftermarket cast pans, one-piece gasket kits and mixed-size production hardware may use different location groups.",detail:"Separate the small side-rail bolts from the larger corner fasteners before starting. Flatten pulled bolt holes on a stamped pan, place sealant only where the gasket instructions call for it, start every bolt by hand, and tighten in gradual alternating passes. More torque will bow the flange and worsen a leak.",values:[{label:"Side-rail bolts",value:"97 in-lb",note:"11 N·m; 350 HO Deluxe"},{label:"Corner bolts",value:"15 lb-ft",note:"20 N·m; 350 HO Deluxe"},{label:"Oil-pan drain plug",value:"15 lb-ft",note:"20 N·m; separate joint"}],source:chevy350HoDeluxe,diagram:"main"},
  {slug:"chevrolet/350/water-pump-bolt-torque",keyword:"chevy 350 water pump bolt torque spec",make:"Chevrolet",model:"350 Small-Block V8",title:"Chevy 350 Water Pump Bolt Torque Specs",answer:"Chevrolet Performance specifies 30 lb-ft (40 N·m) for the water-pump bolts in its 350/265 HP long-block guide.",scope:"The 30-lb-ft value is a manufacturer specification for the covered Gen I small-block crate-engine arrangement. Accessory brackets captured under a bolt, aftermarket pumps, aluminum components and nonstandard fasteners still require their own instructions.",detail:"Keep each bolt in its original position because lengths can differ. Clean the block and pump faces, confirm whether the exact bolt hole or pump instructions require thread sealant, start all bolts by hand and tighten evenly so the pump does not cock against the gasket. Recheck for leaks after the first complete heat cycle without automatically retorquing.",values:[{label:"Water-pump bolts",value:"30 lb-ft",note:"40 N·m; Chevrolet Performance 350/265"},{label:"Aftermarket pump or bracket stack",value:"Component instructions",note:"Verify bolt length and sealant"}],source:chevy350_265,diagram:"timing"},
  {slug:"chevrolet/350/timing-cover-bolt-torque",keyword:"chevy 350 timing cover bolt torque spec",make:"Chevrolet",model:"350 Small-Block V8",title:"Chevy 350 Timing Cover Bolt Torque Specs",answer:"Chevrolet Performance specifies 97 in-lb (11 N·m) for the front-cover bolts on the 350 HO Deluxe.",scope:"This is an exact package value for the cited Gen I 350 HO Deluxe front cover. Cast aftermarket covers, reinforcement plates, different washers and accessory brackets can change the fastener stack and required torque.",detail:"Fit the cover loosely before the oil-pan corner seals are compressed, center it to the crank seal as the installation procedure requires, and tighten the small bolts evenly. The joint seals through correct alignment and gasket compression; overtightening can dish a stamped flange, squeeze out the seal or create a new leak path.",values:[{label:"Front/timing-cover bolts",value:"97 in-lb",note:"11 N·m; 350 HO Deluxe"},{label:"Cast aftermarket cover",value:"Manufacturer instructions",note:"Material and hardware may differ"}],source:chevy350HoDeluxe,diagram:"timing"},
  {slug:"ford/302/exhaust-manifold-torque",keyword:"ford 302 exhaust manifold torque spec",make:"Ford",model:"302 Small-Block V8",title:"Ford 302 Exhaust Manifold Torque Specs",answer:"Many stock Ford 302 cast-manifold procedures fall roughly in the 18-25 lb-ft range, while headers and aluminum heads require their own instructions.",scope:"Covers Windsor-family 302 cast-iron head/manifold applications.",detail:"Use the correct locking hardware, center-out sequence and gasket guidance; model-year emissions hardware can change bolt locations.",values:[{label:"Common stock range",value:"About 18-25 lb-ft",note:"Verify year and hardware"},{label:"Tube headers",value:"Header-maker value",note:"Recheck if instructed"}],source:S.ford},
  {slug:"ford/302/oil-pan-bolt-torque",keyword:"ford 302 oil pan bolt torque spec",make:"Ford",model:"302 Small-Block V8",title:"Ford 302 Oil Pan Bolt Torque Specs",answer:"Ford 302 stamped oil pans use low, size-dependent torque; common references are about 7-9 lb-ft for 1/4-inch bolts and 11-13 lb-ft for larger bolts.",scope:"Covers common Windsor 302 stamped pans; one-piece gaskets and aftermarket cast pans can specify different values.",detail:"Repair dimpled rails, apply sealant only at specified joints and tighten in several even passes.",values:[{label:"Common small bolts",value:"7-9 lb-ft",note:"Verify diameter"},{label:"Common larger bolts",value:"11-13 lb-ft",note:"Position-specific"}],source:S.ford,diagram:"main"},
  {slug:"ford/302/flywheel-bolt-torque",keyword:"ford 302 flywheel torque spec",make:"Ford",model:"302 Small-Block V8",title:"Ford 302 Flywheel Bolt Torque Specs",answer:"A common production Ford 302 manual-flywheel bolt range is about 75-85 lb-ft, but crank, bolt kit, flywheel and thread treatment must match.",scope:"Covers common Windsor manual-transmission flywheels; flexplate and aftermarket hardware are separate applications.",detail:"Confirm balance weight and rear-main-seal generation, clean mating faces and tighten in a staged crisscross pattern.",values:[{label:"Common stock range",value:"75-85 lb-ft",note:"Verify bolt and flywheel"},{label:"Aftermarket bolts",value:"Fastener-maker chart",note:"Lubricant-specific"}],source:S.ford,diagram:"main"},
  {slug:"ford/302/harmonic-balancer-bolt-torque",keyword:"ford 302 harmonic balancer torque spec",make:"Ford",model:"302 Small-Block V8",title:"Ford 302 Harmonic Balancer Bolt Torque Specs",answer:"Many Ford 302 crankshaft damper retaining-bolt procedures use roughly 70-90 lb-ft; engine year, crank and aftermarket damper instructions determine the exact value.",scope:"Covers common threaded-snout Windsor 302 crankshafts.",detail:"Use a dedicated installer to seat the damper; never hammer it or use the retaining bolt to draw it fully onto the crank.",values:[{label:"Common stock range",value:"70-90 lb-ft",note:"Verify year and hardware"},{label:"Installation",value:"Damper installer required",note:"Protect crank threads"}],source:S.ford,diagram:"timing"},
  {slug:"chevrolet/5-3/exhaust-manifold-torque",keyword:"chevy 5.3 exhaust manifold torque spec",make:"Chevrolet",model:"5.3L V8",title:"Chevy 5.3 Exhaust Manifold Torque Specs by Generation",answer:"Many Gen III/IV 5.3L exhaust manifold procedures use staged tightening near 11 lb-ft then 18 lb-ft, but Gen V, replacement bolts and headers require exact data.",scope:"Covers common LS-based truck 5.3L cast manifolds; identify engine RPO and model year.",detail:"Inspect for broken rear bolts and warped manifolds. Do not overtorque a replacement bolt to compensate for a leaking flange.",values:[{label:"Common initial pass",value:"11 lb-ft",note:"15 N-m"},{label:"Common final pass",value:"18 lb-ft",note:"25 N-m; verify RPO"}],source:S.gm},
  {slug:"chevrolet/5-3/flywheel-flexplate-torque",keyword:"chevy 5.3 flywheel torque spec",make:"Chevrolet",model:"5.3L V8",title:"Chevy 5.3 Flywheel and Flexplate Bolt Torque Specs",answer:"Chevy 5.3L flywheel/flexplate procedures vary by engine generation, transmission and bolt design and may use torque-plus-angle rather than one final torque.",scope:"Covers LS/Vortec and EcoTec3 5.3L application identification.",detail:"Manual flywheel and automatic flexplate fasteners are not interchangeable procedures. Use new bolts or threadlocker exactly as specified.",values:[{label:"Transmission type",value:"Manual or automatic required",note:"Different joints"},{label:"Procedure",value:"Torque or torque-angle",note:"Engine-generation specific"}],source:S.gm,diagram:"main"},
  {slug:"chevrolet/5-3/harmonic-balancer-torque",keyword:"chevy 5.3 harmonic balancer torque spec",make:"Chevrolet",model:"5.3L V8",title:"Chevy 5.3 Harmonic Balancer Bolt Torque Specs",answer:"Many LS-based 5.3L engines use a new crank bolt with an initial torque and large angle turn; Gen V and aftermarket damper procedures must be matched separately.",scope:"Covers common LS/Vortec 5.3L damper installation concepts.",detail:"Use an installation bolt/tool to seat the damper where specified, then install the new final bolt. Never reuse a torque-to-yield bolt unless service data permits it.",values:[{label:"Common LS method",value:"Initial torque plus angle",note:"New bolt commonly required"},{label:"Gen V/aftermarket",value:"Exact component procedure",note:"Do not transfer LS chart"}],source:S.gm,diagram:"timing"},
  {slug:"chevrolet/5-3/oil-pan-bolt-torque",keyword:"chevy 5.3 oil pan bolt torque spec",make:"Chevrolet",model:"5.3L V8",title:"Chevy 5.3 Oil Pan Bolt Torque Specs by Bolt Group",answer:"The 5.3L oil pan uses multiple fastener groups with different low torque values; pan-to-block, pan-to-front-cover and bellhousing bolts must not share one setting.",scope:"Covers LS/Vortec and EcoTec3 pan-service planning; engine generation and pan design are mandatory.",detail:"Align the rear face and front-cover joints before tightening. Treat small perimeter bolts separately from structural fasteners.",values:[{label:"Perimeter bolts",value:"Low torque, group-specific",note:"Use exact RPO chart"},{label:"Front/rear structural bolts",value:"Separate value",note:"Do not copy perimeter torque"}],source:S.gm,diagram:"main"},
  {slug:"dodge/5-7-hemi/exhaust-manifold-torque",keyword:"dodge 5.7 hemi exhaust manifold torque spec",make:"Dodge",model:"5.7L HEMI V8",title:"Dodge 5.7 HEMI Exhaust Manifold Torque Specs",answer:"5.7L HEMI exhaust manifold tightening varies by car/truck generation, bolt revision and heat shield; use the exact Mopar staged sequence.",scope:"Covers HEMI exhaust manifold service planning across common vehicles.",detail:"Broken rear bolts and warped manifolds are common failure modes. Repair the joint rather than increasing torque on remaining bolts.",values:[{label:"Procedure",value:"Model-year staged sequence",note:"Use exact Mopar data"},{label:"Replacement hardware",value:"Revision-specific",note:"Bolts and shields can change"}],source:S.mopar},
  {slug:"dodge/5-7-hemi/flywheel-flexplate-torque",keyword:"dodge 5.7 hemi flywheel torque spec",make:"Dodge",model:"5.7L HEMI V8",title:"Dodge 5.7 HEMI Flywheel and Flexplate Torque Specs",answer:"HEMI flywheel and flexplate fasteners are transmission- and model-year-specific and may use torque-angle or threadlocker requirements.",scope:"Covers 5.7L HEMI crank-to-driveplate/flywheel identification.",detail:"Confirm manual versus automatic transmission, bolt length and plate orientation before applying a numerical chart.",values:[{label:"Application",value:"Transmission-specific",note:"Manual and automatic differ"},{label:"Fasteners",value:"Reuse rule required",note:"Check torque-angle/threadlocker"}],source:S.mopar,diagram:"main"},
  {slug:"dodge/5-7-hemi/harmonic-balancer-torque",keyword:"dodge 5.7 hemi harmonic balancer torque spec",make:"Dodge",model:"5.7L HEMI V8",title:"Dodge 5.7 HEMI Harmonic Balancer Bolt Torque Specs",answer:"The 5.7L HEMI crankshaft damper bolt uses a generation-specific high-clamp procedure; exact model-year service data and bolt-reuse rules control.",scope:"Covers factory 5.7L HEMI dampers; aftermarket supercharger hubs and performance dampers use separate instructions.",detail:"Seat the damper with the approved installer and never hammer it or rely on the final bolt as the installation tool.",values:[{label:"Factory method",value:"High torque, generation-specific",note:"Verify exact service data"},{label:"Aftermarket hub/damper",value:"Component instructions",note:"May change bolt and washer"}],source:S.mopar,diagram:"timing"},
];
function torquePage(j:TorqueJob):SpecRecord{return {slug:j.slug,keyword:j.keyword,make:j.make,model:j.model,category:"Torque Specs",title:j.title,
  metaDescription:`${j.title} with fastener-group distinctions, installation cautions, application limits and official source lookup.`,answer:j.answer,scope:j.scope,detail:j.detail,values:j.values,sources:j.sources??[j.source],reviewed,featureImage:engineImage,featureOverlay:true,
  diagram:{type:j.diagram??"intake",title:`Interactive ${j.model} fastener map`,caption:"Orientation aid only. Match every position and stage to the exact service diagram.",points:["1","5","3","7","8","4","6","2"]},intro:[j.answer,j.scope],steps:["Identify the exact engine, component, fastener size and hardware instructions.","Clean and inspect threads and mating faces; apply only the specified lubricant or sealant.","Tighten in gradual balanced passes and verify any angle, cure-time or recheck instruction."],sections:[{heading:`Application boundaries for ${j.model}`,paragraphs:[j.scope,j.detail]}],faqs:dieselServiceFaqs[j.slug]??[{q:`What is the ${j.keyword}?`,a:j.answer},{q:"Does aftermarket hardware use the stock torque?",a:"Not automatically. Use the component or fastener maker's instructions for its exact hardware and lubricant."},{q:"Can extra torque stop a leak?",a:"No. Diagnose flatness, cracks, gasket alignment, fastener condition and thread damage instead of overtightening."}]};}

type OilJob={slug:string;keyword:string;make:string;model:string;title:string;answer:string;scope:string;detail:string;capacity:string;liters:string;source:Source};
const oilJobs:OilJob[]=[
  {slug:"ford/f-150/2015/3-5-ecoboost/oil-capacity",keyword:"2015 ford f150 oil capacity 3.5 ecoboost",make:"Ford",model:"2015 F-150 3.5L EcoBoost",title:"2015 Ford F-150 3.5 EcoBoost Oil Capacity",answer:"Ford specifies 6.0 US qt (5.7 L) for a 2015 F-150 3.5L EcoBoost oil-and-filter change.",scope:"Applies specifically to the first-generation 3.5L EcoBoost in the 2015 F-150. Do not transfer the capacity from a later second-generation 3.5L EcoBoost or another Ford model.",detail:"The same manual calls for SAE 5W-30 meeting Ford WSS-M2C946-A. Add slightly less than the published capacity first, run the engine to fill the filter, shut it down, allow drain-back on level ground and finish by the dipstick without exceeding MAX.",capacity:"6.0 US qt",liters:"5.7 L; with filter",source:ford2015F150},
  {slug:"ford/f-150/2016/2-7-ecoboost/oil-capacity",keyword:"2016 ford f150 oil capacity 2.7 ecoboost",make:"Ford",model:"2016 F-150 2.7L EcoBoost",title:"2016 Ford F-150 2.7 EcoBoost Oil Capacity",answer:"Ford specifies 6.0 US qt (5.7 L) with the filter for the 2016 F-150 2.7L EcoBoost.",scope:"Applies to the 2016 F-150 equipped with the 2.7L EcoBoost. Similar displacement does not make a later-generation engine or another vehicle application interchangeable.",detail:"Use SAE 5W-30 oil carrying the Ford approval shown in the model-year manual. Reinstall the correct filter and drain plug, refill below the nominal total, run briefly while checking for leaks, wait for drain-back and use the dipstick as the final authority.",capacity:"6.0 US qt",liters:"5.7 L; with filter",source:ford2016F150},
  {slug:"ford/f-150/2017/5-0/oil-capacity",keyword:"2017 ford f150 oil capacity 5.0",make:"Ford",model:"2017 F-150 5.0L V8",title:"2017 Ford F-150 5.0 Oil Capacity",answer:"Ford specifies 7.7 US qt (7.3 L) with the oil filter for the 2017 F-150 5.0L V8.",scope:"Applies to the 2017 F-150 5.0L Coyote V8. The revised 2018 5.0L has a different published capacity, so model year must be part of the lookup.",detail:"Use SAE 5W-20 meeting the Ford specification in the 2017 manual. Do not round this page to an 8-qt bottle count or substitute the later 8.8-qt figure; refill progressively and verify the final level on the dipstick after the filter is filled and the oil has drained back.",capacity:"7.7 US qt",liters:"7.3 L; with filter",source:ford2017F150},
  {slug:"chevrolet/silverado-1500/2018/5-3/oil-capacity",keyword:"2018 chevy silverado 1500 5.3 oil capacity",make:"Chevrolet",model:"2018 Silverado 1500 5.3L",title:"2018 Chevy Silverado 1500 5.3 Oil Capacity",answer:"GM lists 8.0 US qt (7.6 L) with the oil filter for the 2018 Silverado 1500 5.3L V8.",scope:"Applies to the light-duty 2018 Silverado 1500 with the 5.3L gasoline V8. It does not cover Silverado HD engines, Duramax applications or a different displacement.",detail:"The manual calls for the specified dexos-approved oil and viscosity for the engine. Add less than the full eight quarts initially, run the engine while checking for leaks, allow drain-back on level ground and finish at the dipstick rather than assuming every drained engine accepts the nominal total immediately.",capacity:"8.0 US qt",liters:"7.6 L; with filter",source:chevy2018Silverado},
  {slug:"chevrolet/silverado-1500/2019/6-2/oil-capacity",keyword:"2019 chevy silverado 1500 6.2 oil capacity",make:"Chevrolet",model:"2019 Silverado 1500 6.2L",title:"2019 Chevy Silverado 1500 6.2 Oil Capacity",answer:"The new-body 2019 Silverado 1500 6.2L L87 takes 8.0 US qt (7.6 L) with the oil filter.",scope:"Applies to the 2019 light-duty Silverado 1500 equipped with the 6.2L L87 V8. The 2019 model year also includes carryover/LD trucks, so identify the VIN, body generation and engine before using surrounding service data.",detail:"GM groups the 5.3L and 6.2L 1500-series V8 oil capacity at 8.0 qt in the cited manual, but oil specification, filter and other service parts remain engine-code specific. Refill progressively and verify the final level after drain-back.",capacity:"8.0 US qt",liters:"7.6 L; with filter",source:chevy2019Silverado},
  {slug:"ram/1500/2020/5-7-hemi/oil-capacity",keyword:"2020 ram 1500 5.7 hemi oil capacity",make:"Ram",model:"2020 1500 5.7L HEMI",title:"2020 Ram 1500 5.7 HEMI Oil Capacity",answer:"The 2020 Ram 1500 DT with either 5.7L HEMI configuration takes 7.0 US qt (6.6 L) with a new oil filter.",scope:"Applies to the fifth-generation 2020 Ram 1500 DT 5.7L HEMI, including eTorque where equipped. The concurrently sold Ram 1500 Classic uses the DS-platform manual and should be identified separately.",detail:"Ram specifies API-certified SAE 5W-20 meeting FCA Material Standard MS-6395. Refill below the seven-quart reference first, start the engine and check for leaks, shut it down on level ground, allow the oil to drain back and use the dipstick for the final top-off. The manual also says the filter should be replaced at every oil change.",capacity:"7.0 US qt",liters:"6.6 L; with filter",source:ram2020_1500},
  {slug:"toyota/tacoma/2021/3-5/oil-capacity",keyword:"2021 toyota tacoma 3.5 oil capacity",make:"Toyota",model:"2021 Tacoma 3.5L V6",title:"2021 Toyota Tacoma 3.5 Oil Capacity",answer:"Toyota lists 6.2 US qt (5.9 L) with a new filter for the 2021 Tacoma 3.5L 2GR-FKS V6.",scope:"Applies to U.S.-market 2021 Tacoma models equipped with the 3.5L 2GR-FKS. It does not apply to the 2.7L four-cylinder or to the redesigned turbocharged Tacoma introduced later.",detail:"Treat 6.2 qt as a drain-and-refill reference, not a command to pour in the full amount at once. Install the correct filter and drain-plug gasket, add slightly less than the reference, run the engine, inspect for leaks, wait more than five minutes on level ground and finish at the dipstick. Use the oil grade and viscosity stated in the same model-year manual.",capacity:"6.2 US qt",liters:"5.9 L; with filter",source:toyota2021Tacoma},
  {slug:"toyota/camry/2018/2-5/oil-capacity",keyword:"2018 toyota camry 2.5 oil capacity",make:"Toyota",model:"2018 Camry 2.5L",title:"2018 Toyota Camry 2.5 Oil Capacity",answer:"Toyota lists 4.8 US qt (4.5 L) with a new filter for the gasoline 2018 Camry 2.5L A25A-FKS.",scope:"Applies to the conventional gasoline 2018 Camry 2.5L A25A-FKS. The Camry Hybrid uses the A25A-FXS and a separate owner-manual section, while the available 3.5L V6 has a different capacity.",detail:"Toyota describes the figure as a drain-and-refill reference. Add below 4.8 qt initially, run the engine long enough to fill the filter, inspect the drain plug and filter, switch off, wait more than five minutes on level ground and bring the dipstick level into range. The gasoline A25A-FKS page specifies SAE 0W-16; if 0W-20 is used only because 0W-16 is unavailable, Toyota directs replacement with 0W-16 at the next change.",capacity:"4.8 US qt",liters:"4.5 L; with filter",source:toyota2018Camry},
  {slug:"toyota/rav4/2019/2-5/oil-capacity",keyword:"2019 toyota rav4 2.5 oil capacity",make:"Toyota",model:"2019 RAV4 2.5L",title:"2019 Toyota RAV4 2.5 Oil Capacity",answer:"Toyota lists 4.8 US qt (4.5 L) with a new filter for the gasoline 2019 RAV4 2.5L A25A-FKS.",scope:"Applies to the conventional gasoline 2019 RAV4 with the A25A-FKS engine. The RAV4 Hybrid uses the A25A-FXS and its own manual, so engine and powertrain identity should be confirmed even when the nominal refill amount appears similar.",detail:"The published capacity is a reference for a drain and refill. Start below the full 4.8 qt, run the engine while checking for leakage, shut it off on level ground, wait more than five minutes and finish by the dipstick. Toyota specifies SAE 0W-16 for this application; temporary 0W-20 use carries a return-to-0W-16 instruction at the next oil change.",capacity:"4.8 US qt",liters:"4.5 L; with filter",source:toyota2019Rav4},
  {slug:"honda/civic/2020/1-5-turbo/oil-capacity",keyword:"2020 honda civic 1.5t oil capacity",make:"Honda",model:"2020 Civic 1.5L Turbo",title:"2020 Honda Civic 1.5T Oil Capacity",answer:"Honda lists 3.7 US qt (3.5 L) including a new filter for the 2020 Civic 1.5L turbo.",scope:"Applies to U.S.-market 2020 Civic 1.5L turbo models after confirming body style and engine. It does not apply to the naturally aspirated 2.0L or the 2.0L turbo Type R.",detail:"Honda recommends 0W-20 and distinguishes 3.4 qt for an oil-only drain from 3.7 qt when the filter is changed. Install a new drain-bolt washer, refill below the reference first, run the engine while checking for leakage, shut it off on level ground, wait about three minutes and finish at the dipstick rather than by bottle count.",capacity:"3.7 US qt",liters:"3.5 L; including filter",source:honda2020Civic},
  {slug:"honda/cr-v/2017/1-5-turbo/oil-capacity",keyword:"2017 honda crv 1.5t oil capacity",make:"Honda",model:"2017 CR-V 1.5L Turbo",title:"2017 Honda CR-V 1.5T Oil Capacity",answer:"Honda lists 3.7 US qt (3.5 L) including a new filter for the 2017 CR-V 1.5L turbo.",scope:"Applies to the 2017 CR-V equipped with the 1.5L turbo. The same model year also offered a 2.4L naturally aspirated engine in some trims, and its refill figure must not be substituted.",detail:"Use 0W-20 engine oil carrying the API certification specified by Honda. Replace the drain-bolt sealing washer, add slightly less than 3.7 qt, start the engine and inspect the filter and drain bolt, then stop on level ground and wait about three minutes before the final dipstick check. Reset the Maintenance Minder only after the service is complete.",capacity:"3.7 US qt",liters:"3.5 L; including filter",source:honda2017Crv},
  {slug:"jeep/wrangler/2018/3-6/oil-capacity",keyword:"2018 jeep wrangler 3.6 oil capacity",make:"Jeep",model:"2018 Wrangler 3.6L",title:"2018 Jeep Wrangler 3.6 Oil Capacity: JK vs. JL",answer:"For the 2018 overlap year, the all-new JL 3.6L takes 5.0 US qt (4.73 L), while the carryover JK 3.6L takes 6.0 US qt (about 5.7 L), both with a new filter.",scope:"Applies specifically to the 2018 Wrangler, when Jeep sold two generations. A JL has the newer body/interior and a JL VIN/platform designation; a Wrangler JK or JK Unlimited uses the earlier platform and its separate manual.",detail:"Do not average the two capacities. The JL manual specifies API-certified SAE 0W-20 meeting FCA MS-6395; the JK manual calls for the grade shown in its own oil section and filler cap. Add below the platform-specific total, run briefly, inspect for leaks, allow drain-back on level ground and finish by dipstick.",capacity:"JL: 5.0 qt; JK: 6.0 qt",liters:"JL: 4.73 L; JK: about 5.7 L",source:jeep2018Jl},
  {slug:"subaru/forester/2019/2-5/oil-capacity",keyword:"2019 subaru forester 2.5 oil capacity",make:"Subaru",model:"2019 Forester 2.5L",title:"2019 Subaru Forester 2.5 Oil Capacity",answer:"Subaru lists 4.4 US qt (4.2 L) for a 2019 Forester 2.5L oil-and-filter change.",scope:"Applies to the redesigned U.S.-market 2019 Forester with the direct-injected 2.5L FB25. Earlier Forester generations and turbocharged models use different capacities and service references.",detail:"Use the 0W-20 oil specification shown in the model-year manual and treat 4.4 qt as a refill reference. Confirm that the old filter gasket came off, install the correct filter and drain-plug sealing washer, fill below the reference, run the engine while checking for leaks, then wait on level ground and bring the dipstick level between the marks without overfilling.",capacity:"4.4 US qt",liters:"4.2 L; with filter",source:subaru2019Forester},
  {slug:"subaru/outback/2020/2-5/oil-capacity",keyword:"2020 subaru outback 2.5 oil capacity",make:"Subaru",model:"2020 Outback 2.5L",title:"2020 Subaru Outback 2.5 Oil Capacity",answer:"Subaru lists 4.4 US qt (about 4.2 L) during an oil-and-filter change for the 2020 Outback 2.5L.",scope:"Applies to the naturally aspirated 2.5L engine in the redesigned 2020 Outback. The available 2.4L turbo uses 4.8 US qt, so the engine label and trim must be confirmed before refill.",detail:"The Subaru guide calls for 0W-20 synthetic meeting its listed API/ILSAC requirements. Replace the filter and drain-plug sealing washer, fill below 4.4 qt first, run the engine while checking for leaks, then shut down on level ground and use the dipstick after drain-back. Subaru notes roughly one quart separates the low and full marks.",capacity:"4.4 US qt",liters:"About 4.2 L; with filter",source:subaru2020Outback},
  {slug:"nissan/altima/2017/2-5/oil-capacity",keyword:"2017 nissan altima 2.5 oil capacity",make:"Nissan",model:"2017 Altima 2.5L",title:"2017 Nissan Altima 2.5 Oil Capacity",answer:"Nissan lists 4-7/8 US qt (4.6 L) with a new filter for the 2017 Altima 2.5L QR25DE.",scope:"Applies to the 2017 Altima 2.5L four-cylinder. The 3.5L VQ35DE in the same manual uses 5-1/8 qt (4.8 L), so displacement must be confirmed before filling.",detail:"The manual recommends Genuine Nissan Motor Oil 0W-20 SN or an equivalent matching that grade and viscosity. Nissan labels the table values approximate: install the correct filter and drain-plug washer, add below 4-7/8 qt, run the engine, inspect for leaks, wait on level ground and determine the final amount from the dipstick.",capacity:"4-7/8 US qt",liters:"4.6 L; with filter",source:nissan2017Altima},
  {slug:"nissan/rogue/2018/2-5/oil-capacity",keyword:"2018 nissan rogue 2.5 oil capacity",make:"Nissan",model:"2018 Rogue 2.5L",title:"2018 Nissan Rogue 2.5 Oil Capacity",answer:"Nissan lists 4-7/8 US qt (4.6 L) with a new filter for the 2018 Rogue 2.5L QR25DE.",scope:"Applies to the full-size 2018 Rogue with the 2.5L QR25DE. It does not apply to the smaller Rogue Sport, which is a separate model with a different engine and manual.",detail:"The same table lists 4-1/2 qt (4.3 L) when the filter is not changed and recommends Nissan 0W-20 SN or equivalent. Because Nissan calls the capacities approximate, refill below the reference first, run the engine while checking the filter and drain plug, allow drain-back on level ground and finish by dipstick.",capacity:"4-7/8 US qt",liters:"4.6 L; with filter",source:nissan2018Rogue},
  {slug:"gmc/sierra-1500/2019/5-3/oil-capacity",keyword:"2019 gmc sierra 1500 5.3 oil capacity",make:"GMC",model:"2019 Sierra 1500 5.3L",title:"2019 GMC Sierra 1500 5.3 Oil Capacity",answer:"The new-body 2019 GMC Sierra 1500 5.3L V8 takes 8.0 US qt (7.6 L) with the oil filter.",scope:"Applies to 2019 Sierra 1500 5.3L gasoline applications after confirming L82 or L84 engine identity. The concurrently sold Sierra 1500 Limited/carryover is a separate manual and platform lookup.",detail:"Capacity is shared between the cited 5.3L variants, but engine code still controls oil specification and service parts. Add below the nominal total, run to fill the filter, inspect for leaks and verify on level ground after the prescribed drain-back interval.",capacity:"8.0 US qt",liters:"7.6 L; with filter",source:gmc2019Sierra},
  {slug:"ford/explorer/2020/2-3-ecoboost/oil-capacity",keyword:"2020 ford explorer 2.3 ecoboost oil capacity",make:"Ford",model:"2020 Explorer 2.3L EcoBoost",title:"2020 Ford Explorer 2.3 EcoBoost Oil Capacity",answer:"Ford lists 4.9 L, approximately 5.2 US qt, including the filter for the 2020 Explorer 2.3L EcoBoost.",scope:"Applies to the redesigned rear-wheel-drive-platform 2020 Explorer with the 2.3L EcoBoost. Do not substitute a Mustang, Ranger or earlier transverse Ford 2.3L capacity simply because the displacement matches.",detail:"The printed model-year manual specifies SAE 5W-30 meeting Ford WSS-M2C946-B1. Install the correct Motorcraft-equivalent filter and drain plug hardware, add slightly less than 4.9 L first, run the engine and inspect for leaks, then switch off on level ground and finish at the dipstick after the oil drains back.",capacity:"About 5.2 US qt",liters:"4.9 L; including filter",source:ford2020Explorer},
  {slug:"hyundai/elantra/2018/2-0/oil-capacity",keyword:"2018 hyundai elantra 2.0 oil capacity",make:"Hyundai",model:"2018 Elantra 2.0L",title:"2018 Hyundai Elantra 2.0 Oil Capacity",answer:"Hyundai lists 4.0 L (4.23 US qt) for a drain and refill on the 2018 Elantra Nu 2.0 MPI.",scope:"Applies to the regular 2018 Elantra sedan with the Nu 2.0 MPI after confirming market and engine. The Elantra Sport/Eco turbo engines and Elantra GT applications have separate specifications.",detail:"The manual groups the refill amount with the approved API/ILSAC oil classification and a separate viscosity chart; use both, not capacity alone. Replace the filter and drain-plug washer, add below 4.0 L first, run the engine and inspect for leaks, then wait on level ground and set the final level with the dipstick.",capacity:"4.23 US qt",liters:"4.0 L; drain and refill",source:hyundai2018Elantra},
  {slug:"kia/optima/2019/2-4/oil-capacity",keyword:"2019 kia optima 2.4 oil capacity",make:"Kia",model:"2019 Optima 2.4L",title:"2019 Kia Optima 2.4 Oil Capacity",answer:"Kia lists 4.8 L (5.07 US qt) for a drain and refill on the 2019 Optima 2.4L GDI.",scope:"Applies to U.S.-market 2019 Optima LX and S models with the 2.4L GDI. The 1.6L turbo, 2.0L turbo and hybrid powertrains use different refill data and should be identified separately.",detail:"Use the oil classification and viscosity chart from the same model-year manual; capacity by itself is not a complete oil specification. Refill below 4.8 L initially, run the engine while checking the new filter and drain plug, shut down on level ground, allow drain-back and finish at the dipstick without exceeding the full mark.",capacity:"5.07 US qt",liters:"4.8 L; drain and refill",source:kia2019Optima},
];
function oilPage(j:OilJob):SpecRecord{return oilGuide({slug:j.slug,keyword:j.keyword,make:j.make,model:j.model,category:"Fluid Capacities",title:j.title,
  metaDescription:`${j.title}: ${j.capacity} with filter, application boundaries, refill procedure, dipstick check and official manual lookup.`,answer:j.answer,scope:j.scope,detail:j.detail,
  values:[{label:"Oil and filter change",value:j.capacity,note:j.liters},{label:"Final level",value:"Verify after drain-back",note:"Level ground and correct procedure"}],sources:[j.source],identity:j.model,distinctions:[j.scope,j.detail],featureImage:oilImage,featureOverlay:true});}

export const dieselServiceSpecs:SpecRecord[]=[...firingJobs.map(firingPage),...headJobs.map(headPage),...torqueJobs.map(torquePage),...oilJobs.map(oilPage)];
