import type { Source, SpecRecord } from "./chevy350-content";
import { firingGuide, lugGuide, sparkGuide, type Base } from "./extended-content";

const reviewed = "2026-08-14";
const lugSedan = "/features/shared-lug-sedan.png";
const lugSuv = "/features/shared-lug-suv.png";
const firingImage = "/features/shared-firing-engine.png";

const source = (label: string, url: string, note: string): Source => ({ label, url, note });

const sources = {
  fordF150: source("2018 Ford F-150 Owner's Manual — wheel nuts", "https://www.fordservicecontent.com/Ford_Content/vdirsnet/OwnerManual/Home/Content?ProcUid=G2227314&Uid=G2267322&buildtype=web&countryCode=USA&div=f&languageCode=en&moidRef=G2154962&userMarket=usa&vFilteringEnabled=False&variantid=10133", "Ford's VIN-filterable wheel-nut specification and 100-mile recheck instruction."),
  fordExplorer: source("2019 Ford Explorer Owner's Manual — wheel lug nuts", "https://www.fordservicecontent.com/Ford_Content/vdirsnet/OwnerManual/Home/Content?ProcUid=G1760877&Uid=G1760876&buildtype=web&countryCode=USA&div=f&languageCode=en&userMarket=CAN&vFilteringEnabled=False&variantid=6426", "Ford's 2019 Explorer fastener size, dry-thread torque, and recheck guidance."),
  fordManuals: source("Ford owner-manual library", "https://www.ford.com/support/owner-manuals/", "Primary Ford manual lookup; select the exact year and vehicle or enter the VIN."),
  gm2020: source("2020 Chevrolet Silverado Owner's Manual — wheel nut torque", "https://www.chevrolet.com/ownercenter/content/dam/gmownercenter/gmna/dynamic/manuals/2020/chevrolet/silverado-1500/2020-chevrolet-silverado-owners-manual.pdf", "Primary Chevrolet manual listing 190 N·m (140 lb-ft) and separating 1500-series applications from HD service data."),
  gmManuals: source("GM Owner Center manuals", "https://experience.gm.com/support/vehicle/manuals-guides", "Primary Chevrolet and GMC manual lookup for year-, model-, and VIN-specific confirmation."),
  ram2019: source("2019 Ram 1500 Owner's Manual", "https://vehicleinfo.mopar.com/assets/publications/en-us/Ram/2019/1500_DT/P128702_19_DT_OM_EN_USC_E7_V1.pdf", "Mopar's DT-platform wheel and tire service information."),
  mopar: source("Mopar owner-manual library", "https://vehicleinfo.mopar.com/", "Primary Ram, Dodge, and Jeep manual lookup for the exact vehicle."),
  toyota: source("Toyota owner's manual library", "https://www.toyota.com/owners/warranty-owners-manuals/", "Primary Toyota manual lookup; confirm the year and model before wheel service."),
  toyotaCamry17: source("2017 Toyota Camry Owner's Manual — wheel nut torque", "https://assets.sia.toyota.com/publications/en/om-s/OM33C64U/pdf/OM33C64U.pdf", "Primary Toyota manual listing 76 ft-lbf (103 N·m) for the 2017 Camry factory wheel nuts."),
  toyotaTacoma21: source("2021 Toyota Tacoma Owner's Manual — wheel nut torque", "https://assets.sia.toyota.com/publications/en/om-s/OM04029U/pdf/OM04029U.pdf", "Primary Toyota manual listing 83 ft-lbf (113 N·m) for the 2021 Tacoma factory wheel nuts."),
  hondaAccord: source("Honda Accord wheel-nut procedure", "https://techinfo.honda.com/rjanisis/pubs/OM/AH/A30A2525IOM/enu/details/131244047-15363.html", "Honda's 80 lbf-ft specification and two-to-three-pass tightening procedure."),
  hondaAccord16: source("2016 Honda Accord Sedan Owner's Guide — replacing a flat tire", "https://techinfo.honda.com/rjanisis/pubs/QS/AH/AT2A1616OG4D/enu/AT2A1616OG-4D.pdf", "Primary Honda guide for the 2016 Accord sedan, including the 80 lbf-ft wheel-nut setting and crisscross tightening procedure."),
  hondaCivic22: source("2022 Honda Civic Sedan — flat-tire procedure", "https://techinfo.honda.com/rjanisis/pubs/OM/AH/AT202222IOM/enu/details/131229047-15363.html", "Honda's 80 lbf-ft specification and illustrated tightening order for the 2022 Civic sedan."),
  hondaManuals: source("Honda owners-manual library", "https://mygarage.honda.com/s/manuals-search", "Primary Honda manual lookup for the exact year, body style, and powertrain."),
  nissan: source("Nissan owner-manual library", "https://www.nissanusa.com/owners/ownership/manuals-guides.html", "Primary Nissan manual lookup for the exact model year."),
  subaru: source("Subaru vehicle resources — owner manuals", "https://www.subaru.com/owners/vehicle-resources.html", "Primary Subaru model-year owner-manual library."),
  hyundai: source("Hyundai owner's manual library", "https://ownersmanual.hyundai.com/", "Official Hyundai lookup for the applicable market and model-year owner manual."),
  kia: source("Kia owner resources", "https://owners.kia.com/content/owners/en/manuals.html", "Primary Kia owner-manual lookup for exact model-year confirmation."),
  mazda: source("Mazda wheel installation procedure", "https://owners-manual.mazda.com/gen/en/cx-5/cx-5_8fy4ee17e/contents/10020109.html", "Mazda's published 108–147 N·m (80–108 ft-lbf) range and dry-fastener warning."),
  vw: source("Volkswagen online owner's manuals", "https://www.vwserviceandparts.com/digital-resources/online-owners-manual/", "Primary Volkswagen VIN-based manual lookup."),
  bmw: source("BMW Driver's Guide", "https://www.bmwusa.com/owners-manuals.html", "Primary BMW VIN-based owner's manual and wheel-service reference."),
  audi: source("Audi owner's manual library", "https://ownersmanual.audiusa.com/", "Primary Audi VIN-based owner's manual lookup."),
  fordPerformance: source("Ford Performance engine history", "https://performanceparts.ford.com/download/pdfs/enginehistory.pdf", "Ford Performance reference for small-block firing-order differences."),
  fordEngine: source("2018 Ford F-150 Owner's Manual — 3.5L EcoBoost engine specifications", "https://www.fordservicecontent.com/Ford_Content/vdirsnet/OwnerManual/Home/Content?ProcUid=G1825147&Uid=G1825132&buildtype=web&countryCode=USA&div=f&languageCode=en&userMarket=usa&vFilteringEnabled=False&variantid=4640", "Ford's application-specific table lists the 1-4-2-5-3-6 firing order for the 3.5L EcoBoost."),
  gmLs: source("Chevrolet Performance LS-family installation guide", "https://www.chevrolet.com/content/dam/chevrolet/na/us/english/index/performance/resources/installation-guides/crate-engines/02-pdf/long-block-install-guide-19260831-19299306-19260833.pdf", "Chevrolet Performance documentation for LS-family cylinder numbering and firing order."),
  toyotaTech: source("Toyota Technical Information System", "https://techinfo.toyota.com/", "Toyota's official service-information source for engine-specific cylinder identification."),
  hondaTech: source("Honda Service Information System", "https://techinfo.honda.com/", "Honda's official service-information source for engine identification and ignition diagnosis."),
  nissanTech: source("Nissan TechInfo", "https://www.nissan-techinfo.com/", "Nissan's official service-information source for VQ engine cylinder identification."),
  subaruTech: source("Subaru Technical Information System", "https://techinfo.subaru.com/stis/", "Subaru's official service-information source for EJ engine layout and diagnostics."),
  cummins: source("Cummins QuickServe Online", "https://quickserve.cummins.com/", "Cummins' official engine-identification and service-information portal."),
  bmwTech: source("BMW Technical Information System", "https://bmwtechinfo.bmwgroup.com/", "BMW's official service-information portal for engine-specific repair data."),
  erwin: source("Volkswagen erWin service information", "https://erwin.vw.com/", "Volkswagen's official repair-information portal."),
};

type LugInput = {
  slug: string; keyword: string; make: string; model: string; title: string;
  torque: string; metric: string; scope: string; source: Source;
  context: string; caution: string; image?: "sedan" | "suv";
};

function editorialLug(input: LugInput): SpecRecord {
  const base: Base = {
    slug: input.slug,
    keyword: input.keyword,
    make: input.make,
    model: input.model,
    category: "Torque Specs",
    title: input.title,
    metaDescription: `${input.title}. Verified ${input.torque} (${input.metric}) factory-wheel value, star-pattern steps, dry-thread guidance, FAQs, and sources.`,
    answer: `For the factory-wheel application covered here, use ${input.torque} (${input.metric}). Tighten clean, dry fasteners in an opposite-side pattern and confirm the exact owner's manual when the wheel or hardware is not original.`,
    detail: `${input.context} The value is a final hand-torque setting, not an impact-wrench target.`,
    scope: input.scope,
    values: [
      { label: "Factory wheel torque", value: input.torque, note: input.metric },
      { label: "Fastener condition", value: "Clean and dry", note: "No oil or anti-seize unless the exact manual directs it" },
      { label: "Tightening method", value: "Star / opposite-side", note: "Hand-start, staged passes, calibrated torque wrench" },
      { label: "Verification", value: "Manual + hardware check", note: "Aftermarket wheels and fasteners may specify a different value" },
    ],
    sources: [input.source],
    identity: `${input.model} with factory wheel fasteners`,
    distinctions: [input.context, input.caution],
    featureImage: input.image === "sedan" ? lugSedan : lugSuv,
    featureOverlay: true,
  };
  const record = lugGuide(base);
  record.intro = [
    `${record.answer} That is the useful number, but it only produces a trustworthy installation when the wheel is fully seated and the friction conditions match the manual. Torque is a proxy for stud tension; rust, lubricant, damaged seats, or an impact gun can make the same wrench reading create a very different clamp load.`,
    `${input.context} This page is deliberately scoped to the named application instead of blending several generations into one chart. ${input.caution} If the vehicle has conversion studs, spacers, locking hardware, or aftermarket wheels, identify those parts before choosing a setting.`,
    "A careful wheel installation is repeatable: inspect, hand-start, snug across the wheel, apply the final setting smoothly, then make a confirmation pass. The diagram and checklist below turn the specification into a procedure a home mechanic or technician can actually audit.",
  ];
  record.sections.unshift({
    heading: `What matters specifically on the ${input.model}`,
    paragraphs: [
      `${input.context} The table keeps the published imperial and metric values together so a unit conversion never becomes a shop-floor guess. Use a socket that fully engages the fastener and a torque wrench whose normal working range comfortably includes ${input.torque}.`,
      `${input.caution} A wheel that rocks on corrosion, paint, or a mismatched seat can feel tight before it is clamped flat. Clean the hub pad and inspect every seat first; torque cannot correct a mechanical mismatch.`,
    ],
  });
  record.faqs[0] = { q: `What is the correct ${input.keyword}?`, a: `${input.torque} (${input.metric}) for the factory-wheel application described here. Confirm non-original wheels, fasteners, and trim-specific instructions separately.` };
  return record;
}

const lugInputs: LugInput[] = [
  { slug:"honda/accord/lug-nut-torque", keyword:"honda accord lug nut torque spec", make:"Honda", model:"Accord", title:"Honda Accord Lug Nut Torque Chart by Model Year", torque:"80 lbf-ft", metric:"108 N·m", scope:"Covers mainstream North American Accord factory-wheel applications; confirm the exact owner's manual for an unusual market, wheel package, or non-original hardware.", source:sources.hondaAccord, context:"Honda's Accord procedure specifies 80 lbf-ft and calls for two or three trips through the illustrated sequence rather than one heavy pass.", caution:"Do not borrow the higher value published for certain performance-oriented Honda wheel packages.", image:"sedan" },
  { slug:"ford/f-150/2018/lug-nut-torque", keyword:"2018 ford f150 lug nut torque spec", make:"Ford", model:"2018 F-150", title:"2018 Ford F-150 Lug Nut Torque Spec", torque:"150 lb-ft", metric:"204 N·m", scope:"Applies to the 2018 Ford F-150 with original M14 x 1.5 wheel studs and factory-style nuts.", source:sources.fordF150, context:"The 2018 F-150 uses M14 x 1.5 studs and Ford publishes a much higher setting than many passenger vehicles.", caution:"Ford also calls for a torque recheck within 100 miles (160 km) after a wheel is disturbed.", image:"suv" },
  { slug:"chevrolet/silverado-1500/2020/lug-nut-torque", keyword:"2020 chevy silverado 1500 lug nut torque spec", make:"Chevrolet", model:"2020 Silverado 1500", title:"2020 Chevy Silverado 1500 Lug Nut Torque Spec", torque:"140 lb-ft", metric:"190 N·m", scope:"Applies to 2020 Chevrolet Silverado 1500 factory wheels and original-style M14 fasteners; it is not a Silverado HD specification.", source:sources.gm2020, context:"The 2020 light-duty Silverado 1500 is a T1-platform truck; do not identify it only by the Silverado badge or wheel diameter.", caution:"Silverado 2500HD/3500HD hardware and procedures are separate applications.", image:"suv" },
  { slug:"ram/1500/2019/lug-nut-torque", keyword:"2019 ram 1500 lug nut torque chart", make:"Ram", model:"2019 1500", title:"2019 Ram 1500 Lug Nut Torque Chart: DT vs. Classic", torque:"130 ft-lb", metric:"176 N·m", scope:"Covers the new-body 2019 Ram 1500 DT factory-wheel application; verify the manual for a 2019 Ram 1500 Classic (DS) or special hardware.", source:sources.ram2019, context:"Ram sold both the redesigned DT and the carryover 1500 Classic during 2019, so the platform name belongs in any serious lookup.", caution:"Identify cone-seat versus flanged hardware rather than assuming two nuts that fit the same socket are interchangeable.", image:"suv" },
  { slug:"toyota/tacoma/2021/lug-nut-torque", keyword:"2021 toyota tacoma wheel lug torque", make:"Toyota", model:"2021 Tacoma", title:"2021 Toyota Tacoma Wheel Lug Torque", torque:"83 ft-lb", metric:"113 N·m", scope:"Applies to 2021 Toyota Tacoma factory wheels with original-style fasteners.", source:sources.toyotaTacoma21, context:"Toyota's Tacoma setting differs from the 76 ft-lb figure seen on many Toyota passenger cars and crossovers.", caution:"Do not choose the value by counting lugs or by copying a RAV4/Camry chart.", image:"suv" },
  { slug:"toyota/camry/2017/lug-nut-torque", keyword:"2017 toyota camry lug nut torque spec", make:"Toyota", model:"2017 Camry", title:"2017 Toyota Camry Lug Nut Torque Spec", torque:"76 ft-lb", metric:"103 N·m", scope:"Applies to 2017 Toyota Camry original wheels and factory-style nuts.", source:sources.toyotaCamry17, context:"The 2017 Camry uses Toyota's 76 ft-lb passenger-car specification, but the hub face and washer/cone-seat condition still determine whether the wheel seats correctly.", caution:"A used replacement wheel must match the original nut-seat design.", image:"sedan" },
  { slug:"honda/civic/2022/lug-nut-torque", keyword:"2022 honda civic lug nut torque specification", make:"Honda", model:"2022 Civic", title:"2022 Honda Civic Lug Nut Torque Specification", torque:"80 lbf-ft", metric:"108 N·m", scope:"Applies to 2022 North American Civic sedan factory wheels; confirm hatchback Type R or non-original wheel instructions separately.", source:sources.hondaCivic22, context:"Honda's 2022 Civic sedan flat-tire procedure explicitly gives 80 lbf-ft and asks for two to three passes through the pattern.", caution:"Do not import the 94 lbf-ft figure from later manual-transmission hatchback guidance without matching the exact model.", image:"sedan" },
  { slug:"honda/accord/2016/lug-nut-torque", keyword:"2016 honda accord lug nut torque chart", make:"Honda", model:"2016 Accord", title:"2016 Honda Accord Lug Nut Torque Chart", torque:"80 lbf-ft", metric:"108 N·m", scope:"Applies to 2016 Honda Accord sedan factory-wheel applications using original-style nuts; verify coupe documentation separately if the hardware is not original.", source:sources.hondaAccord16, context:"Honda's 2016 Accord sedan guide gives 80 lbf-ft and directs the installer to tighten in the illustrated crisscross order rather than loading one side first.", caution:"Accord Crosstour is a different model and should be checked under its own manual.", image:"sedan" },
  { slug:"ford/explorer/2019/lug-nut-torque", keyword:"2019 ford explorer lug nut torque spec", make:"Ford", model:"2019 Explorer", title:"2019 Ford Explorer Lug Nut Torque Spec", torque:"110 lb-ft", metric:"149 N·m", scope:"Applies to the 2019 Ford Explorer with original 1/2-20 wheel studs and factory-style nuts.", source:sources.fordExplorer, context:"Ford lists 110 lb-ft for this Explorer—neither the 100 lb-ft used by some Ford crossovers nor the F-150's 150 lb-ft.", caution:"The manual calls for clean, rust-free threads and a recheck within 100 miles after wheel service.", image:"suv" },
  { slug:"jeep/grand-cherokee/2020/lug-nut-torque", keyword:"2020 jeep grand cherokee lug torque spec", make:"Jeep", model:"2020 Grand Cherokee", title:"2020 Jeep Grand Cherokee Lug Torque Spec", torque:"130 ft-lb base; 110 ft-lb SRT", metric:"176 N·m; 149 N·m", scope:"Applies to 2020 Jeep Grand Cherokee WK2 factory-wheel applications with original-style M14 x 1.50 fasteners; base and SRT models use different values.", source:source("2020 Jeep Grand Cherokee Owner's Manual — wheel and tire torque", "https://vehicleinfo.mopar.com/assets/publications/en-us/Jeep/2020/Grand_Cherokee/P136192_20_WK_OM_EN_USC_DIGITAL.pdf", "Primary Mopar manual listing 130 ft-lb for base models, 110 ft-lb for SRT, a 22 mm socket, and a 25-mile recheck."), context:"The 2020 WK2 manual separates base-model wheel torque at 130 ft-lb from SRT wheel torque at 110 ft-lb; trim identification is therefore part of the specification.", caution:"Inspect swollen two-piece nuts, use a fully engaged six-point 22 mm socket, and replace damaged hardware before torquing.", image:"suv" },
  { slug:"nissan/altima/2018/lug-nut-torque", keyword:"2018 nissan altima lug nut torque spec", make:"Nissan", model:"2018 Altima", title:"2018 Nissan Altima Lug Nut Torque Spec", torque:"83 ft-lb", metric:"113 N·m", scope:"Applies to 2018 Nissan Altima sedan factory wheels and original-style nuts.", source:source("2018 Nissan Altima Owner's Manual — wheel nut tightening torque", "https://owners.nissanusa.com/content/techpub/ManualsAndGuides/Altima/2018/2018-Altima-owner-manual.pdf", "Primary Nissan manual listing 83 ft-lb (113 N·m), dry studs and nuts, and a torque check at each lubrication interval."), context:"The 2018 Altima manual states 83 ft-lb (113 N·m) and calls for the nuts to be tightened alternately and evenly, more than twice through the illustrated sequence.", caution:"Nissan explicitly instructs against oiling or greasing wheel studs and nuts.", image:"sedan" },
  { slug:"chevrolet/tahoe/2021/lug-nut-torque", keyword:"2021 chevy tahoe lug nut torque specification", make:"Chevrolet", model:"2021 Tahoe", title:"2021 Chevy Tahoe Lug Nut Torque Specification", torque:"140 lb-ft", metric:"190 N·m", scope:"Applies to 2021 Chevrolet Tahoe factory wheels and original-style fasteners.", source:source("2021 Chevrolet Tahoe/Suburban Owner's Manual — capacities and specifications", "https://www.chevrolet.com/ownercenter/content/dam/gmownercenter/gmna/dynamic/manuals/2021/chevrolet/tahoe-suburban/2021-chevrolet-tahoe-suburban-owners-manual.pdf", "Primary Chevrolet manual for the redesigned 2021 Tahoe, including the OE wheel-nut setting and crisscross procedure."), context:"The redesigned 2021 Tahoe uses a 140 lb-ft factory-wheel setting; its six-lug pattern needs opposite-side staged passes so the wheel seats flat.", caution:"Do not treat a Silverado HD or aftermarket off-road wheel chart as interchangeable.", image:"suv" },
  { slug:"gmc/sierra-1500/2015/lug-nut-torque", keyword:"2015 gmc sierra 1500 lug nut torque chart", make:"GMC", model:"2015 Sierra 1500", title:"2015 GMC Sierra 1500 Lug Nut Torque Chart", torque:"140 lb-ft", metric:"190 N·m", scope:"Applies to 2015 GMC Sierra 1500 light-duty factory wheels; HD and dual-wheel service procedures require their own verification.", source:source("2015 GMC Sierra Owner's Manual — wheel nut torque", "https://www.gmc.com/ownercenter/content/dam/gmownercenter/gmna/dynamic/manuals/2015/gmc/sierra_1500/2015_gmc_sierra_owners.pdf", "Primary GMC manual listing 190 N·m (140 lb-ft) and separate repeated torque-check guidance for dual-wheel vehicles."), context:"The 2015 Sierra manual lists 140 lb-ft (190 N·m) for original wheel fasteners; wheel diameter does not change that published OE value.", caution:"A Sierra 2500HD/3500HD or dual-wheel service procedure should not be reduced to this light-duty summary.", image:"suv" },
  { slug:"toyota/rav4/2020/lug-nut-torque", keyword:"2020 toyota rav4 lug nut torque spec", make:"Toyota", model:"2020 RAV4", title:"2020 Toyota RAV4 Lug Nut Torque Spec", torque:"76 ft-lb", metric:"103 N·m", scope:"Applies to 2020 North American RAV4 gasoline factory wheels with original-style nuts; verify the separate hybrid manual and non-original hardware where applicable.", source:source("2020 Toyota RAV4 Owner's Manual — wheel nut torque", "https://assets.sia.toyota.com/publications/en/om-s/OM0R024U/pdf/OM0R024U.pdf", "Primary Toyota manual for the 2020 RAV4, including the 76 ft-lbf wheel-nut setting, tapered-seat orientation, and post-installation torque check."), context:"Toyota's 2020 RAV4 manual lists 76 ft-lb (103 N·m) and shows the tapered end of each original nut facing the wheel seat.", caution:"RAV4 Hybrid, RAV4 Prime, and non-original wheel hardware should be verified in their exact manuals or component instructions.", image:"suv" },
  { slug:"honda/cr-v/2018/lug-nut-torque", keyword:"2018 honda crv lug nut torque spec", make:"Honda", model:"2018 CR-V", title:"2018 Honda CR-V Lug Nut Torque Spec", torque:"80 lbf-ft", metric:"108 N·m", scope:"Applies to 2018 North American Honda CR-V factory wheels and original-style nuts.", source:source("2018 Honda CR-V Owner's Guide — replacing a flat tire", "https://techinfo.honda.com/rjanisis/pubs/QS/AH/ATLA1818OG/enu/ATLA1818OG.pdf", "Primary Honda guide specifying 80 lbf-ft (108 N·m) and two-to-three passes through the illustrated tightening order."), context:"Honda's 2018 CR-V guide uses 80 lbf-ft and repeated crisscross passes so the wheel settles evenly on the hub rather than being pulled down from one side.", caution:"Keep the mounting face and tapered nut seats clean and dry; tire pressure is a separate door-jamb specification.", image:"suv" },
  { slug:"subaru/forester/2019/lug-nut-torque", keyword:"2019 subaru forester lug nut torque chart", make:"Subaru", model:"2019 Forester", title:"2019 Subaru Forester Lug Nut Torque Chart", torque:"89 lbf-ft", metric:"120 N·m", scope:"Applies to 2019 North American Subaru Forester factory wheels and original-style nuts.", source:source("2019 Subaru Forester Owner's Manual — tire specifications", "https://techinfo.subaru.com/stis/doc/ownerManual/MSA5M1902B_STIS.pdf", "Primary Subaru manual MSA5M1902B listing 89 lbf-ft (120 N·m), the approximate emergency-wrench hand force, and prompt professional torque verification."), context:"Subaru's 2019 Forester value is 89 lbf-ft after rounding from 120 N·m; the two numbers are the same setting in different units, not alternative targets.", caution:"Never misread the 89 figure as N·m, which would leave the wheel substantially under-torqued.", image:"suv" },
  { slug:"subaru/outback/2022/lug-nut-torque", keyword:"2022 subaru outback lug nut torque spec", make:"Subaru", model:"2022 Outback", title:"2022 Subaru Outback Lug Nut Torque Spec", torque:"89 lbf-ft", metric:"120 N·m", scope:"Applies to 2022 North American Subaru Outback factory-wheel applications, including the owner-manual coverage for Outback Wilderness; non-original hardware remains separate.", source:source("2022 Subaru Legacy/Outback Owner's Manual — tire specifications", "https://techinfo.subaru.com/stis/doc/ownerManual/MSA5M2203A_STIS-Opt.pdf", "Primary Subaru manual for 2022 Legacy, Outback, and Outback Wilderness applications, including the wheel-nut tightening specification and installation procedure."), context:"The 2022 Outback's 120 N·m specification converts to about 89 lbf-ft and is applied in a five-lug star sequence after the wheel has seated flat.", caution:"The supplied wrench guidance is an emergency approximation; confirm the final setting with a calibrated torque wrench as soon as practical.", image:"suv" },
  { slug:"ford/mustang/2017/lug-nut-torque", keyword:"2017 ford mustang wheel lug torque spec", make:"Ford", model:"2017 Mustang", title:"2017 Ford Mustang Wheel Lug Torque Spec", torque:"150 lb-ft", metric:"204 N·m", scope:"Applies to 2017 Ford Mustang factory wheels and original M14 x 1.5 lug nuts; specialty competition wheels require separate instructions.", source:source("2017 Ford Mustang Owner's Manual — wheel lug nut torque", "https://www.fordservicecontent.com/Ford_Content/vdirsnet/OwnerManual/Home/Content?ProcUid=G1660905&Uid=G1642517&buildType=web%2F1000&countryCode=USA&div=f&languageCode=EN&userMarket=USA&vCode=&vFilteringEnabled=False&variantid=4230", "Primary Ford specification listing M14 x 1.5 hardware, 150 lb-ft (204 N·m), clean threads, and a 100-mile recheck."), context:"The S550 Mustang's M14 x 1.5 hardware uses 150 lb-ft, a value substantially higher than older Mustangs with smaller studs.", caution:"Two-piece capped nuts can swell; a socket that does not seat fully is a reason to replace the nut, not hammer it on.", image:"sedan" },
  { slug:"ford/escape/2021/lug-nut-torque", keyword:"2021 ford escape lug nut torque chart", make:"Ford", model:"2021 Escape", title:"2021 Ford Escape Lug Nut Torque Chart", torque:"100 lb-ft", metric:"135 N·m", scope:"Applies to 2021 Ford Escape factory wheels and original M12 x 1.5 lug nuts.", source:source("2021 Ford Escape Owner's Manual — wheel lug nut torque", "https://www.fordservicecontent.com/Ford_Content/vdirsnet/OwnerManual/Home/Content?ProcUid=G2099111&Uid=G2099108&buildtype=web&countryCode=USA&div=f&languageCode=en&moidRef=G539680&userMarket=USA&vFilteringEnabled=True&variantid=7204", "Primary Ford table listing M12 x 1.5 hardware, 100 lb-ft (135 N·m), clean threads, and a 100-mile recheck."), context:"The 2021 Escape uses M12 x 1.5 hardware at 100 lb-ft, so the higher F-150 and Mustang figures are not valid substitutes simply because all three wear Ford badges.", caution:"Ford's clean-thread, clean-hub, and 100-mile recheck guidance remains part of the job.", image:"suv" },
  { slug:"hyundai/elantra/2020/lug-nut-torque", keyword:"2020 hyundai elantra lug nut torque spec", make:"Hyundai", model:"2020 Elantra", title:"2020 Hyundai Elantra Lug Nut Torque Spec", torque:"79–94 lbf-ft", metric:"107–127 N·m", scope:"Applies to 2020 North American Hyundai Elantra factory wheels and original metric lug nuts; aftermarket wheels and hardware follow their own verified instructions.", source:source("2020 Hyundai Elantra Owner's Manual — tires and wheels", "https://www.carmanualsonline.info/hyundai-elantra-2020-owner-s-manual/?srch=wheel+torque", "Model-year manual transcription showing 11–13 kgf·m (79–94 lbf-ft / 107–127 N·m) for every listed original wheel size."), context:"Hyundai publishes a permitted range rather than one midpoint. Select one repeatable final setting inside 79–94 lbf-ft, apply it consistently to all five nuts in a star pattern, and confirm the wheel is sitting flush before the final pass.", caution:"Do not add extra torque beyond the upper limit as a substitute for a recheck, and do not treat the nearby tire-pressure numbers as wheel-fastener values.", image:"sedan" },
  { slug:"hyundai/tucson/2019/lug-nut-torque", keyword:"2019 hyundai tucson lug nut torque specification", make:"Hyundai", model:"2019 Tucson", title:"2019 Hyundai Tucson Lug Nut Torque Specification", torque:"79–94 lbf-ft", metric:"107–127 N·m", scope:"Applies to 2019 North American Hyundai Tucson factory wheels and original metric lug nuts across the 17-, 18-, and 19-inch sizes listed in the owner manual.", source:source("2019 Hyundai Tucson Owner's Manual — wheel installation and tire table", "https://www.carmanualsonline.info/hyundai-tucson-2019-owner-s-manual/?srch=wheel+torque", "Model-year manual pages list 11–13 kgf·m (79–94 lbf-ft / 107–127 N·m), a 30-mile recheck, and a second check near 600 miles."), context:"The 2019 Tucson manual uses 79–94 lbf-ft, not the 65–79 lbf-ft range found in some older Hyundai/Kia applications. It also calls for the wheel nuts to be checked after about 30 miles (50 km) and again after about 600 miles (1,000 km).", caution:"Keep the metric threads clean, reinstall matching nuts with the correct seat, and do not borrow a value from an earlier Tucson generation.", image:"suv" },
  { slug:"kia/optima/2018/lug-nut-torque", keyword:"2018 kia optima lug nut torque spec", make:"Kia", model:"2018 Optima", title:"2018 Kia Optima Lug Nut Torque Spec", torque:"79–94 lbf-ft", metric:"107–127 N·m", scope:"Applies to 2018 North American Kia Optima factory wheels and original metric lug nuts; verify a non-U.S. market car by VIN and manual.", source:source("2018 Kia Optima Owner's Manual — tires and wheels", "https://www.carmanualsonline.info/kia-optima-2018-owners-manual/?srch=wheel+torque", "Model-year owner-manual table and emergency wheel procedure identify the 11–13 kgf·m (79–94 lbf-ft / 107–127 N·m) range."), context:"The 2018 Optima uses a permitted 79–94 lbf-ft range. Hybrid and plug-in-hybrid manuals for the same model year also list 11–13 kgf·m, but exact wheel, nut seat, and market identification still matter.", caution:"Start every nut by hand and use the same final torque around the wheel; a cross-threaded or mismatched nut is not made safe by reaching the wrench setting.", image:"sedan" },
  { slug:"kia/sorento/2020/lug-nut-torque", keyword:"2020 kia sorento wheel lug torque spec", make:"Kia", model:"2020 Sorento", title:"2020 Kia Sorento Wheel Lug Torque Spec", torque:"79–94 lbf-ft", metric:"107–127 N·m", scope:"Applies to 2020 North American Kia Sorento factory wheels and original metric lug nuts on the UM-platform model; the redesigned 2021 vehicle must be checked separately.", source:source("2020 Kia Sorento Owner's Manual — wheel-nut tightening", "https://www.carmanualsonline.info/kia-sorento-2020-owners-manual/?srch=wheel+nut+torque", "Model-year owner-manual procedure for factory wheels; the adjacent 2019 UM manual and Kia manual library corroborate the 11–13 kgf·m range."), context:"The 2020 Sorento uses 79–94 lbf-ft (11–13 kgf·m), not the lower 65–79 lbf-ft band printed in some earlier Kia manuals. Tighten in alternating passes, lower the vehicle fully for the calibrated final pass, and double-check every nut.", caution:"Seat type and thread condition control clamp load; do not lubricate the studs to make the nuts feel smoother or reuse a chart for the next-generation Sorento.", image:"suv" },
  { slug:"mazda/cx-5/2017/lug-nut-torque", keyword:"2017 mazda cx5 lug nut torque chart", make:"Mazda", model:"2017 CX-5", title:"2017 Mazda CX-5 Lug Nut Torque Chart", torque:"80–108 ft-lbf", metric:"108–147 N·m", scope:"Applies to 2017 Mazda CX-5 factory wheels and matching metric lug nuts; Mazda publishes a range rather than a single nominal value.", source:source("2017 Mazda CX-5 Owner's Manual — wheel installation", "https://owners-manual.mazda.com/gen/en/cx-5/cx-5_8fy4ee17e/contents/10020109.html", "Primary Mazda procedure listing 108–147 N·m (80–108 ft-lbf), clean mounting faces, beveled-edge orientation, and dry fasteners."), context:"Mazda's 108–147 N·m range is a permitted band rather than an invitation to exceed its upper limit; choose one repeatable setting inside the band and apply it evenly to every nut.", caution:"Mazda explicitly warns against oil or grease on the wheel nuts and bolts because lubrication changes clamp load.", image:"suv" },
  { slug:"mazda/3/2021/lug-nut-torque", keyword:"2021 mazda 3 lug nut torque spec", make:"Mazda", model:"2021 Mazda3", title:"2021 Mazda3 Lug Nut Torque Spec", torque:"80–108 ft-lbf", metric:"108–147 N·m", scope:"Applies to 2021 North American Mazda3 sedan and hatchback factory wheels, including the listed original 16- and 18-inch applications.", source:source("2021 Mazda3 Owner's Manual — mounting the spare tire", "https://www.mazdausa.com/static/manuals/2021/mazda3/contents/08020301.html", "Primary Mazda USA procedure listing 108–147 N·m (80–108 ft-lbf), clean hub surfaces, beveled-edge orientation, and no oil or grease."), context:"Mazda publishes the same 108–147 N·m permitted range across the listed original 2021 Mazda3 wheel sizes and powertrains, including 2.0, 2.5, and 2.5T applications.", caution:"Use the vehicle's door label for tire pressure; it does not replace the separate wheel-fastener torque range.", image:"sedan" },
  { slug:"dodge/charger/2019/lug-nut-torque", keyword:"2019 dodge charger lug nut torque spec", make:"Dodge", model:"2019 Charger", title:"2019 Dodge Charger Lug Nut Torque Spec", torque:"130 ft-lb base; 111 ft-lb SRT", metric:"176 N·m; 150 N·m", scope:"Covers 2019 Dodge Charger factory wheels and original M14 x 1.50 hardware, with base and SRT applications separated explicitly.", source:source("2019 Dodge Charger User's Guide — wheel and tire torque", "https://vehicleinfo.mopar.com/assets/publications/en-us/Dodge/2019/Charger/10061.pdf", "Primary Mopar guide listing 130 ft-lb for base models, 111 ft-lb for SRT, a 22 mm socket, two star-pattern passes, and a 25-mile recheck."), context:"The 2019 Charger guide separates base-model torque at 130 ft-lb from SRT torque at 111 ft-lb (150 N·m); trim identification is therefore part of the specification.", caution:"Replace swollen capped lug nuts before torquing, fully seat a six-point 22 mm socket, and recheck after 25 miles (40 km).", image:"sedan" },
  { slug:"dodge/challenger/2018/lug-nut-torque", keyword:"2018 dodge challenger lug nut torque chart", make:"Dodge", model:"2018 Challenger", title:"2018 Dodge Challenger Lug Nut Torque Chart", torque:"130 ft-lb base; 111 ft-lb SRT", metric:"176 N·m; 150 N·m", scope:"Covers 2018 Dodge Challenger factory wheels and original M14 x 1.50 hardware, separating base and SRT applications; Demon track guidance must also remain application-specific.", source:source("2018 Dodge Challenger User's Guide — wheel and tire torque", "https://vehicleinfo.mopar.com/assets/publications/en-us/Dodge/2018/Challenger/8640.pdf", "Primary Mopar guide listing 130 ft-lb for base models, 111 ft-lb for SRT, a 22 mm socket, two star-pattern passes, and a 25-mile recheck."), context:"The 2018 Challenger guide separates base-model torque at 130 ft-lb from SRT torque at 111 ft-lb (150 N·m), so a trim-free chart is incomplete.", caution:"Drag-race studs, beadlock wheels, and aftermarket lug hardware are separate engineered systems; verify their supplied instructions.", image:"sedan" },
  { slug:"volkswagen/jetta/2020/lug-bolt-torque", keyword:"2020 volkswagen jetta lug nut torque spec", make:"Volkswagen", model:"2020 Jetta", title:"2020 Volkswagen Jetta Wheel Bolt Torque Spec", torque:"89 ft-lb", metric:"120 N·m", scope:"Applies to 2020 North American Volkswagen Jetta factory steel or alloy wheels with the correct original-style ball-seat wheel bolts.", source:source("Volkswagen 2020 Jetta recall work instructions — wheel bolts", "https://static.nhtsa.gov/odi/rcl/2020/RCRIT-20V359-9397.pdf", "Volkswagen Group of America repair instructions for the 2020 Jetta explicitly direct technicians to torque the wheel bolts to 120 N·m."), context:"The Jetta uses wheel bolts rather than studs with separate lug nuts. Volkswagen's 120 N·m value converts to 88.5 ft-lb, conventionally rounded to 89 ft-lb; the factory wheel's ball seat and the bolt's threaded length must both match.", caution:"Never oil or grease the bolt or hub threads. A cone-seat aftermarket bolt can thread into the hub yet fail to clamp an original ball-seat Volkswagen wheel correctly.", image:"sedan" },
  { slug:"volkswagen/tiguan/2019/lug-bolt-torque", keyword:"2019 volkswagen tiguan lug nut torque specification", make:"Volkswagen", model:"2019 Tiguan", title:"2019 Volkswagen Tiguan Wheel Bolt Torque Specification", torque:"103 ft-lb", metric:"140 N·m", scope:"Applies to the 2019 Volkswagen Tiguan factory steel or alloy wheels and the correct original-style wheel bolts covered by the cited model-year manual.", source:source("2019 Volkswagen Tiguan Owner's Manual — wheel bolts", "https://www.carmanualsonline.info/volkswagen-tiguan-2019-owners-manual/?srch=wheel+bolts", "Model-year manual procedure specifies 140 N·m for steel or alloy wheels, immediate torque-wrench verification, clean hub threads, and no lubrication."), context:"The 2019 Tiguan manual lists 140 N·m, which converts to about 103 ft-lb. That is higher than the 120 N·m value used on many Volkswagen passenger cars, so a generic VW chart is not an acceptable substitute.", caution:"Replace corroded or difficult-to-turn bolts before the torque check, clean the hub threads, and verify the seat shape and threaded length when non-original wheels are installed.", image:"suv" },
  { slug:"bmw/3-series/2021/wheel-bolt-torque", keyword:"2021 bmw 3 series wheel lug torque spec", make:"BMW", model:"2021 3 Series", title:"2021 BMW 3 Series Wheel Bolt Torque Spec", torque:"101 lb-ft", metric:"140 N·m", scope:"Applies to 2021 BMW 3 Series factory wheels and correct original-style wheel bolts, including the matching coded locking bolt where equipped.", source:source("2021 BMW 3 Series Owner's Manual — wheel change", "https://www.carmanualsonline.info/bmw-3-series-2021-owner-s-manual/35", "The model-year BMW manual specifies 101 lb-ft / 140 N·m, crosswise tightening, and a calibrated torque-wrench verification after installation."), context:"BMW publishes 140 N·m as 101 lb-ft in this manual. Tighten the five bolts crosswise only after the wheel is centered and every bolt has been started by hand; then reset or reinitialize the tire-monitoring system as the vehicle requires.", caution:"Fully seat the coded adapter on the locking bolt before applying torque, and do not reuse a bolt whose threads or seat are damaged simply because it can still reach the setting.", image:"sedan" },
  { slug:"audi/a4/2018/wheel-bolt-torque", keyword:"2018 audi a4 lug nut torque chart", make:"Audi", model:"2018 A4", title:"2018 Audi A4 Wheel Bolt Torque Chart", torque:"90 ft-lb", metric:"120 N·m", scope:"Applies to 2018 Audi A4 factory steel and alloy wheels with the correct original ball-seat wheel bolts; wheel packages with separate instructions remain application-specific.", source:source("2018 Audi A4 Owner's Manual — changing a wheel", "https://www.carmanualsonline.info/audi-a4-2018-owners-manual/?srch=wheel+bolt+torque", "The model-year manual specifies 90 ft-lb (120 N·m), prompt torque-wrench verification, tire-pressure correction, and replacement of corroded bolts."), context:"Audi's manual rounds 120 N·m to 90 ft-lb. Because the A4 uses removable wheel bolts, thread engagement and the ball-seat profile are part of the specification; torque alone cannot compensate for a bolt that is too short, too long, or the wrong seat.", caution:"Drive carefully until the final setting has been verified with a calibrated torque wrench, and replace corroded or difficult-to-turn bolts before the check.", image:"sedan" },
];

const accordSpark = sparkGuide({
  slug:"honda/accord/spark-plug-gap", keyword:"honda accord spark plug gap", make:"Honda", model:"Accord", category:"Ignition Specs",
  title:"Honda Accord Spark Plug Gap by Engine and Model Year",
  metaDescription:"Honda Accord spark plug gap guide explaining the common 1.0–1.1 mm legacy range, modern pre-gapped fine-wire plugs, engine identification, measurement, and installation.",
  answer:"For the 2008–2012 Accord 2.4L service procedure, the new-plug electrode gap is 1.0–1.1 mm (0.039–0.043 in). This is not a universal Accord value: V6, earlier generations, 2018-and-later turbo engines and hybrids must be matched by engine code and approved plug part number.",
  detail:"The covered service data specifies the fine-wire NGK IIZKR7B-11S family and a 1.0–1.1 mm new-plug range. Measure gently with a wire gauge; replace a damaged or substantially out-of-range fine-wire plug instead of levering against its center electrode.",
  scope:"The exact range applies to the 2008–2012 Accord 2.4L application in the cited service-manual transcription. Other Accord engines and generations require their own Honda specification.",
  values:[
    {label:"2008–2012 Accord 2.4L", value:"0.039–0.043 in", note:"1.0–1.1 mm; new plug standard"},
    {label:"2018+ 1.5T / 2.0T and later engines", value:"Match OE part number", note:"Inspect the supplied fine-wire gap; do not apply a legacy number blindly"},
    {label:"Measurement tool", value:"Wire-style gauge", note:"Do not lever against the center electrode"},
    {label:"Final authority", value:"VIN + engine code", note:"Honda service data and approved plug application"},
  ],
  sources:[source("2008–2012 Honda Accord service manual — spark-plug inspection", "https://www.haccord.org/spark_plug_inspection-730.html", "Factory service-manual transcription specifying NGK IIZKR7B-11S and a 1.0–1.1 mm (0.039–0.043 in) new-plug electrode gap for the covered Accord 2.4L application."), sources.hondaTech], identity:"2008–2012 Honda Accord 2.4L gasoline engine",
  distinctions:["Accord spans carbureted, naturally aspirated fuel-injected, hybrid, and turbocharged generations, so the model name alone cannot select a plug.", "A correct gap cannot make a plug with the wrong reach, seat, heat range, or electrode design suitable."],
  featureImage:firingImage, featureOverlay:true,
});
accordSpark.sections.unshift({heading:"Start with the engine, not the badge", paragraphs:["An Accord search can refer to several unrelated four-cylinder and V6 families. Read the eighth VIN character where applicable, the emissions label, and the plug number removed from an unmodified engine. Then cross-check the approved Honda application before measuring anything.", "For a modern laser-iridium plug, consistency among a set matters, but aggressive regapping is the wrong quality-control method. Shipping damage, a crooked ground strap, or a chipped insulator calls for replacement."]});

type FiringInput = { slug:string; keyword:string; make:string; model:string; title:string; order:string; numbering:string; scope:string; context:string; caution:string; source:Source };
const researchedFiringEditorial:Record<string,{sections:SpecRecord["sections"];faqs:SpecRecord["faqs"]}>={
  "honda/j35/firing-order":{
    sections:[
      {heading:"The Honda diagram this page is anchored to",paragraphs:["Honda's 2025 warranty-extension bulletin for the 2013–2017 Odyssey includes an engine-view diagram that labels the rear, firewall-side bank as cylinders 1-2-3 and the front, radiator-side bank as 4-5-6. The same figure prints the firing order as 1-4-2-5-3-6. That makes this page an application-specific reference for the transverse Odyssey J35, not a promise that every vehicle ever fitted with a J35 presents the engine from the same viewing angle.","The bulletin also identifies the crankshaft-pulley side. That orientation marker matters because words such as left, right, front and rear can change meaning depending on whether a person is standing at the bumper or sitting in the vehicle. Start with the pulley side and the numbered banks shown by Honda; only then translate a scan-tool cylinder number into a physical coil, plug or injector." ]},
      {heading:"How to use the order during a misfire diagnosis",paragraphs:["A P0301 through P0306 code names a physical cylinder. It does not name that cylinder's position in the combustion sequence. For example, cylinder 4 is the first cylinder on the front bank in the covered Odyssey layout, even though it is the second event in 1-4-2-5-3-6. Record freeze-frame data and any companion fuel-trim or injector codes before clearing memory.","A careful coil-swap test changes one thing at a time. Label both coils, move the suspected coil to a known cylinder, clear the code only after recording it, and repeat the operating conditions that set the fault. If the misfire follows the coil, the result points toward the coil or its connection. If it stays on the original cylinder, continue with the plug, injector command, compression, valve clearance and mechanical checks rather than replacing an entire bank of parts." ]},
      {heading:"VCM and bank language without the common mix-ups",paragraphs:["Honda's Variable Cylinder Management strategy is one reason J35 searches often mention particular cylinders or a rear bank. VCM information is calibration- and vehicle-specific; it does not change the mechanical firing order or renumber the engine. Treat a VCM-related symptom, oil-consumption concern or bulletin as a separate diagnostic layer and confirm the exact VIN eligibility before applying it.","Bank 1 on the cited transverse layout is the firewall bank because that bank contains cylinder 1. Bank identity follows cylinder numbering—not the driver's seating position and not whichever side is easiest to reach. Oxygen-sensor bank labels, coil connector labels and physical cylinder numbers should all be checked against the same application diagram before parts are swapped." ]},
    ],
    faqs:[
      {q:"What is the firing order for the 2013–2017 Honda Odyssey 3.5L J35?",a:"Honda's application diagram lists 1-4-2-5-3-6."},
      {q:"Where is cylinder 1 on the covered Honda J35?",a:"It is on the rear/firewall-side bank. That bank contains cylinders 1-2-3; the front/radiator-side bank contains 4-5-6."},
      {q:"Does P0304 mean the fourth event in the firing order?",a:"No. P0304 identifies physical cylinder 4, which is the second combustion event in the 1-4-2-5-3-6 sequence."},
      {q:"Can I use this bank orientation for every Honda or Acura J35?",a:"Do not assume so. The order is well established, but installed orientation, suffix, wiring and service procedures must be confirmed for the exact vehicle and J35 variant."},
    ],
  },
  "volkswagen/2-0-tsi/firing-order":{
    sections:[
      {heading:"Exact application: 2014 Golf and GTI CBFA/CCTA",paragraphs:["Volkswagen's January 2014 Golf/GTI Quick Reference Specification Book identifies the 2.0L CBFA and CCTA engines and lists the ignition sequence as 1-3-4-2. The same table specifies a 1.0–1.1 mm spark-plug gap and 25 N·m plug torque, useful cross-checks when the task involves ignition service rather than firing-order identification alone.","This application boundary is important. '2.0 TSI' appears on several Volkswagen Group engine generations, while a 2.0L badge can also describe a naturally aspirated engine with different ignition hardware. Read the engine code from the vehicle data label or service information before ordering coils, plugs, injectors or timing components." ]},
      {heading:"Cylinder numbering and coil-on-plug diagnosis",paragraphs:["The four cylinders form one row, numbered 1-2-3-4 from the timing-drive end toward the transmission on the covered installation. The combustion events then occur 1-3-4-2. Because each plug has an individual coil, there is no distributor-cap tower sequence to rewire; the diagram's job is to connect a physical cylinder to scan data, coil connectors and component locations.","For a P030x complaint, save freeze-frame data and note whether P0300, fuel-pressure, cam/crank correlation or mixture codes are present. Inspect the plug well for oil or water, check the connector lock and harness strain, and use a controlled coil swap only when the parts are interchangeable. A misfire that remains on the same cylinder after a verified coil swap calls for plug, injector, compression, valve-train and intake-leak testing." ]},
      {heading:"EA888 generation boundaries matter",paragraphs:["Later EA888 Gen 3 technical data also uses 1-3-4-2, but that shared order does not make the engines service-identical. Timing-drive design, ignition parts, fuel-system pressure, sensor locations and repair procedures can change with engine code and model year. A correct firing-order page should help identify a cylinder without encouraging parts interchange across generations.","Do not rotate or disturb timing components merely to investigate crossed coils: the engine management system schedules spark electronically. If correlation codes or mechanical timing symptoms are present, move to the exact Volkswagen repair procedure for the engine code and use its locking tools, timing marks and torque stages." ]},
    ],
    faqs:[
      {q:"What is the firing order for a 2014 VW Golf or GTI 2.0 TSI CBFA/CCTA?",a:"Volkswagen lists the ignition sequence as 1-3-4-2."},
      {q:"Where is cylinder 1 on the covered VW 2.0 TSI?",a:"Cylinder 1 is at the timing-drive end of the inline engine; numbering continues 1-2-3-4 toward the transmission."},
      {q:"Does the VW 2.0 TSI have distributor wires to arrange?",a:"No. The covered CBFA/CCTA engines use coil-on-plug ignition. Use the order for cylinder identification and diagnosis, not for arranging cap towers."},
      {q:"Is every Volkswagen 2.0L engine covered by this diagram?",a:"No. Confirm the engine code. Other 2.0L gasoline engines and later EA888 generations may share the order while using different parts and procedures."},
    ],
  },
};
function editorialFiring(input:FiringInput):SpecRecord {
  const base:Base = {
    slug:input.slug, keyword:input.keyword, make:input.make, model:input.model, category:"Firing Order", title:input.title,
    metaDescription:`${input.model} firing order ${input.order}, cylinder numbering, interactive diagram, connector-routing notes, troubleshooting, FAQs, and official source links.`,
    answer:`The ${input.model} firing order is ${input.order}. ${input.numbering}`,
    detail:input.context, scope:input.scope,
    values:[
      {label:"Firing order", value:input.order, note:"One complete four-stroke combustion sequence"},
      {label:"Cylinder numbering", value:input.numbering, note:"Confirm orientation before moving wires or coils"},
      {label:"Diagnostic rule", value:"Identify before swapping", note:"Coil connector number and cylinder number are not interchangeable"},
    ],
    sources:[input.source], identity:input.model, distinctions:[input.context,input.caution], featureImage:firingImage, featureOverlay:true,
  };
  const record=firingGuide(base);
  const rows=[...input.numbering.matchAll(/(?:bank|side) (?:is|carries) ([0-9](?:[-–][0-9])*)/gi)].map((match)=>match[1].split(/[-–]/));
  const inline=input.numbering.match(/Cylinders (?:are |are numbered )?([0-9](?:[-–][0-9])*)/i);
  record.diagram.banks=rows.length ? rows : inline ? [inline[1].split(/[-–]/)] : undefined;
  record.diagram.engineLabel=input.model;
  record.diagram.orientation=input.numbering.split(".")[0];
  record.intro=[`${record.answer} The order is simple to print; the difficult part is applying it to the correct physical cylinders. ${input.context}`, `A firing-order diagram should answer three separate questions: which cylinder is which, what sequence the crankshaft uses, and how the ignition system reaches each cylinder. ${input.caution} The interactive drawing below keeps the order visible while the table preserves the numbering notes in crawlable text.`, "Before disconnecting anything, photograph the harness or leads, label both ends, and identify the engine from a durable source. That five-minute audit is faster than diagnosing a crossed pair after the engine has been reassembled."];
  record.sections.unshift({heading:`Reading the ${input.model} diagram correctly`, paragraphs:[`${input.numbering} Read the vehicle as installed and use the manufacturer's left/right convention, not the side from which you happen to be standing. The first cylinder listed in ${input.order} begins the sequence but does not define a universal connector position.`, `${input.context} ${input.caution} On coil-on-plug engines, use the diagram for cylinder identity and diagnosis; the PCM, not a physical distributor cap, schedules spark.`]});
  const editorial=researchedFiringEditorial[input.slug];
  if(editorial){record.sections.unshift(...editorial.sections);record.faqs=editorial.faqs;}
  return record;
}

const firingInputs:FiringInput[]=[
  {slug:"ford/5-0-coyote/firing-order",keyword:"ford 5.0 ecoboost firing order",make:"Ford",model:"Gen 1–3 5.0L Coyote V8",title:"Ford 5.0 ‘EcoBoost’ Firing Order: Coyote Engine Correction",order:"1-5-4-8-6-3-7-2",numbering:"Passenger/right bank is 1-2-3-4 and driver/left bank is 5-6-7-8, with both banks numbered from the front accessory end toward the transmission.",scope:"Covers first-, second- and third-generation production-style 5.0L Coyote V8s. Ford did not market a production 5.0L EcoBoost; EcoBoost denotes turbocharged engines such as the 2.7L and 3.5L V6, while later fourth-generation Coyote applications require their own model-year specification.",context:"Ford Performance's Coyote technical guide explicitly lists 1-5-4-8-6-3-7-2 for Gen 1, Gen 2 and Gen 3 engines. Correcting the searched '5.0 EcoBoost' label prevents a turbo-V6 diagram from being applied to this naturally aspirated coil-on-plug V8.",caution:"Do not substitute the traditional 302/5.0 HO order, and do not assume every modern 5.0 shares the same calibration. A replacement camshaft, racing crankshaft or later production revision can make the component documentation decisive.",source:source("Ford Performance Coyote technical reference — Gen 1, 2 and 3", "https://www-performanceparts.app.ford.com/download/instructionsheets/COYOTE_TECH_GUIDE_062819.PDF", "Primary Ford Performance guide explicitly listing firing order 1-5-4-8-6-3-7-2 for Gen 1, Gen 2 and Gen 3 5.0L Coyote engines.")},
  {slug:"ford/3-5-ecoboost/firing-order",keyword:"ford f150 3.5 ecoboost firing order diagram",make:"Ford",model:"F-150 3.5L EcoBoost V6",title:"Ford F-150 3.5 EcoBoost Firing Order Diagram",order:"1-4-2-5-3-6",numbering:"Passenger bank is 1-2-3 and driver bank is 4-5-6, front to rear.",scope:"Covers longitudinal 3.5L EcoBoost V6 engines in the Ford F-150; transverse Ford/Lincoln installations require their own orientation diagram.",context:"Ford's F-150 engine-specification table confirms the firing order. Twin turbochargers and coil-on-plug ignition do not change the mechanical combustion sequence.",caution:"A P0304 code identifies physical cylinder 4, not the fourth event in the firing order.",source:sources.fordEngine},
  {slug:"toyota/4-0-v6/firing-order",keyword:"toyota 4.0 v6 firing order diagram",make:"Toyota",model:"4.0L 1GR-FE V6",title:"Toyota 4.0 V6 1GR-FE Firing Order Diagram",order:"1-2-3-4-5-6",numbering:"Bank 1 is 1-3-5 and Bank 2 is 2-4-6, with each bank numbered from the front/timing-chain end toward the transmission; on common left-hand-drive longitudinal installations Bank 1 is the passenger/right bank.",scope:"Covers the production 1GR-FE 4.0L V6 used in Toyota truck and SUV applications. Dual-VVT-i revisions, market orientation and connector access should still be matched to the VIN and repair manual.",context:"Toyota's 1GR-FE engine service data explicitly lists the 1-2-3-4-5-6 firing order. The notation appears sequential, but consecutive combustion events alternate between the odd- and even-numbered cylinder banks.",caution:"Bank 1 is defined by cylinder 1, not universally by the driver's seating position. Identify the timing-chain end and engine code before interpreting a scan-tool cylinder or A/F-sensor bank fault.",source:source("Toyota 1GR-FE engine service manual — specifications", "https://manualplace.com/lib/toyota-engine-1grfe-4-0-repair-manual-sample.pdf", "Toyota factory-format engine specifications explicitly list firing order 1-2-3-4-5-6 for the 1GR-FE and provide the matching engine identity and service data.")},
  {slug:"toyota/2gr-fe/firing-order",keyword:"toyota 3.5 v6 2gr-fe firing order diagram",make:"Toyota",model:"2010 Highlander 3.5L 2GR-FE V6",title:"Toyota 3.5 V6 2GR-FE Firing Order Diagram",order:"1-2-3-4-5-6",numbering:"On the covered transverse Highlander installation, the rear/firewall Bank 1 carries 1-3-5 and the front/radiator Bank 2 carries 2-4-6; cylinders on each bank run from the timing-drive end toward the transmission.",scope:"The cited factory service data covers the 2010 Highlander 2GR-FE. Other Toyota/Lexus 2GR-FE vehicles share the mechanical order, but longitudinal installations and later 2GR-FKS/FXE/FSE variants must be viewed using their own orientation and service information.",context:"Toyota service data explicitly lists 1-2-3-4-5-6. That sequential notation is the combustion order, not a single physical row: consecutive events alternate between the odd- and even-numbered cylinder banks.",caution:"Use engine code and installed orientation before calling a coil front, rear, left or right. Bank 1 is the bank containing cylinder 1, not a universal driver-side designation.",source:source("2010 Toyota Highlander factory service data — 2GR-FE firing order", "https://charm.li/Toyota/2010/Highlander%204WD%20V6-3.5L%20%282GR-FE%29/Repair%20and%20Diagnosis/Specifications/Mechanical%20Specifications/Ignition%20System/Firing%20Order/", "Factory service-data transcription explicitly listing firing order 1-2-3-4-5-6 for the covered 2010 Highlander 2GR-FE.")},
  {slug:"honda/j35/firing-order",keyword:"honda 3.5 v6 firing order diagram",make:"Honda",model:"2013–2017 Odyssey 3.5L J35 V6",title:"Honda 3.5 V6 J35 Firing Order Diagram",order:"1-4-2-5-3-6",numbering:"Rear/firewall bank is 1-2-3 and front/radiator bank is 4-5-6 on the covered transverse 2013–2017 Odyssey installation.",scope:"The exact diagram and orientation on this page are anchored to Honda's 2013–2017 Odyssey J35 service bulletin. Other Honda and Acura J35 suffixes retain engine-family similarities but require their own installed-orientation, wiring and service information.",context:"Honda's application diagram places consecutive cylinders along each bank rather than using the odd/even bank convention seen on many other V6 engines.",caution:"VCM references, P030x codes and coil connector locations must be traced by physical cylinder number, not by firing-event position.",source:source("Honda service bulletin 25-060 — J35 cylinder layout and firing order", "https://static.nhtsa.gov/odi/tsbs/2025/MC-11020825-0001.pdf", "Honda-authored 2013–2017 Odyssey repair bulletin with an engine-view diagram labeling Bank 1 cylinders 1-2-3, Bank 2 cylinders 4-5-6 and firing order 1-4-2-5-3-6.")},
  {slug:"honda/k24/firing-order",keyword:"honda 2.4 k24 firing order diagram",make:"Honda",model:"K24A/K24Z 2.4L Inline-Four",title:"Honda 2.4 K24 Firing Order Diagram",order:"1-3-4-2",numbering:"Cylinders are numbered 1-2-3-4 in one row from the timing-chain end toward the transmission.",scope:"Covers production K24A- and K24Z-family inline-four engines using the standard crankshaft and PCM strategy. Later direct-injected K24W engines, mixed K20/K24 builds and racing crankshafts require their exact engine or component documentation.",context:"Factory-manual-derived K24 service data lists the 1-3-4-2 combustion order. Because the engine has one cylinder row, timing-chain-end orientation is more dependable than left/right language, which changes with where the observer stands.",caution:"The coil-harness branches may not appear in simple 1-2-3-4 order after routing around the valve cover. Label connectors by physical cylinder before unplugging them and interpret a P030x code by cylinder number, not firing-event position.",source:source("Honda K24 factory-manual-derived specifications", "https://meksta.com/en/engines/honda-k24", "K24A/K24Z rebuild reference cross-checked against Honda factory manuals and explicitly listing firing order 1-3-4-2; exact vehicle service information remains available through Honda TechInfo.")},
  {slug:"nissan/vq35de/firing-order",keyword:"nissan 3.5 vq35de firing order diagram",make:"Nissan",model:"2005 Infiniti FX35 VQ35DE V6",title:"Nissan 3.5 VQ35DE Firing Order Diagram",order:"1-2-3-4-5-6",numbering:"Right/passenger bank is 1-3-5 and left/driver bank is 2-4-6 on the covered longitudinal FX35 installation, with both banks numbered from the front of the engine toward the transmission.",scope:"The exact order and orientation here cover the longitudinal VQ35DE as installed in the 2005 Infiniti FX35. Transverse Maxima, Altima, Murano and Quest packaging must be viewed in its installed orientation, while the later VQ35HR is a distinct service application.",context:"The factory service manual's VQ35DE tune-up table lists firing order 1-2-3-4-5-6. Those six consecutive events alternate between odd- and even-numbered banks, so firing-event position cannot be used as a physical-cylinder address.",caution:"Use the engine code and chassis manual before moving connectors. A P0303 fault means physical cylinder 3; it does not mean the third cylinder encountered from whichever side of the vehicle is easiest to reach.",source:source("2005 Infiniti FX35 factory service manual — VQ35DE tune-up data", "https://www.carmanualsonline.info/infiniti-fx35-2005-service-manual/?srch=vq35de", "Factory service-manual transcription explicitly lists the VQ35DE firing order as 1-2-3-4-5-6 for the covered longitudinal FX35 application.")},
  {slug:"subaru/ej25/firing-order",keyword:"subaru 2.5 ej25 firing order diagram",make:"Subaru",model:"2.5L EJ25 Boxer-Four",title:"Subaru 2.5 EJ25 Firing Order Diagram",order:"1-3-2-4",numbering:"Passenger/right side carries cylinders 1 and 3; driver/left side carries 2 and 4, with the lower-numbered cylinder on each bank nearest the front/timing-belt end.",scope:"Covers the mechanical firing order and established Subaru boxer cylinder numbering used by common EJ25 engines. Turbo versus naturally aspirated versions, phase changes and coil-on-plug versus remote-coil ignition still require the exact engine code and model-year manual.",context:"Subaru factory service specifications list 1-3-2-4, and the horizontally opposed layout means a conventional inline-four drawing is actively misleading. The two cylinders on each bank lie opposite the other bank rather than in one front-to-rear row.",caution:"A wasted-spark coil pack can fire paired plugs simultaneously, but that electrical pairing is not the four-event combustion order. Trace tower labels or individual coil connectors from the exact wiring diagram before swapping leads.",source:source("1999 Subaru Legacy factory service manual — engine specifications", "https://www.carmanualsonline.info/subaru-legacy-1999-service-repair-manual/?srch=gas+type", "Factory service-manual transcription explicitly lists the horizontally opposed engine firing order as 1-3-2-4; later ignition hardware must still be matched by engine code.")},
  {slug:"chevrolet/2-8-duramax/firing-order",keyword:"chevy 2.8 duramax firing order diagram",make:"Chevrolet",model:"2.8L Duramax LWN Inline-Four",title:"Chevy 2.8 Duramax Firing Order Diagram",order:"1-3-4-2",numbering:"Cylinders are numbered 1-2-3-4 from the front/timing-drive end toward the transmission in the longitudinal Colorado/Canyon installation.",scope:"Covers the GM 2.8L LWN Duramax used in North American Chevrolet Colorado and GMC Canyon applications. The closely related overseas LWH and vehicle-specific emissions systems require their own service information.",context:"GM Powered Solutions data explicitly lists the LWN firing order as 1-3-4-2 and identifies it as a longitudinal 2.8L inline-four. It is unrelated to the 6.6L Duramax V8, so neither its bank diagram nor its eight-cylinder order applies.",caution:"Common-rail injector connector number, injector compensation data and firing-event position are different references. Depressurize and service the fuel system only by the exact GM procedure; the diagram is for cylinder identity, not permission to loosen a high-pressure line.",source:source("GM Powered Solutions 2.8L LWN Duramax specifications", "https://downloads.regulations.gov/NHTSA-2023-0022-0039/attachment_5.pdf", "Primary General Motors specification sheet identifying the longitudinal LWN inline-four and explicitly listing firing order 1-3-4-2.")},
  {slug:"ram/6-7-cummins/firing-order",keyword:"dodge 6.7 cummins firing order diagram",make:"Ram",model:"6.7L Cummins Inline-Six",title:"Dodge/Ram 6.7 Cummins Firing Order Diagram",order:"1-5-3-6-2-4",numbering:"Cylinders are numbered 1-2-3-4-5-6 from the front gear-housing/radiator end toward the flywheel and transmission.",scope:"Covers the mechanical firing sequence of the production 6.7L Cummins inline-six used in Ram heavy-duty trucks. Model year, calibration, emissions generation and engine serial number still control fuel-system and valve-service procedures.",context:"Cummins' manufacturer-hosted adjustment literature uses the 1-5-3-6-2-4 inline-six sequence, while Cummins identifies the QSB6.7 architecture as an inline six. The truck engine has one cylinder row, not two banks.",caution:"Older searches often say 'Dodge 6.7,' but later trucks carry Ram branding. Naming does not change the order; it does matter when retrieving the correct model-year wiring, injector coding and aftertreatment procedure.",source:source("Cummins/Jacobs inline-six adjustment sequence", "https://www.cummins.com/sites/default/files/jvs/service_literature/42562_PN_28542_Rev_F_2018.pdf", "Cummins-hosted service instructions explicitly use firing order 1-5-3-6-2-4; exact Ram 6.7L procedures remain engine-serial-number and model-year specific in QuickServe.")},
  {slug:"ford/6-7-power-stroke/firing-order",keyword:"ford 6.7 powerstroke firing order diagram",make:"Ford",model:"6.7L Power Stroke V8",title:"Ford 6.7 Power Stroke Firing Order Diagram",order:"1-3-7-2-6-5-4-8",numbering:"Passenger bank is 1-2-3-4 and driver bank is 5-6-7-8, front to rear.",scope:"Covers Ford 6.7L Power Stroke diesel V8 applications using the production firing sequence; generation-specific service procedures and injector coding still require the exact manual.",context:"Ford's Power Stroke technical reference publishes both the sequence and physical bank numbering, preventing a gasoline Modular/Coyote diagram from being misapplied.",caution:"Injector coding, connector identification, and relative-compression diagnosis require the exact model-year service procedure.",source:source("Ford 6.7L Power Stroke engine specifications and cylinder order", "https://www.fordservicecontent.com/Ford_Content/Catalog/service_tip_files/Replaced_67CTB03_MCS6720.pdf", "Primary Ford technical reference listing firing order 1-3-7-2-6-5-4-8 and cylinders 1-4 on Bank 1 and 5-8 on Bank 2, front to rear.")},
  {slug:"gm/6-6-duramax/firing-order",keyword:"gm 6.6 duramax firing order diagram",make:"GMC",model:"2007.5–2010 LMM 6.6L Duramax V8",title:"GM 6.6 Duramax Firing Order Diagram",order:"1-2-7-8-4-5-6-3",numbering:"Passenger/right bank is 1-3-5-7 and driver/left bank is 2-4-6-8, with both banks numbered from the front of the engine toward the transmission.",scope:"The cited diagnostic reference specifically covers 2007.5–2010 LMM Duramax engines. The base mechanical order is shared across familiar 6.6L truck generations, but LB7, LLY, LBZ, LMM, LML, L5P and medium-duty variants require their own injector, harness and service procedures.",context:"The LMM diagnostic manual explicitly lists 1-2-7-8-4-5-6-3. This order differs from classic Chevrolet gasoline V8, LS/EcoTec3 gasoline V8 and Ford diesel sequences, even though their cylinder-bank drawings can look superficially similar.",caution:"Identify the RPO from the vehicle and engine before electrical work. Injector balance-rate display, harness connector position and the eight mechanical combustion events are related diagnostic references but are not interchangeable labels.",source:source("2007.5–2010 GM 6.6L LMM Duramax diagnostic manual", "https://oregonfuelinjection.com/wp-content/uploads/2016/08/gm-duramax-07.5-10-diagnostic.pdf", "Application-specific LMM diagnostic manual explicitly listing the Duramax firing order as 1-2-7-8-4-5-6-3 and tying injector diagnosis to physical cylinder identity.")},
  {slug:"bmw/n55/firing-order",keyword:"bmw n55 engine firing order diagram",make:"BMW",model:"N55B30 3.0L Inline-Six",title:"BMW N55 Engine Firing Order Diagram",order:"1-5-3-6-2-4",numbering:"Cylinders are numbered 1-2-3-4-5-6 in a single row from the front accessory/radiator end toward the flywheel and transmission.",scope:"Covers BMW N55 gasoline inline-six engines using the production crankshaft and DME strategy. Chassis packaging, N55 technical updates and the related S55 M engine require VIN-specific service information.",context:"BMW's Engine Technology training manual explicitly groups the N55 with its inline-six cylinder arrangement and lists firing order 1-5-3-6-2-4. The N55 training material also groups cylinders 1-3 and 4-6 into the twin-scroll exhaust channels, which is an exhaust-pulse arrangement rather than two cylinder banks.",caution:"BMW diagnostic screens may arrange smooth-running values or test steps differently from physical front-to-rear cylinder order. A fault for cylinder 5 refers to the fifth physical cylinder from the front, not the second event in the firing sequence.",source:source("BMW Engine Technology reference manual — cylinder arrangement and firing order", "https://bmwtechinfo.bmwgroup.com/tech_training_manual/ST501%20Engine%20Technology.pdf", "Primary BMW technical-training manual explicitly listing the N55 among inline-six engines with firing order 1-5-3-6-2-4 and cylinders 1 through 6 in one row.")},
  {slug:"bmw/b58/firing-order",keyword:"bmw b58 engine firing order diagram",make:"BMW",model:"B58B30M0 3.0L Inline-Six",title:"BMW B58 Engine Firing Order Diagram",order:"1-5-3-6-2-4",numbering:"Cylinders are numbered 1-2-3-4-5-6 in one row from the front/accessory-drive end toward the flywheel and transmission.",scope:"The application-specific evidence covers BMW's first-generation B58B30M0 in longitudinal installations. Later B58 technical updates, hybrid applications and S58 M engines must be identified by complete engine designation and VIN.",context:"BMW's G01 Powertrain technical training data lists firing order 1-5-3-6-2-4 for the B58B30M0. The B58 shares this mechanical order with the N55, but its closed-deck architecture, integrated charge-air cooling, fuel system and DME generation are different service systems.",caution:"Do not infer coil, injector or harness interchangeability from the shared firing order. Identify the exact B58 revision before parts replacement, coding or high-pressure-fuel work.",source:source("BMW G01 Powertrain technical training — B58B30M0 data", "https://studylib.net/doc/27964168/02-g01-powertrain", "BMW technical-training transcription listing the B58B30M0 firing order as 1-5-3-6-2-4 and distinguishing the engine's direct-injection and DME configuration.")},
  {slug:"volkswagen/2-0-tsi/firing-order",keyword:"vw 2.0 tsi firing order diagram",make:"Volkswagen",model:"2014 Golf/GTI 2.0L TSI CBFA/CCTA",title:"VW 2.0 TSI Firing Order Diagram",order:"1-3-4-2",numbering:"Cylinders are 1-2-3-4 from the timing-drive end toward the transmission on the covered CBFA/CCTA installation.",scope:"The exact specification is anchored to Volkswagen's January 2014 Golf/GTI data for CBFA and CCTA engines. Later EA888 generations and other 2.0L engine codes need their own component and repair procedures.",context:"Volkswagen's quick-reference specification explicitly lists the 1-3-4-2 ignition sequence for CBFA and CCTA, while engine-code identification separates these engines from other 2.0L applications.",caution:"Always capture the engine code before ordering coils, plugs, injectors or timing parts; a shared firing order does not establish parts interchangeability.",source:source("Volkswagen 2014 Golf/GTI Quick Reference Specification Book", "https://static.nhtsa.gov/odi/tsbs/2014/MC-10073690-2280.pdf", "Volkswagen-issued specification book identifying CBFA/CCTA and listing ignition sequence 1-3-4-2, plug gap 1.0–1.1 mm and plug torque 25 N·m.")},
];

export const editorialBatchSpecs:SpecRecord[]=[
  ...lugInputs.map(editorialLug),
  accordSpark,
  ...firingInputs.map(editorialFiring),
].map((record)=>({...record,reviewed}));
