import type { Diagram, Source, SpecRecord, SpecValue } from "./chevy350-content";
import { lugGuide, type Base } from "./extended-content";

const reviewed = "2026-08-14";
const lugSedan = "/features/shared-lug-sedan.png";
const lugSuv = "/features/shared-lug-suv.png";
const engineImage = "/features/shared-firing-engine.png";
const source = (label: string, url: string, note: string): Source => ({ label, url, note });

const S = {
  kia: source("Kia owner's manual library", "https://owners.kia.com/content/owners/en/manuals.html", "Select the exact model year and market before using a wheel specification."),
  mazda: source("Mazda owner's manual library", "https://www.mazdausa.com/static/manuals/", "Official Mazda model-year manual lookup."),
  vw: source("Volkswagen online owner's manuals", "https://www.vwserviceandparts.com/digital-resources/online-owners-manual/", "Official VIN-based Volkswagen manual lookup."),
  audi: source("Audi owner's manual library", "https://ownersmanual.audiusa.com/", "Official Audi VIN-based manual lookup."),
  bmw: source("BMW Driver's Guide", "https://www.bmwusa.com/owners-manuals.html", "Official BMW VIN-based owner information."),
  mercedes: source("Mercedes-Benz digital owner's manuals", "https://www.mbusa.com/en/owners/manuals", "Official Mercedes-Benz model and VIN manual lookup."),
  chevrolet: source("GM service information", "https://www.acdelcotds.com/subscriptions", "Official GM service-information access; match the engine RPO, fastener and model year."),
  ford: source("Ford service information", "https://www.motorcraftservice.com/", "Official Ford service-information access; match the engine code and model year."),
  mopar: source("Mopar service and owner information", "https://vehicleinfo.mopar.com/", "Official Stellantis vehicle-information lookup."),
  subaru: source("Subaru Technical Information System", "https://techinfo.subaru.com/stis/", "Official Subaru engine-code-specific service information."),
  toyota: source("Toyota Technical Information System", "https://techinfo.toyota.com/", "Official Toyota engine and model-year service information."),
};
const kiaSportage2022 = source("2022 Kia Sportage Owner's Manual — changing tires", "https://ownersmanual.kia.com/full_webhelp/NQ5SH/2022/en_GB/topics/chapter7_7_2.html", "Primary Kia procedure specifying 11–13 kgf·m (79–94 lbf·ft), every-other-nut tightening and matching metric chamfered hardware.");
const mazdaCx52021 = source("2021 Mazda CX-5 Owner's Manual — tire specifications", "https://www.mazdausa.com/static/manuals/2021/cx-5/contents/10020103.html", "Primary Mazda USA specifications listing 108–147 N·m (80–108 ft·lbf) for the 2021 CX-5.");
const mazda32020 = source("2020 Mazda3 Owner's Manual — mounting the spare tire", "https://owners-manual.mazda.com/gen/en/mazda3/mazda3_8jr5eo20e/contents/08020102.html", "Primary Mazda procedure listing 108–147 N·m (80–108 ft·lbf), clean mounting faces and dry wheel fasteners.");
const mazda62021 = source("2021 Mazda6 Owner's Manual — mounting the spare tire", "https://www.mazdausa.com/static/manuals/2021/mazda6/contents/08020300.html", "Primary Mazda USA procedure listing 108–147 N·m (80–108 ft·lbf), beveled-edge orientation and no oil or grease.");
const audiWheelSpecs2020 = source("Audi Wheel and Tire General Information — Edition 01.2020", "https://manuals.plus/m/3d2bec4a29eba6dfccb615e803842d339a5a5b7690fdd67260508729d51193f2", "Audi workshop reference table specifying 120 N·m for all A4 and A6 types and 140 N·m for all Q5 types, with a torque-wrench check for every bolt.");
const mercedesCClass2020 = source("2020 Mercedes-Benz C-Class Sedan Operator's Manual — changing a wheel", "https://www.mbusa.com/content/dam/mb-nafta/us/owners/manuals/2020/Operators/2020_C-Class_Sedan_OM.pdf", "Primary Mercedes-Benz USA procedure specifying a first diagonal pass no higher than 80 N·m, followed by a final diagonal pass at 130 N·m (96 lb-ft).");
const mercedesEClassCoupe2020 = source("2020 Mercedes-Benz E-Class Coupe Operator's Manual — changing a wheel", "https://www.mbusa.com/content/dam/mb-nafta/us/owners/manuals/2020/Operators/2020_E-Class_Coupe_OM.pdf", "Primary Mercedes-Benz USA procedure specifying a first diagonal pass no higher than 80 N·m, followed by a final diagonal pass at 150 N·m (111 lb-ft).");
const mercedesGlc2019 = source("2019 Mercedes-Benz GLC SUV Operator's Manual — lowering the vehicle", "https://www.mbusa.com/content/dam/mb-nafta/us/owners/manuals/2019/operators/2019_GLC_SUV_OM.pdf", "Primary Mercedes-Benz USA procedure specifying 150 N·m (111 lb-ft), a crosswise sequence and an immediate torque check after a wheel change.");

type LugJob = {
  slug: string; keyword: string; make: string; model: string; title: string;
  answer: string; scope: string; detail: string; values: SpecValue[]; source: Source; suv?: boolean;
};

const lugJobs: LugJob[] = [
  {slug:"kia/sportage/lug-nut-torque",keyword:"kia sportage lug nut torque spec",make:"Kia",model:"2022 Sportage",title:"2022 Kia Sportage Lug Nut Torque and Tightening Method",answer:"Kia specifies 79–94 lbf·ft (11–13 kgf·m, approximately 107–127 N·m) for the 2022 Sportage wheel lug nuts.",scope:"This exact permitted range comes from the 2022 Sportage tire-changing procedure. It applies to the original metric studs and matching chamfered nuts; aftermarket wheels or changed hardware require the wheel supplier's instructions.",detail:"Clean debris from the hub and wheel mating faces, place each nut by hand, lower the vehicle and tighten every other nut until all are secure. Use one repeatable setting within Kia's published range for every position rather than scattering final values across the range. Do not install a non-metric or mismatched-seat nut simply because it appears to thread onto the stud.",values:[{label:"Permitted torque range",value:"79–94 lbf·ft",note:"11–13 kgf·m; about 107–127 N·m"},{label:"Tightening order",value:"Every other nut",note:"Opposite-side/star sequence"},{label:"Hardware",value:"Metric, matching chamfer",note:"Reuse correct original style"},{label:"Final tool",value:"Calibrated torque wrench",note:"Do not finish by feel"}],source:kiaSportage2022,suv:true},
  {slug:"mazda/cx-5/lug-nut-torque",keyword:"mazda cx5 lug nut torque spec",make:"Mazda",model:"2021 CX-5",title:"2021 Mazda CX-5 Lug Nut Torque: Factory Range",answer:"Mazda specifies 80–108 ft·lbf (108–147 N·m) for the wheel lug nuts on the 2021 CX-5.",scope:"This exact range applies to the 2021 North American CX-5's factory wheel and stud arrangement, including the listed original 17- and 19-inch tire packages. Non-factory wheels may use different seat geometry or instructions.",detail:"Mazda publishes a range, but all five nuts on a wheel should receive the same selected final setting within it. Remove dirt from the wheel, hub and stud mounting areas, install the beveled side of each original nut toward the wheel, and do not put oil or grease on the threads or seats. Tighten in the illustrated crisscross order with a calibrated wrench.",values:[{label:"Factory torque range",value:"80–108 ft·lbf",note:"108–147 N·m"},{label:"Original tire packages",value:"17- and 19-inch",note:"Same manual torque row"},{label:"Nut orientation",value:"Beveled edge inward",note:"Factory conical seat"},{label:"Lubrication",value:"None",note:"Keep threads and seats dry"}],source:mazdaCx52021,suv:true},
  {slug:"mazda/mazda3/lug-nut-torque",keyword:"mazda 3 lug nut torque spec",make:"Mazda",model:"2020 Mazda3",title:"2020 Mazda3 Lug Nut Torque and Installation Order",answer:"Mazda specifies 80–108 ft·lbf (108–147 N·m) for the 2020 Mazda3 wheel lug nuts.",scope:"This exact range is from the 2020 Mazda3 owner procedure for its factory metric studs and wheels. Sedan and hatchback body style does not change that row, but aftermarket wheel hardware can.",detail:"Wipe dirt and grime from the hub, wheel mating face and studs. Start the original beveled nuts by hand, never oil or grease them, lower the car and tighten in the illustrated crisscross order. Choose one consistent value within the allowed range and apply it to every nut. An impact may seat the wheel provisionally, but the final pass belongs to a calibrated torque wrench.",values:[{label:"Factory torque range",value:"80–108 ft·lbf",note:"108–147 N·m"},{label:"Fastener type",value:"Metric conical-seat nut",note:"Match original configuration"},{label:"Mounting surfaces",value:"Clean",note:"Remove dirt and grime"},{label:"Final order",value:"Crisscross/star",note:"Same chosen torque at all positions"}],source:mazda32020},
  {slug:"mazda/mazda6/lug-nut-torque",keyword:"mazda 6 lug nut torque spec",make:"Mazda",model:"2021 Mazda6",title:"2021 Mazda6 Lug Nut Torque: 80–108 ft-lbf",answer:"Mazda specifies 80–108 ft·lbf (108–147 N·m) for the wheel lug nuts on the 2021 Mazda6.",scope:"This exact range applies to the 2021 U.S./Canada Mazda6 factory wheel hardware and covers the manual's original 17- and 19-inch tire rows. Accessory wheels with different nuts require their own instructions.",detail:"Clean the mounting surfaces and studs, point the beveled edge of each original nut inward, and thread every nut by hand before loading it. Mazda explicitly warns against oil or grease and against exceeding the range. Tighten across the wheel in stages, then use one chosen in-range value for the final calibrated pass at every position.",values:[{label:"Factory torque range",value:"80–108 ft·lbf",note:"108–147 N·m"},{label:"Original wheel rows",value:"17- and 19-inch",note:"Same factory fastener range"},{label:"Nut orientation",value:"Beveled edge inward",note:"Seat must match wheel"},{label:"Impact wrench",value:"Not for final torque",note:"Finish manually with calibrated wrench"}],source:mazda62021},
  {slug:"volkswagen/jetta/lug-bolt-torque",keyword:"volkswagen jetta lug nut torque spec",make:"Volkswagen",model:"Jetta",title:"Volkswagen Jetta Wheel Bolt Torque Specs",answer:"Most modern Volkswagen Jetta factory-wheel applications use 88 lb-ft (120 N-m).",scope:"Covers common Jetta applications using original ball-seat wheel bolts; older generations and aftermarket wheels must be checked separately.",detail:"The Jetta uses removable wheel bolts, not conventional lug nuts. Seat shape, shank length and thread engagement must match the wheel.",values:[{label:"Common modern setting",value:"88 lb-ft",note:"120 N-m"},{label:"Hardware",value:"Ball-seat wheel bolt",note:"Verify original wheel design"}],source:S.vw},
  {slug:"volkswagen/golf/lug-bolt-torque",keyword:"volkswagen golf lug nut torque spec",make:"Volkswagen",model:"Golf",title:"Volkswagen Golf Wheel Bolt Torque Specs",answer:"Most modern Volkswagen Golf factory wheels use 88 lb-ft (120 N-m).",scope:"Covers common Golf, Golf GTI and Golf R factory wheel-bolt applications; verify performance-model and accessory-wheel instructions.",detail:"Do not substitute cone-seat hardware for Volkswagen ball-seat bolts merely because the thread pitch matches.",values:[{label:"Common Golf setting",value:"88 lb-ft",note:"120 N-m"},{label:"Bolt seat",value:"Application-specific",note:"Usually OEM ball seat"}],source:S.vw},
  {slug:"volkswagen/passat/lug-bolt-torque",keyword:"volkswagen passat lug nut torque spec",make:"Volkswagen",model:"Passat",title:"Volkswagen Passat Wheel Bolt Torque Specs",answer:"A common Volkswagen Passat factory-wheel specification is 88 lb-ft (120 N-m).",scope:"Covers common North American Passat factory wheels and original wheel bolts; confirm the exact VIN manual.",detail:"Clean rust from the hub mounting face without lubricating bolt threads or the ball seats unless the exact manual explicitly permits it.",values:[{label:"Common setting",value:"88 lb-ft",note:"120 N-m"},{label:"Installation",value:"Opposite-side pattern",note:"Finish with a torque wrench"}],source:S.vw},
  {slug:"volkswagen/tiguan/lug-bolt-torque",keyword:"volkswagen tiguan lug nut torque spec",make:"Volkswagen",model:"Tiguan",title:"Volkswagen Tiguan Wheel Bolt Torque Specs",answer:"Many later Volkswagen Tiguan applications use 103 lb-ft (140 N-m); some earlier applications require confirmation before using that value.",scope:"Covers factory-wheel Tiguan applications, with the platform and model year treated as mandatory identifiers.",detail:"Do not borrow the 120 N-m passenger-car value automatically. Tiguan platform changes are why this generic query requires a year check.",values:[{label:"Common later-platform setting",value:"103 lb-ft",note:"140 N-m; verify model year"},{label:"Earlier platform",value:"Check VIN manual",note:"Do not infer from wheel diameter"}],source:S.vw,suv:true},
  {slug:"audi/a4/wheel-bolt-torque",keyword:"audi a4 lug nut torque spec",make:"Audi",model:"A4",title:"Audi A4 Wheel Bolt Torque: 120 N·m Factory Specification",answer:"Audi's January 2020 wheel-and-tire workshop table specifies 120 N·m (about 89 lb-ft) for all listed A4 types except the early RS 4 type 8D, which is separately listed at 140 N·m.",scope:"This is a wheel-bolt specification for the original Audi wheel and correct bolt. The historical type-8D RS 4 exception, accessory wheels, changed hardware and a later superseding instruction must be handled by their own documentation.",detail:"The A4 uses removable wheel bolts, not captive studs with lug nuts. Match thread, effective length and the wheel's seat geometry. Clean the hub and wheel mating faces, start every bolt by hand, snug diagonally while raised, then lower and finish each bolt with a calibrated torque wrench. Never use the 140-N·m Q5 value just because both vehicles wear Audi wheels.",values:[{label:"A4 all listed types",value:"120 N·m",note:"About 89 lb-ft"},{label:"RS 4 type 8D exception",value:"140 N·m",note:"About 103 lb-ft; separate early application"},{label:"Fastener",value:"Wheel bolt",note:"Correct seat and effective length required"},{label:"Final pattern",value:"Diagonal/crisscross",note:"Check every bolt with torque wrench"}],source:audiWheelSpecs2020},
  {slug:"audi/a6/wheel-bolt-torque",keyword:"audi a6 lug nut torque spec",make:"Audi",model:"A6",title:"Audi A6 Wheel Bolt Torque: 120 N·m for Standard Models",answer:"Audi's January 2020 wheel-and-tire reference specifies 120 N·m (about 89 lb-ft) for all listed A6 types. It separately lists 140 N·m for A6 PAX wheels and security versions, so those are not interchangeable rows.",scope:"Use 120 N·m only with a standard A6 factory wheel and its correct bolts. PAX, security, accessory, altered and special-purpose wheel systems require their own listed value and hardware.",detail:"Identify the wheel system before reaching for the wrench. A bolt can share the thread diameter yet have the wrong ball-seat radius or shank length. With clean, flush mounting faces, start the proper bolts by hand, tighten across the wheel in stages and make the final pass with a calibrated torque wrench. Recheck any replacement-wheel instructions that supersede the vehicle value.",values:[{label:"Standard A6, all listed types",value:"120 N·m",note:"About 89 lb-ft"},{label:"A6 PAX wheels",value:"140 N·m",note:"About 103 lb-ft; special wheel system"},{label:"A6 security model",value:"140 N·m",note:"Special application"},{label:"Hardware check",value:"Seat + length + thread",note:"All must match the wheel"}],source:audiWheelSpecs2020},
  {slug:"audi/q5/wheel-bolt-torque",keyword:"audi q5 lug nut torque spec",make:"Audi",model:"Q5",title:"Audi Q5 Wheel Bolt Torque: 140 N·m Factory Specification",answer:"Audi's January 2020 workshop table specifies 140 N·m (about 103 lb-ft) for all listed Q5 types.",scope:"The value applies to the Q5 row with factory-approved wheels and the correct original-style bolts. Accessory wheels, nonstandard bolts or a later model-specific instruction can supersede it; confirm the VIN guide when the hardware history is unknown.",detail:"Do not borrow the A4/A6 120-N·m figure—the Q5 is explicitly listed at 140 N·m. Remove loose corrosion from the hub and wheel mating surfaces, verify bolt seat and effective length, start bolts by hand and snug in a diagonal pattern. Lower the vehicle enough to prevent rotation, then check every bolt at the final setting with a calibrated wrench.",values:[{label:"Q5, all listed types",value:"140 N·m",note:"About 103 lb-ft"},{label:"A4/A6 comparison",value:"120 N·m",note:"Do not transfer passenger-car row"},{label:"Bolt selection",value:"Correct seat and length",note:"Torque cannot fix mismatched hardware"},{label:"Final verification",value:"Every bolt",note:"Calibrated torque wrench"}],source:audiWheelSpecs2020,suv:true},
  {slug:"bmw/3-series/wheel-bolt-torque",keyword:"bmw 3 series lug nut torque spec",make:"BMW",model:"3 Series",title:"BMW 3 Series Wheel Bolt Torque Specs",answer:"Later BMW 3 Series applications commonly use 103 lb-ft (140 N-m), while some older generations use 88 lb-ft (120 N-m).",scope:"Covers standard factory-wheel 3 Series applications; generation, chassis code and accessory-wheel instructions determine the row.",detail:"Identify the chassis before selecting 120 or 140 N-m. M models and nonstandard wheel hardware require model-specific data.",values:[{label:"Many later generations",value:"103 lb-ft",note:"140 N-m"},{label:"Some older generations",value:"88 lb-ft",note:"120 N-m; verify chassis"}],source:S.bmw},
  {slug:"bmw/5-series/wheel-bolt-torque",keyword:"bmw 5 series lug nut torque spec",make:"BMW",model:"5 Series",title:"BMW 5 Series Wheel Bolt Torque Specs",answer:"Many later BMW 5 Series applications use 103 lb-ft (140 N-m); older chassis may specify 88 lb-ft (120 N-m).",scope:"Covers standard 5 Series factory wheels; identify chassis, model year, M/non-M application and wheel package.",detail:"Use the VIN-based Driver's Guide because the model name spans both 120 and 140 N-m eras.",values:[{label:"Common later setting",value:"103 lb-ft",note:"140 N-m"},{label:"Older chassis",value:"88 lb-ft possible",note:"Confirm before service"}],source:S.bmw},
  {slug:"bmw/x5/wheel-bolt-torque",keyword:"bmw x5 lug nut torque spec",make:"BMW",model:"X5",title:"BMW X5 Wheel Bolt Torque Specs by Chassis",answer:"Many BMW X5 factory-wheel applications use 103 lb-ft (140 N-m), subject to chassis and wheel-package confirmation.",scope:"Covers common X5 factory wheels; X5 M, accessory wheels and nonstandard bolts can carry separate instructions.",detail:"Large wheel diameter does not by itself change the setting. Bolt design, hub and approved wheel package determine the specification.",values:[{label:"Common X5 setting",value:"103 lb-ft",note:"140 N-m"},{label:"X5 M/accessory",value:"Verify separately",note:"Use VIN and wheel instructions"}],source:S.bmw,suv:true},
  {slug:"mercedes-benz/c-class/wheel-bolt-torque",keyword:"mercedes c class lug nut torque spec",make:"Mercedes-Benz",model:"2020 C-Class Sedan",title:"2020 Mercedes C-Class Wheel Bolt Torque: 130 N·m",answer:"The 2020 Mercedes-Benz C-Class Sedan operator's manual specifies a final wheel-bolt torque of 130 N·m (96 lb-ft). It directs a preliminary diagonal pass at no more than 80 N·m before the final pass.",scope:"This exact two-stage procedure applies to the standard 2020 U.S.-market C-Class Sedan manual. AMG vehicles, another body style or model year, accessory wheels and changed fasteners must follow their own operator's manual or approved-wheel instructions.",detail:"Use approved wheel bolts with the correct seat and effective length, keep the threads free of oil and grease, and start each bolt by hand. With the vehicle on the ground, tighten positions 1 through 5 diagonally to no more than 80 N·m, then repeat the same order at 130 N·m. Check tire pressure and restart the applicable pressure-loss or TPMS procedure after installation.",values:[{label:"Final wheel-bolt torque",value:"130 N·m",note:"96 lb-ft"},{label:"Preliminary diagonal pass",value:"Maximum 80 N·m",note:"59 lb-ft"},{label:"Final order",value:"1–5 diagonal pattern",note:"Repeat at full torque"},{label:"Thread treatment",value:"No oil or grease",note:"Use approved undamaged bolts"}],source:mercedesCClass2020},
  {slug:"mercedes-benz/e-class/wheel-bolt-torque",keyword:"mercedes e class lug nut torque spec",make:"Mercedes-Benz",model:"2020 E-Class Coupe",title:"2020 Mercedes E-Class Coupe Wheel Bolt Torque: 150 N·m",answer:"The 2020 Mercedes-Benz E-Class Coupe operator's manual specifies 150 N·m (111 lb-ft) for the final wheel-bolt pass—not the 130 N·m commonly quoted for some other Mercedes passenger cars.",scope:"This exact value and method are for the U.S.-market 2020 E-Class Coupe manual. Sedan, wagon, cabriolet, AMG, accessory-wheel and other model-year applications require their corresponding document; the E-Class name alone is not enough.",detail:"Use only approved bolts that match the wheel. Keep bolt and hub threads clean and dry, start them by hand, and lower the vehicle before final tightening. Mercedes specifies a diagonal 1–5 pass capped at 80 N·m, followed by the same diagonal order at 150 N·m. Adjust tire pressure and restart the relevant monitoring system afterward.",values:[{label:"Final wheel-bolt torque",value:"150 N·m",note:"111 lb-ft"},{label:"Preliminary diagonal pass",value:"Maximum 80 N·m",note:"59 lb-ft"},{label:"Tightening sequence",value:"1–5 diagonal",note:"Vehicle supported on ground for final torque"},{label:"C-Class comparison",value:"Do not substitute 130 N·m",note:"Model/body procedure differs"}],source:mercedesEClassCoupe2020},
  {slug:"mercedes-benz/glc/wheel-bolt-torque",keyword:"mercedes glc lug nut torque spec",make:"Mercedes-Benz",model:"2019 GLC SUV",title:"2019 Mercedes GLC Wheel Bolt Torque: 150 N·m",answer:"Mercedes-Benz specifies 150 N·m (111 lb-ft) for the 2019 GLC SUV wheel bolts. The operator's manual calls for an even crosswise sequence and an immediate torque check after a wheel change.",scope:"This exact figure comes from the U.S. 2019 GLC SUV operator's manual. It should not be transferred automatically to a later redesigned GLC, an AMG supplement, a coupe, an accessory wheel or non-original fasteners.",detail:"Lower the vehicle until it stands firmly on the ground, then tighten all five approved wheel bolts evenly in the illustrated crosswise order at 150 N·m. Check the newly installed tire's pressure and correct it if needed. If bolt threads, hub threads or seating surfaces are damaged, stop and have them repaired; extra torque cannot make mismatched or damaged hardware safe.",values:[{label:"Final wheel-bolt torque",value:"150 N·m",note:"111 lb-ft"},{label:"Tightening order",value:"Crosswise",note:"Five-bolt illustrated sequence"},{label:"After wheel change",value:"Immediate torque check",note:"Manual safety instruction"},{label:"After installation",value:"Check tire pressure",note:"Restart monitoring when applicable"}],source:mercedesGlc2019,suv:true},
];

function lugPage(j: LugJob): SpecRecord {
  const base: Base = {slug:j.slug,keyword:j.keyword,make:j.make,model:j.model,category:"Torque Specs",title:j.title,
    metaDescription:`${j.title} with year and generation cautions, dry-thread guidance, tightening pattern, recheck procedure and official manual lookup.`,
    answer:j.answer,scope:j.scope,detail:j.detail,values:j.values,sources:[j.source],identity:j.model,
    distinctions:[j.scope,j.detail],featureImage:j.suv?lugSuv:lugSedan,featureOverlay:true};
  return lugGuide(base);
}

type TorqueJob = {slug:string;keyword:string;make:string;model:string;title:string;answer:string;scope:string;detail:string;values:SpecValue[];source:Source;diagram?:Diagram["type"]};

const torqueJobs: TorqueJob[] = [
  {slug:"ford/302/head-bolt-torque-sequence",keyword:"ford 302 head bolt torque sequence",make:"Ford",model:"302 Small-Block V8",title:"Ford 302 Head Bolt Torque Sequence and Application Guide",answer:"Ford 302 head tightening commonly uses a center-out sequence and staged torque, but the final value varies with model year, head material, bolt length, lubricant and aftermarket fastener instructions.",scope:"Covers planning for traditional 221/260/289/302-family head service, not a substitute for the exact block, head, gasket and fastener procedure.",detail:"Early production combinations are often published near 65-70 lb-ft with specified thread treatment; later or aftermarket combinations can differ substantially.",values:[{label:"Sequence",value:"Center outward",note:"Alternate across the deck"},{label:"Common stock reference",value:"About 65-70 lb-ft",note:"Verify application and lubricant"},{label:"Aftermarket studs",value:"Use fastener maker data",note:"Do not reuse factory number"}],source:S.ford,diagram:"head"},
  {slug:"ford/351-windsor/head-bolt-torque-sequence",keyword:"ford 351 windsor head bolt torque sequence",make:"Ford",model:"351 Windsor V8",title:"Ford 351 Windsor Head Bolt Torque Sequence Guide",answer:"The 351 Windsor uses a center-out head-bolt pattern, but deck height, bolt position, production year, cylinder head and fastener kit determine the numerical stages.",scope:"Covers Windsor-family 351W assembly identification; Cleveland and Modified engines are not interchangeable applications.",detail:"Common stock references use higher final values than many 302 combinations. Long and short bolts and any water-jacket sealant must be handled exactly as the matched service data states.",values:[{label:"Pattern",value:"Center outward",note:"Staged, alternating passes"},{label:"Common stock reference",value:"About 95-105 lb-ft",note:"Position and application dependent"},{label:"Critical identification",value:"351W, not 351C/351M",note:"Different engines"}],source:S.ford,diagram:"head"},
  {slug:"chevrolet/5-3/head-bolt-torque-sequence",keyword:"chevy 5.3 head bolt torque sequence",make:"Chevrolet",model:"5.3L V8",title:"Chevy 5.3 Head Bolt Torque Sequence by Engine Generation",answer:"Chevrolet 5.3L engines use a staged torque-plus-angle head procedure, but Gen III, Gen IV and Gen V engines do not share one universal stage chart.",scope:"Covers LS/Vortec and EcoTec3 5.3L identification; the VIN engine code, RPO, bolt type, block and head casting are mandatory.",detail:"Main M11/M12 bolts and smaller upper bolts are tightened in separate groups. New torque-to-yield bolts and an angle gauge are commonly required.",values:[{label:"Procedure type",value:"Torque plus angle",note:"Generation-specific stages"},{label:"Bolt groups",value:"Main and small bolts",note:"Separate values and patterns"},{label:"Bolt reuse",value:"Usually replace TTY bolts",note:"Follow exact service data"}],source:S.chevrolet,diagram:"head"},
  {slug:"chevrolet/350/rocker-arm-torque",keyword:"chevy 350 rocker arm torque specs",make:"Chevrolet",model:"350 Small-Block V8",title:"Chevy 350 Rocker Arm Torque Specs: Adjustable vs. Pedestal",answer:"Most traditional Chevy 350 stud-mounted rocker arms are adjusted for valve lash or hydraulic preload, not tightened to a universal final torque.",scope:"Covers Gen I small-block valvetrains; self-aligning rockers, pedestal conversions, screw-in studs and aftermarket poly-locks require their own method.",detail:"For a hydraulic lifter, remove lash at the correct cam position and add the specified preload turn. A nonadjustable pedestal system uses a true bolt torque and must not be treated like a rocker nut.",values:[{label:"Traditional stud rocker",value:"Adjust preload, not final torque",note:"Zero lash plus specified turn"},{label:"Solid lifter",value:"Set hot/cold lash",note:"Cam card controls"},{label:"Pedestal conversion",value:"Kit-specific torque",note:"Verify hardware"}],source:S.chevrolet,diagram:"valve"},
  {slug:"chevrolet/350/flywheel-bolt-torque",keyword:"chevy 350 flywheel torque specs",make:"Chevrolet",model:"350 Small-Block V8",title:"Chevy 350 Flywheel Bolt Torque Specs and Installation Checks",answer:"A commonly cited Chevy small-block manual-transmission flywheel-bolt value is about 60 lb-ft, but bolt grade, crankshaft flange, threadlocker and flywheel instructions must be matched.",scope:"Covers common Gen I 350 crankshaft and manual flywheel combinations; one-piece and two-piece rear-main-seal parts are not automatically interchangeable.",detail:"Use the correct length bolts, clean the crank and flywheel mating faces, apply only the specified thread treatment and tighten gradually in a crisscross pattern.",values:[{label:"Common stock reference",value:"60 lb-ft",note:"Verify bolt and flywheel instructions"},{label:"Pattern",value:"Crisscross in stages",note:"Seat flywheel evenly"},{label:"Aftermarket fasteners",value:"Manufacturer value",note:"Lubricant changes torque"}],source:S.chevrolet,diagram:"main"},
  {slug:"chevrolet/350/flexplate-bolt-torque",keyword:"chevy 350 flexplate torque specs",make:"Chevrolet",model:"350 Small-Block V8",title:"Chevy 350 Flexplate Bolt Torque Specs and Orientation",answer:"A common stock Chevy 350 flexplate-to-crank bolt reference is about 60 lb-ft, subject to the exact crank, fastener and flexplate instructions.",scope:"Covers common Gen I automatic-transmission flexplate installations; rear-main-seal design, balance weight and converter pattern must be identified.",detail:"Flexplate orientation and engine balance are as important as torque. Confirm the chamfer, offset and weight position before tightening new or approved bolts.",values:[{label:"Common crank-bolt reference",value:"60 lb-ft",note:"Verify exact hardware"},{label:"Converter bolts",value:"Separate specification",note:"Do not use crank-bolt value"},{label:"Orientation",value:"Application-specific",note:"Check balance and offset"}],source:S.chevrolet,diagram:"main"},
  {slug:"chevrolet/350/harmonic-balancer-bolt-torque",keyword:"chevy 350 harmonic balancer torque spec",make:"Chevrolet",model:"350 Small-Block V8",title:"Chevy 350 Harmonic Balancer Bolt Torque Spec and Installation",answer:"Many production Chevy 350 applications use about 60 lb-ft for the crankshaft balancer retaining bolt, but crate-engine and aftermarket damper instructions can differ.",scope:"Covers common threaded-snout Gen I small-block crankshafts; early press-fit-only arrangements and aftermarket crank hardware require separate procedures.",detail:"Install the damper with a proper installer. Never pull it onto the crank by using the retaining bolt as an installation tool.",values:[{label:"Common retaining-bolt reference",value:"60 lb-ft",note:"Verify engine and bolt"},{label:"Damper installation",value:"Use installer tool",note:"Do not hammer or draw with bolt"},{label:"Aftermarket damper",value:"Maker instructions control",note:"Check washer and thread treatment"}],source:S.chevrolet,diagram:"timing"},
  {slug:"ford/302/intake-manifold-torque",keyword:"ford 302 intake manifold torque specs",make:"Ford",model:"302 Small-Block V8",title:"Ford 302 Intake Manifold Torque Specs and Sequence",answer:"Traditional Ford 302 intake manifolds are tightened from the center outward in stages; common cast-iron references are around 23-25 lb-ft, while aluminum manifold instructions may differ.",scope:"Covers Windsor-family 289/302 intake installation; EFI lower intakes, aftermarket heads and manifold-specific gaskets require their own chart.",detail:"Use sealant at the specified coolant and end-rail locations, align the manifold without disturbing the gaskets, and retorque only if the component instructions call for it.",values:[{label:"Common cast-iron reference",value:"23-25 lb-ft",note:"Verify year and manifold"},{label:"Aluminum aftermarket",value:"Manufacturer value",note:"Often lower or staged differently"},{label:"Pattern",value:"Center outward",note:"Alternate side to side"}],source:S.ford,diagram:"intake"},
  {slug:"ford/302/rocker-arm-torque",keyword:"ford 302 rocker arm torque specs",make:"Ford",model:"302 Small-Block V8",title:"Ford 302 Rocker Arm Torque Specs and Adjustment Types",answer:"A Ford 302 rocker specification depends on whether the engine has rail, pedestal, stud-adjustable or aftermarket roller rockers; there is no universal rocker-nut torque.",scope:"Covers common Windsor 302 valvetrain identification; camshaft, lifter, head and rocker conversion parts can change the procedure.",detail:"Pedestal bolts use a specified torque within an acceptable lifter-preload range. Stud-mounted adjustable rockers are set by lash or preload instead.",values:[{label:"Pedestal rocker",value:"Torque plus preload check",note:"Year and hardware specific"},{label:"Adjustable stud rocker",value:"Set lash/preload",note:"Not a universal torque"},{label:"Aftermarket roller",value:"Kit instructions",note:"Geometry must be checked"}],source:S.ford,diagram:"valve"},
  {slug:"ford/351-windsor/intake-manifold-torque",keyword:"ford 351 windsor intake manifold torque specs",make:"Ford",model:"351 Windsor V8",title:"Ford 351 Windsor Intake Manifold Torque Specs",answer:"A common 351 Windsor intake-manifold reference is approximately 23-25 lb-ft with a center-out staged pattern, but manifold material and manufacturer instructions control.",scope:"Covers traditional 351W intake installation; 351 Cleveland, 351M/400 and EFI-specific parts use different designs.",detail:"The 351W's wider deck means a 302 intake is not interchangeable. Dry-fit the correct manifold and verify gasket alignment before sealant and torque.",values:[{label:"Common stock reference",value:"23-25 lb-ft",note:"Verify manifold and gasket"},{label:"Pattern",value:"Center outward",note:"Several even stages"},{label:"Aftermarket aluminum",value:"Maker instructions",note:"May specify lower torque"}],source:S.ford,diagram:"intake"},
  {slug:"chevrolet/ls1/head-bolt-torque-sequence",keyword:"chevy ls1 head bolt torque sequence",make:"Chevrolet",model:"LS1 5.7L V8",title:"Chevy LS1 Head Bolt Torque Sequence and Stages",answer:"The LS1 uses torque-to-yield head bolts tightened in a center-out sequence with initial torque and angle stages; exact stages depend on bolt position and service revision.",scope:"Covers production LS1 identification, not every LS-family block or aftermarket head/stud package.",detail:"Long main bolts and shorter upper bolts are separate groups. Replace TTY bolts where required, clean blind holes and use an accurate angle gauge.",values:[{label:"Main bolts",value:"Torque plus angle stages",note:"Follow exact LS1 sequence"},{label:"Short upper bolts",value:"Separate stage",note:"Do not apply main-bolt angles"},{label:"Aftermarket studs",value:"Stud maker procedure",note:"Factory TTY chart does not apply"}],source:S.chevrolet,diagram:"head"},
  {slug:"chevrolet/ls1/intake-manifold-torque",keyword:"chevy ls1 intake manifold torque specs",make:"Chevrolet",model:"LS1 5.7L V8",title:"Chevy LS1 Intake Manifold Torque Specs and Sequence",answer:"Many LS1 composite intake procedures use a light first pass near 44 in-lb followed by a final pass near 89 in-lb, in the specified center-out order.",scope:"Covers common production LS1 composite intake manifolds; LS6, truck, aftermarket and modified combinations must be verified.",detail:"These are inch-pound values, not foot-pounds. Inspect O-ring seals, keep ports clean and avoid sealant unless the exact manifold procedure calls for it.",values:[{label:"Common first pass",value:"44 in-lb",note:"5 N-m"},{label:"Common final pass",value:"89 in-lb",note:"10 N-m"},{label:"Unit warning",value:"Inch-pounds",note:"Do not confuse with ft-lb"}],source:S.chevrolet,diagram:"intake"},
  {slug:"chevrolet/454/intake-manifold-torque",keyword:"chevy 454 intake manifold torque specs",make:"Chevrolet",model:"454 Big-Block V8",title:"Chevy 454 Intake Manifold Torque Specs and Sequence",answer:"A common stock big-block Chevrolet intake-manifold reference is about 25 lb-ft, applied gradually from the center outward; aftermarket aluminum components may specify another value.",scope:"Covers common Mark IV-style 454 intake installation; Gen V/VI, tall-deck, rectangular/oval-port and aftermarket combinations require matching parts and instructions.",detail:"Confirm port shape, coolant passages, distributor clearance and gasket style before torque. Recheck only when the gasket or manifold manufacturer instructs it.",values:[{label:"Common stock reference",value:"25 lb-ft",note:"Verify engine and manifold"},{label:"Pattern",value:"Center outward",note:"Alternate banks"},{label:"Aftermarket",value:"Manufacturer chart",note:"Material and washers matter"}],source:S.chevrolet,diagram:"intake"},
  {slug:"ford/4-6/head-bolt-torque-sequence",keyword:"ford 4.6 head bolt torque sequence",make:"Ford",model:"4.6L Modular V8",title:"Ford 4.6 Head Bolt Torque Sequence by Engine Version",answer:"Ford 4.6L Modular engines use staged torque-and-angle cylinder-head procedures, but 2-valve, 3-valve and 4-valve versions do not share one universal chart.",scope:"Covers 4.6L Modular engine identification; model year, VIN, head casting, bolt design and service manual are mandatory.",detail:"Main bolts and smaller front fasteners may have separate sequences. Use new bolts where specified and do not mix Romeo, Windsor or performance-engine procedures.",values:[{label:"Procedure",value:"Torque plus angle",note:"Version-specific"},{label:"Engine type",value:"2V, 3V or 4V",note:"Identify before assembly"},{label:"Bolts",value:"Replace if specified",note:"Check TTY rules"}],source:S.ford,diagram:"head"},
  {slug:"ford/5-4-triton/head-bolt-torque-sequence",keyword:"ford 5.4 triton head bolt torque sequence",make:"Ford",model:"5.4L Triton V8",title:"Ford 5.4 Triton Head Bolt Torque Sequence Guide",answer:"The Ford 5.4 Triton uses a staged torque-and-angle head-bolt procedure that varies between 2-valve, 3-valve and 4-valve applications.",scope:"Covers 5.4L Modular/Triton identification; the exact VIN, head, block and bolt service procedure must be used.",detail:"Do not reuse a 4.6L chart simply because the engines look related. Clean bolt holes, check deck flatness and keep the angle stages tied to the exact engine version.",values:[{label:"Procedure",value:"Torque plus angle",note:"Exact stages vary"},{label:"Required identity",value:"2V, 3V or 4V",note:"Also verify model year"},{label:"Sequence",value:"Center outward",note:"Use factory diagram"}],source:S.ford,diagram:"head"},
  {slug:"chevrolet/5-3/intake-manifold-torque",keyword:"chevy 5.3 intake manifold torque specs",make:"Chevrolet",model:"5.3L V8",title:"Chevy 5.3 Intake Manifold Torque Specs by Generation",answer:"Many Gen III/IV 5.3L composite intake manifolds use approximately 44 in-lb followed by 89 in-lb, but Gen V EcoTec3 and aftermarket procedures must be checked separately.",scope:"Covers common LS-based 4.8/5.3/6.0-style composite intake practice; engine RPO and manifold part number determine applicability.",detail:"Use inch-pounds, follow the specified sequence and inspect reusable seals. A vacuum leak from pinched seals cannot be corrected safely by overtorquing the composite manifold.",values:[{label:"Common initial pass",value:"44 in-lb",note:"5 N-m"},{label:"Common final pass",value:"89 in-lb",note:"10 N-m"},{label:"Gen V/aftermarket",value:"Verify separately",note:"Do not assume LS chart"}],source:S.chevrolet,diagram:"intake"},
  {slug:"dodge/5-7-hemi/intake-manifold-torque",keyword:"dodge 5.7 hemi intake manifold torque specs",make:"Dodge",model:"5.7L HEMI V8",title:"Dodge 5.7 HEMI Intake Manifold Torque Specs",answer:"The 5.7 HEMI composite intake uses a low inch-pound staged tightening procedure; the exact value and pattern vary by manifold generation and vehicle application.",scope:"Covers general 5.7L HEMI intake service planning; car, truck, MDS, active-runner and aftermarket manifolds require the matched procedure.",detail:"Do not convert a remembered inch-pound value into foot-pounds. Inspect seals, runner controls, harness routing and PCV connections before tightening.",values:[{label:"Torque scale",value:"Low inch-pound range",note:"Use exact Mopar chart"},{label:"Pattern",value:"Staged center-out",note:"Seat composite manifold evenly"},{label:"Aftermarket manifold",value:"Maker instructions",note:"May use different fasteners"}],source:S.mopar,diagram:"intake"},
  {slug:"subaru/ej25/intake-manifold-torque",keyword:"subaru ej25 intake manifold torque specs",make:"Subaru",model:"EJ25 Boxer",title:"Subaru EJ25 Intake Manifold Torque Specs by Engine Code",answer:"EJ25 intake-manifold torque depends on SOHC, DOHC, turbo/non-turbo configuration and model year; a commonly encountered final range is roughly 13-18 lb-ft, but engine-specific service data controls.",scope:"Covers EJ25 intake installation planning; identify the full engine code and manifold before choosing a value.",detail:"Subaru boxer layouts use separate runners and seals at each head. Align the assembly without pinching gaskets, and distinguish manifold bolts from smaller sensor and bracket fasteners.",values:[{label:"Common service range",value:"About 13-18 lb-ft",note:"Engine-code dependent"},{label:"Turbo variants",value:"Verify separately",note:"Different manifold and plumbing"},{label:"Pattern",value:"Even staged passes",note:"Avoid seal displacement"}],source:S.subaru,diagram:"intake"},
  {slug:"toyota/22r/head-bolt-torque",keyword:"toyota 22r head bolt torque spec",make:"Toyota",model:"22R/22RE I4",title:"Toyota 22R Head Bolt Torque Specs and Sequence",answer:"Toyota 22R/22RE head procedures vary by production year, bolt design and gasket; commonly cited early service values are near 58 lb-ft, while later procedures may use revised stages.",scope:"Covers 22R and 22RE identification only; year, cylinder-head casting, gasket and bolt instructions must be matched.",detail:"Use the factory center-out sequence in gradual passes, verify the timing-chain cover joint and follow the selected gasket maker's retorque guidance.",values:[{label:"Common early reference",value:"About 58 lb-ft",note:"Verify exact year"},{label:"Pattern",value:"Center outward",note:"Staged passes"},{label:"Later/replacement parts",value:"Matched instructions",note:"Do not assume early value"}],source:S.toyota,diagram:"head"},
  {slug:"jeep/4-0/head-bolt-torque",keyword:"jeep 4.0 head bolt torque spec",make:"Jeep",model:"4.0L Inline-Six",title:"Jeep 4.0 Head Bolt Torque Specs and Sequence",answer:"Many Jeep 4.0L procedures finish the main head bolts near 110 lb-ft, with bolt 11 commonly treated separately near 100 lb-ft and sealed because it enters a coolant passage; exact year data controls.",scope:"Covers common AMC/Jeep 4.0L inline-six applications; Renix, HO and casting changes require model-year verification.",detail:"Mark the coolant-passage bolt, use the specified sealant and follow every staged center-out pass. Do not apply the reduced value to the other positions.",values:[{label:"Common main-bolt final",value:"110 lb-ft",note:"Verify model year"},{label:"Common bolt 11 final",value:"100 lb-ft",note:"Sealant typically required"},{label:"Pattern",value:"Center outward",note:"Several staged passes"}],source:S.mopar,diagram:"head"},
  {slug:"ford/300-inline-6/head-bolt-torque",keyword:"ford 300 inline 6 head bolt torque spec",make:"Ford",model:"300 Inline-Six",title:"Ford 300 Inline-6 Head Bolt Torque Specs and Sequence",answer:"Ford 300 inline-six head-bolt values vary by year and fastener set; common stock references are generally in the 70-85 lb-ft range with a staged center-out sequence.",scope:"Covers the Ford 4.9L/300 truck inline-six; earlier 240 parts, replacement heads, studs and gasket instructions must be identified.",detail:"The long iron head makes even staged tightening and flatness checks especially important. Use the exact year chart instead of selecting the top of a generic range.",values:[{label:"Common stock range",value:"About 70-85 lb-ft",note:"Year and bolt dependent"},{label:"Pattern",value:"Center outward",note:"Progressive passes"},{label:"Aftermarket studs",value:"Fastener maker chart",note:"Lubricant-specific"}],source:S.ford,diagram:"head"},
];

function torquePage(j: TorqueJob): SpecRecord {
  const diagramType = j.diagram ?? "head";
  return {slug:j.slug,keyword:j.keyword,make:j.make,model:j.model,category:"Torque Specs",title:j.title,
    metaDescription:`${j.title} with application boundaries, staged installation guidance, fastener cautions and official service-information source.`,
    answer:j.answer,scope:j.scope,detail:j.detail,values:j.values,sources:[j.source],reviewed,featureImage:engineImage,featureOverlay:true,
    diagram:{type:diagramType,title:`Interactive ${j.model} ${diagramType} service map`,caption:"Use the numbered map as an orientation aid only. The application-specific service diagram controls the actual bolt positions and stages.",points:j.diagram==="intake"?["1","5","3","7","9","10","8","4","6","2"]:["1","5","9","7","3","4","8","10","6","2"]},
    intro:[j.answer,j.scope],
    steps:["Identify the engine code, model year, casting, gasket and exact fastener kit before disassembly.","Clean and inspect threads, bolt holes and mating faces using the component manufacturer's limits.","Follow the exact staged pattern with the specified lubricant or sealant; record torque and angle completion."],
    sections:[{heading:`Why ${j.model} identification changes the specification`,paragraphs:[j.scope,j.detail]},{heading:"Assembly controls that prevent false torque",bullets:["Use the specified thread condition and lubricant.","Separate main bolts from small or special-position fasteners.","Use an angle gauge where torque-to-yield stages are specified.","Stop if a fastener reaches the setting before the joint seats normally."]}],
    faqs:[{q:`What is the ${j.keyword}?`,a:j.answer},{q:"Can the bolts or studs be reused?",a:"Only when the exact service procedure and fastener manufacturer allow reuse. Torque-to-yield bolts are commonly replaced."},{q:"Does an aftermarket fastener use the factory torque?",a:"Not automatically. Use the fastener maker's value, lubricant and tightening sequence for that exact kit."}]};
}

type FiringJob={slug:string;keyword:string;make:string;model:string;title:string;order:string;numbering:string;scope:string;detail:string;source:Source};
const firingJobs:FiringJob[]=[
  {slug:"toyota/22r/firing-order",keyword:"toyota 22r firing order",make:"Toyota",model:"22R/22RE I4",title:"Toyota 22R Firing Order and Distributor Diagram",order:"1-3-4-2",numbering:"Cylinders 1-2-3-4 run from the timing-chain/front end toward the transmission.",scope:"Covers production Toyota 22R and 22RE inline-four engines with distributor ignition.",detail:"The distributor rotor turns clockwise on common applications; establish compression TDC for cylinder 1 before assigning the first tower.",source:S.toyota},
  {slug:"jeep/4-0/firing-order",keyword:"jeep 4.0 firing order",make:"Jeep",model:"4.0L Inline-Six",title:"Jeep 4.0 Firing Order and Cylinder Numbering",order:"1-5-3-6-2-4",numbering:"Cylinders are numbered 1 through 6 from the radiator/front end toward the transmission.",scope:"Covers common AMC/Jeep 4.0L inline-six engines; distributor indexing and coil-rail diagnostics differ by model year.",detail:"Early engines use distributor routing; later engines use a coil rail. The mechanical firing order stays the same, but the service method changes.",source:S.mopar},
  {slug:"ford/300-inline-6/firing-order",keyword:"ford 300 inline 6 firing order",make:"Ford",model:"300 Inline-Six",title:"Ford 300 Inline-6 Firing Order and Distributor Diagram",order:"1-5-3-6-2-4",numbering:"Cylinders 1 through 6 are numbered from the radiator/front of the engine toward the flywheel.",scope:"Covers the Ford 4.9L/300 inline-six; verify distributor rotation and emission-era ignition hardware for the exact year.",detail:"Set cylinder 1 at compression TDC before clocking the distributor, then route one wire at a time to avoid mirror-image errors.",source:S.ford},
  {slug:"chevrolet/250-inline-6/firing-order",keyword:"chevy 250 inline 6 firing order",make:"Chevrolet",model:"250 Inline-Six",title:"Chevy 250 Inline-6 Firing Order and Distributor Diagram",order:"1-5-3-6-2-4",numbering:"Cylinders are numbered 1 through 6 from the front/radiator end to the transmission.",scope:"Covers common Chevrolet 250 inline-six distributor applications.",detail:"The distributor commonly rotates clockwise, but confirm the specific installation and compression TDC before assigning cap towers.",source:S.chevrolet},
  {slug:"chevrolet/292-inline-6/firing-order",keyword:"chevy 292 inline 6 firing order",make:"Chevrolet",model:"292 Inline-Six",title:"Chevy 292 Inline-6 Firing Order and Cylinder Numbering",order:"1-5-3-6-2-4",numbering:"Cylinders 1-2-3-4-5-6 run from the radiator/front toward the transmission.",scope:"Covers common Chevrolet 292 truck inline-six engines using distributor ignition.",detail:"The 292 shares the familiar GM inline-six order, but its taller block and component locations should not be confused with a 250 during parts identification.",source:S.chevrolet},
  {slug:"ford/290/firing-order",keyword:"ford 290 firing order",make:"Ford",model:"290 Search Correction",title:"Ford 290 Firing Order: Identify the Engine Before Routing Wires",order:"No recognized Ford production 290 order",numbering:"The query commonly refers to a Ford 289 V8, an AMC 290 V8, or a mistyped engine badge.",scope:"This is an identification page, not permission to apply a guessed firing order.",detail:"A Ford 289 commonly uses 1-5-4-2-6-3-7-8, while an AMC 290 is a different engine family. Verify casting numbers and manufacturer first.",source:S.ford},
  {slug:"dodge/318/firing-order",keyword:"dodge 318 firing order",make:"Dodge",model:"318 LA V8",title:"Dodge 318 Firing Order and Distributor Diagram",order:"1-8-4-3-6-5-7-2",numbering:"Driver-side bank is 1-3-5-7 and passenger-side bank is 2-4-6-8, front to rear on common LA applications.",scope:"Covers common Chrysler/Dodge LA 318 distributor engines; later Magnum ignition hardware should be verified by year.",detail:"Distributor rotation is commonly clockwise. Establish cylinder 1 compression TDC before choosing the first cap terminal.",source:S.mopar},
  {slug:"dodge/360/firing-order",keyword:"dodge 360 firing order",make:"Dodge",model:"360 LA/Magnum V8",title:"Dodge 360 Firing Order and Cylinder Numbering",order:"1-8-4-3-6-5-7-2",numbering:"Driver-side bank is 1-3-5-7 and passenger-side bank is 2-4-6-8, front to rear on common Chrysler small-block layouts.",scope:"Covers common LA 360 and related Magnum 5.9L mechanical firing order; ignition components and timing procedures vary by generation.",detail:"Do not diagnose a Magnum coil or PCM circuit from an older carbureted distributor diagram even though the combustion order matches.",source:S.mopar},
];

function firingPage(j:FiringJob):SpecRecord{
  return {slug:j.slug,keyword:j.keyword,make:j.make,model:j.model,category:"Firing Order",title:j.title,
    metaDescription:`${j.title}: ${j.order}, cylinder numbering, compression-TDC setup, routing cautions and official service-information lookup.`,
    answer:j.order.startsWith("No recognized")?`${j.order}. ${j.numbering}`:`The ${j.model} firing order is ${j.order}. ${j.numbering}`,
    scope:j.scope,detail:j.detail,values:[{label:"Firing order",value:j.order,note:"Confirm engine identity"},{label:"Cylinder numbering",value:j.numbering,note:"Orient from the engine front"}],sources:[j.source],reviewed,featureImage:engineImage,featureOverlay:true,
    diagram:{type:"firing",title:`Interactive ${j.model} firing-order map`,caption:"Select the events in order, then confirm physical cylinder locations in the exact service diagram.",points:j.order.match(/\d/g)??["ID"]},
    intro:[j.scope,j.detail],steps:["Confirm engine identity from the VIN, emissions label and casting information.","Bring cylinder 1 to compression TDC before disturbing distributor routing.","Label and trace one wire, coil or injector circuit at a time, then verify with misfire data."],
    sections:[{heading:`Cylinder identification for ${j.model}`,paragraphs:[j.numbering,j.detail]}],
    faqs:[{q:`What is the ${j.keyword}?`,a:j.order.startsWith("No recognized")?`${j.order}; ${j.numbering}`:`${j.order}. ${j.numbering}`},{q:"Is cylinder number the same as firing-event position?",a:"No. Cylinder identity is a physical location; firing order is the sequence in which those cylinders produce power."},{q:"Should the distributor be moved to fix crossed wires?",a:"Not until compression TDC, rotor position and the correct engine-specific routing have been established."}]};
}

const jeepSpark:SpecRecord={slug:"jeep/4-0/spark-plug-gap",keyword:"jeep 4.0 spark plug gap",make:"Jeep",model:"4.0L Inline-Six",category:"Ignition Specs",title:"Jeep 4.0 Spark Plug Gap by Model Year",
  metaDescription:"Jeep 4.0 spark plug gap guide covering common 0.035-inch applications, model-year exceptions, approved plug checks and safe installation.",
  answer:"Many Jeep 4.0L applications specify a 0.035 in (0.89 mm) spark plug gap, but the emissions label and exact model-year manual should be checked before adjustment.",
  scope:"Covers common AMC/Jeep 4.0L distributor and coil-rail applications; ignition revisions, approved plug designs and market calibrations can differ.",
  detail:"Do not force-adjust a fine-wire plug unless its manufacturer permits it. Confirm part number, reach, seat type and heat range along with the gap.",
  values:[{label:"Common specification",value:"0.035 in",note:"0.89 mm; verify model year"},{label:"Best vehicle check",value:"Under-hood emissions label",note:"Then confirm manual and plug catalog"}],sources:[S.mopar],reviewed,featureImage:engineImage,featureOverlay:true,
  diagram:{type:"spark",title:"Jeep 4.0 spark plug measuring guide",caption:"Measure at the specified electrode surfaces without levering against the center electrode.",points:["Identify","Measure","Inspect","Install"]},intro:[],
  steps:["Match the model year, engine and approved spark-plug part number.","Inspect the new plug for shipping damage and measure with a wire-style gauge.","Hand-start into a cool head and use the exact seat-specific torque procedure."],
  sections:[{heading:"Why Jeep 4.0 model year still matters",paragraphs:["The 4.0L name spans distributor, distributorless and coil-rail ignition systems. The familiar gap is not a substitute for checking the emissions label and approved plug.","A plug can have the correct gap and still be wrong in reach, seat, resistor design or heat range."]}],
  faqs:[{q:"What is the common Jeep 4.0 spark plug gap?",a:"0.035 inch (0.89 mm) is common, but verify the exact model year and approved plug."},{q:"Can every new plug be regapped?",a:"No. Follow the plug maker's instructions, especially for fine-wire iridium or platinum electrodes."},{q:"Should anti-seize be used?",a:"Only if the spark-plug or vehicle manufacturer specifies it; coatings change the torque-to-clamp relationship."}]};

export const referenceBatchSpecs:SpecRecord[]=[...lugJobs.map(lugPage),...torqueJobs.map(torquePage),...firingJobs.map(firingPage),jeepSpark];
