"use client";

import { useState } from "react";
import type { Diagram, SpecValue } from "./chevy350-content";

function DiagramGraphic({ diagram, active, setActive }: { diagram: Diagram; active: number; setActive: (i: number) => void }) {
  const buttons = diagram.points.map((point, index) => <button key={`${point}-${index}`} className={active === index ? "diagram-point active" : "diagram-point"} onClick={() => setActive(index)} aria-label={`Step ${index + 1}: ${point}`}><b>{index + 1}</b><span>{point}</span></button>);
  if (diagram.type === "firing" || diagram.type === "valve") return <div className={`diagram-graphic ${diagram.type}-graphic`}><div className="engine-front">FRONT OF ENGINE</div><div className="engine-banks"><div>{[1,3,5,7].map(c=><span key={c} className={diagram.points[active]===String(c)?"active":undefined}>{c}</span>)}</div><div className="engine-valley">350<br/><small>5.7L V8</small></div><div>{[2,4,6,8].map(c=><span key={c} className={diagram.points[active]===String(c)?"active":undefined}>{c}</span>)}</div></div><div className="sequence-strip">{buttons}</div></div>;
  if (diagram.type === "wheel") return <div className="diagram-graphic wheel-graphic"><div className="wheel-ring">{buttons}</div><div className="wheel-label">5-LUG<br/><small>STAR PATTERN</small></div></div>;
  if (diagram.type === "spark") return <div className="diagram-graphic spark-graphic"><div className="spark-body"><i/><i/><i/><strong>GAP</strong></div><div className="choice-row">{buttons}</div></div>;
  if (diagram.type === "timing") return <div className="diagram-graphic timing-graphic"><div className="degree-scale"><span>TDC</span><span>10°</span><span>20°</span><span>30°</span><span>40°</span></div>{diagram.points.map((p,i)=><button key={p} className={active===i?"timing-bar active":"timing-bar"} onClick={()=>setActive(i)}><span style={{width:i===0?"30%":"80%"}}/><b>{p}</b></button>)}</div>;
  if (diagram.type === "oil" || diagram.type === "rod") return <div className={`diagram-graphic workflow-graphic ${diagram.type}-graphic`}><div className="workflow-line"/>{buttons}</div>;
  if (diagram.type === "main") return <div className="diagram-graphic main-graphic"><div className="crank-line"/><div className="cap-grid">{buttons}</div></div>;
  return <div className={`diagram-graphic bolt-graphic ${diagram.type}-graphic`}><div className="component-outline"/><div className="bolt-grid">{buttons}</div></div>;
}

export function SpecVisual({ diagram, values, copyText }: { diagram: Diagram; values: SpecValue[]; copyText: string }) {
  const [tab, setTab] = useState<"diagram"|"table"|"checklist">("diagram"); const [active, setActive] = useState(0); const [copied, setCopied] = useState(false);
  const copy = async () => { await navigator.clipboard.writeText(copyText); setCopied(true); setTimeout(()=>setCopied(false),1500); };
  return <section className="visual-module" aria-labelledby="visual-title"><div className="visual-head"><div><span className="kicker">WORKBENCH VIEW</span><h2 id="visual-title">{diagram.title}</h2></div><div className="visual-actions"><button onClick={copy}>{copied?"Copied":"Copy specs"}</button><button onClick={()=>window.print()}>Print</button></div></div><div className="visual-tabs" role="tablist" aria-label="Specification views"><button className={tab==="diagram"?"active":undefined} onClick={()=>setTab("diagram")} role="tab" aria-selected={tab==="diagram"}>Diagram</button><button className={tab==="table"?"active":undefined} onClick={()=>setTab("table")} role="tab" aria-selected={tab==="table"}>Table</button><button className={tab==="checklist"?"active":undefined} onClick={()=>setTab("checklist")} role="tab" aria-selected={tab==="checklist"}>Text view</button></div><div className="visual-body">{tab==="diagram"&&<><DiagramGraphic diagram={diagram} active={active} setActive={setActive}/><div className="active-readout"><small>SELECTED</small><strong>{diagram.points[active]}</strong><span>Position {active+1} of {diagram.points.length}</span><button onClick={()=>setActive((active+1)%diagram.points.length)}>Next →</button></div></>}{tab==="table"&&<div className="table-scroll"><table className="spec-table visual-table"><thead><tr><th>ITEM</th><th>VALUE</th><th>DETAIL</th></tr></thead><tbody>{values.map(v=><tr key={v.label}><td>{v.label}</td><td>{v.value}</td><td>{v.note}</td></tr>)}</tbody></table></div>}{tab==="checklist"&&<ol className="text-equivalent">{diagram.points.map((p,i)=><li key={`${p}-${i}`}><b>{i+1}</b><span>{p}</span></li>)}</ol>}</div><p className="diagram-caption">{diagram.caption}</p></section>;
}
