import type { TroubleCodeGuide } from "./trouble-code-data";
import { troubleCodeEquinox } from "./trouble-code-equinox";

const manuals={label:"Chevrolet manuals and guides",url:"https://experience.gm.com/support/vehicle/manuals-guides",note:"Official GM model-year and VIN manual lookup; specifications and procedures must match the exact Malibu powertrain"};
const rocker={label:"GM PIP5527H — Malibu 2.5L rocker-arm oil-control valve",url:"https://static.nhtsa.gov/odi/tsbs/2020/MC-10173672-9999.pdf",note:"2014–2015 Malibu 2.5L LKW guidance for surge, roughness, P0171/P0300 and related codes after normal SI diagnosis"};
const earlyMisfire={label:"GM PIP5167 — early-build 2014 Malibu 2.5L P0300",url:"https://static.nhtsa.gov/odi/tsbs/2013/MC-10112376-9999.pdf",note:"Narrow August–September 2013 engine-build population with cylinder misfire and upper-end noise; not a general 2.5L diagnosis"};
const boost={label:"GM PIP5651G — Malibu charge-air outlet connection",url:"https://static.nhtsa.gov/odi/tsbs/2022/MC-10226399-9999.pdf",note:"2018–2022 Malibu 1.5L LFV guidance for reduced power with P1101/P0101/P0299/P0506/P0172; warns against replacing an undamaged throttle body or MAF"};
const boost2020={label:"GM PIP5710A — 2020–2021 Malibu charge-air tube",url:"https://static.nhtsa.gov/odi/tsbs/2022/MC-10217789-9999.pdf",note:"2020–2021 Malibu 1.5L LFV procedure to verify tube retention and seal position at the throttle body"};
const v6Timing={label:"GM PIP3423L — V6 correlation-code diagnosis",url:"https://static.nhtsa.gov/odi/tsbs/2015/MC-10114862-9999.pdf",note:"2008–2012 Malibu with listed 2.8/3.0/3.6L RPOs; inspect timing chains/tensioners first and consider crank reluctor movement only after SI diagnosis"};
const fourTiming={label:"GM PIP4548E — four-cylinder cam reluctor guidance",url:"https://static.nhtsa.gov/odi/tsbs/2015/MC-10114945-9999.pdf",note:"Defined 2007–2013 Malibu four-cylinder applications with P0016/P0017; engine-RPO-specific reluctor checks follow proper timing verification"};
const oilOld={label:"GM Bulletin 18-NA-246 — LTG short-trip fuel dilution",url:"https://static.nhtsa.gov/odi/tsbs/2022/MC-10209255-0001.pdf",note:"Defined 2013–2019 Malibu 2.0L LTG applications/build limits with P0172 and possible P0521/P06DE"};
const oilNew={label:"GM Bulletin 22-NA-056 — later LTG short-trip fuel dilution",url:"https://static.nhtsa.gov/odi/tsbs/2022/MC-10209397-0001.pdf",note:"Defined through-2022 Malibu 2.0L LTG application; requires confirmation of fuel-enriched oil and short-trip operation before the oil-service path"};
const throttle={label:"GM Bulletin 12-06-04-003A — older Malibu P2135",url:"https://static.nhtsa.gov/odi/tsbs/2014/MC-10246602-9999.pdf",note:"2006–2008 Malibu with listed V6 RPOs; explicitly directs technicians not to replace the complete throttle body automatically"};
const coldAir={label:"GM PI0746B — older Malibu V6 cold-weather intake deposits",url:"https://static.nhtsa.gov/odi/tsbs/2012/MC-10118616-9999.pdf",note:"2007–2011 Malibu 3.6L LY7/LLT guidance for cold-weather throttle-body ice/oil deposits with P0171 and related codes"};

const vehicle={name:"Chevrolet Malibu",kicker:"CHEVROLET MALIBU · ENGINE AND EMISSIONS DIAGNOSTICS",breadcrumb:"Chevrolet Malibu",about:"Chevrolet Malibu trouble-code diagnosis",yearsIntro:"Malibu code diagnosis changes sharply by generation and engine. Older 2.4L and V6 cars, the 2013–2015 2.5L, 2.0L turbo and 2016-and-newer 1.5L turbo do not share timing hardware, fuel systems, air plumbing or service bulletins. Confirm the VIN, model year and engine RPO before selecting a test or part."};

type Override=Partial<TroubleCodeGuide>&{code:string;sources:NonNullable<TroubleCodeGuide["sources"]>;yearNotes:string[];deepDive:NonNullable<TroubleCodeGuide["deepDive"]>};
const overrides:Override[]=[
 {code:"P0300",title:"P0300 Code Chevy Malibu: Misfire Diagnosis by Engine and Year",description:"Diagnose Chevy Malibu P0300 using cylinder counters, plugs, coils, fuel data and compression, with GM guidance for specific 2.5L engine-build faults.",quickAnswer:"P0300 means the ECM measured crankshaft-speed changes consistent with misfire but did not assign the failure to one cylinder. Start with counters, freeze frame, trims and companion P0301–P0306 codes. Malibu-specific exceptions matter: GM documents an intake rocker-arm oil-control fault on 2014–2015 2.5L LKW cars and a much narrower early-build 2014 2.5L valvetrain condition. Neither bulletin makes every P0300 a valvetrain repair.",dontReplace:"Do not install a full set of coils or assume a 2.5L rocker-control repair from P0300 alone. Identify the cylinder/system pattern, perform normal SI tests, and match engine/build boundaries before opening the valvetrain.",yearNotes:["2014–2015 2.5L LKW: PIP5527H applies after normal diagnosis and can involve the intake rocker-arm oil-control valve and trapped components in the cam cover.","Early 2014 2.5L engines built August 1 through September 30, 2013 have a separate PIP5167 path when misfire is accompanied by upper-end noise.","Turbo engines add charge-air, direct-injection and boost-dependent tests; older V6 and four-cylinder engines use different cylinder layouts and ignition/fuel procedures."],deepDive:[{heading:"The 2.5L cylinder pattern is evidence, not a shortcut",paragraphs:["PIP5527H notes that covered cars may misfire on cylinders 1–2 or 3–4 and may also set airflow, lean, imbalance or rocker-control codes. That cluster is more informative than P0300 alone.","GM places its inspection after normal Service Information diagnosis. Confirm ignition, injector and compression evidence before removing the oil-control valve; if components are missing, the bulletin explains why the cam cover may also require replacement.","PIP5167 is narrower still: it concerns a defined early engine-build window with upper-end noise. Verify engine build identification rather than using vehicle model year as a substitute."]}],sources:[rocker,earlyMisfire,manuals]},
 {code:"P0171",title:"P0171 Code Chevy Malibu: Lean Mixture Tests by Engine",description:"Diagnose Malibu P0171 with fuel trims, intake and charge-air leak testing, purge checks, fuel pressure and GM 2.5L or cold-weather V6 guidance.",quickAnswer:"P0171 means the ECM had to add more fuel than its calibrated lean limit allows. It does not prove the upstream oxygen sensor failed. Compare correction at idle and higher airflow, then test intake/PCV or turbo plumbing, purge sealing, exhaust leakage, measured airflow and fuel delivery. On defined Malibu engines, use the 2.5L rocker-control and older 3.6L cold-weather bulletins only when their full symptom and RPO patterns match.",dontReplace:"Do not replace an oxygen sensor simply because it reports lean. Prove that the sensor is biased only after air leaks, purge flow, fuel delivery, exhaust leakage and the applicable engine-specific conditions have been tested.",yearNotes:["2014–2015 2.5L LKW with surge/misfire and related codes may enter the PIP5527H rocker-arm oil-control diagnostic path after SI checks.","2007–2011 3.6L LY7/LLT cold-weather cases may involve throttle-body ice or oil deposits under PI0746B; this is not a warm-weather or four-cylinder diagnosis.","2016+ turbo engines require inspection of both vacuum-side intake paths and pressurized charge-air plumbing."],deepDive:[{heading:"Use operating conditions to separate Malibu lean faults",paragraphs:["Positive correction strongest at idle generally raises unmetered crankcase, intake or purge air. Correction that worsens under boost/load raises charge-air measurement, fuel-pressure and injector delivery. A single snapshot cannot make that distinction.","For a 2.5L LKW with P0300, P16D0/P16D1 or P2646/P2647, preserve the companion-code pattern before disturbing parts. For an older 3.6L whose problem follows a cold soak, inspect the documented ice/oil condition instead of transferring that bulletin to a later turbo car."]}],sources:[rocker,coldAir,manuals]},
 {code:"P0420",title:"P0420 Code Chevy Malibu: Catalyst Diagnosis Before Replacement",description:"Diagnose Malibu P0420 by correcting misfire and mixture faults, checking exhaust leaks and oil use, validating sensors and testing catalyst efficiency.",quickAnswer:"P0420 means the catalyst monitor judged Bank 1 oxygen-storage performance below its threshold. It does not identify what damaged the converter or prove a sensor should be replaced. Malibu engines with unresolved P0300/P0171, rich operation, oil consumption, coolant entry or exhaust leakage must have those causes corrected before catalyst efficiency can be judged.",dontReplace:"Do not order a converter from one P0420 result. Confirm exhaust integrity, sensor circuits and monitor prerequisites, then verify the replacement matches the vehicle's federal or California emissions certification.",yearNotes:["Inline-four engines still use the generic phrase Bank 1 even though they have only one cylinder bank.","Older V6 exhaust layouts may use P0420 for Bank 1 and P0430 for Bank 2; identify cylinder-bank and sensor location from VIN-correct information.","The underhood emissions label determines the legal converter family; physical fit alone is not enough."],deepDive:[{heading:"Why the Malibu's upstream fault matters",paragraphs:["A converter can be the failed component and still not be the root cause. Misfire sends oxygen and fuel into the catalyst, rich control overheats it, and oil or coolant can coat the active surface.","Review historical and pending codes, fuel trims, misfire counters and fluid-consumption history. Repair those conditions first, allow the catalyst monitor to run under its enabling conditions, and only then interpret a repeat failure."]}],sources:[manuals]},
 {code:"P0016",title:"P0016 Code Chevy Malibu: Cam-Crank Correlation Diagnosis",description:"Diagnose Malibu P0016 with oil and VVT tests, cam/crank waveform correlation, mechanical timing checks and engine-specific GM reluctor guidance.",quickAnswer:"P0016 means the ECM found a cam signal outside its expected relationship to crankshaft position. A sensor can accurately report low-oil/VVT control problems, chain or tensioner wear, incorrect timing assembly or a shifted reluctor. GM has separate guidance for defined older Malibu four-cylinder and V6 engines; confirm RPO and companion correlation codes before applying either path.",dontReplace:"Do not replace cam and crank sensors because their names appear in the definition. Test oil/VVT response, circuits, waveforms and mechanical timing first; a new sensor cannot correct a stretched chain or moved reluctor.",yearNotes:["Defined 2007–2013 four-cylinder applications are included in PIP4548E; its reluctor checks are engine-specific and follow confirmation that base timing is correct.","2008–2012 Malibu with listed 2.8/3.0/3.6L engines may use PIP3423L when two or more correlation codes are present; chains and tensioners are checked before crank-reluctor conclusions.","Later 1.5L/2.0L turbo engines use different timing and VVT diagnostics and do not inherit either older repair."],deepDive:[{heading:"One code versus a family of correlation codes",paragraphs:["A lone P0016 after connector work calls for a different priority than P0016/P0017/P0018/P0019 together with P0008/P0009 and timing noise. The second pattern can support a common mechanical reference problem on a covered V6.","Document desired and actual cam angles, oil condition, startup noise and recent timing work. Use waveform or SI mechanical checks before disassembly, and treat the bulletin's reluctor advice as a last diagnostic branch rather than the first parts order."]}],sources:[fourTiming,v6Timing,manuals]},
 {code:"P1101",title:"P1101 Code Chevy Malibu: Airflow and Charge-Pipe Diagnosis",description:"Diagnose Malibu P1101 with intake and boost leak testing, MAF/MAP plausibility, PCV checks and GM guidance for a disconnected 1.5L charge-air tube.",quickAnswer:"P1101 means measured airflow disagreed with the ECM's expected airflow model; it is not automatically a bad MAF. Inspect the full air path, PCV system, throttle connection, sensors and circuits. For 2018–2022 Malibu 1.5L LFV applications, GM PIP5651G identifies a charge-air outlet hose that may disconnect at the throttle body and warns against replacing undamaged throttle bodies or MAF sensors.",dontReplace:"Do not replace the MAF or throttle body solely for P1101. On a covered 1.5L car, inspect tube retention, the internal seal and component damage first; otherwise complete the normal SI airflow diagnostic.",yearNotes:["PIP5651G covers 2018–2022 Malibu 1.5L LFV and lists P1101 with P0172/P0299/P0101/P0506 and reduced power.","PIP5710A gives additional connection/seal guidance for 2020–2021 1.5L LFV applications.","A 2.0L turbo or another model year requires its own intake/charge-air layout and SI procedure."],deepDive:[{heading:"A disconnected tube leaves visible evidence",paragraphs:["Inspect the outlet tube where it enters the throttle body, including retainer engagement, seal position and damage. Normal witness marks do not alone condemn the throttle body.","If the tube is attached, do not force the bulletin repair. Smoke/pressure-test the induction system and compare MAF, MAP, desired/actual boost and throttle data before testing sensor circuits."]}],sources:[boost,boost2020,manuals]},
 {code:"P0496",title:"P0496 Code Chevy Malibu: Purge Flow Diagnosis",description:"Diagnose Malibu P0496 with purge sealing, fuel-tank-pressure data, EVAP hose inspection and post-refuel symptom testing before replacing parts.",quickAnswer:"P0496 means the ECM detected EVAP vacuum or vapor flow during a period when purge should not occur. A purge valve leaking internally is plausible, especially with a hard start after refueling, but electrical command, hose routing, fuel-tank-pressure bias and canister contamination still require testing.",dontReplace:"Do not replace the purge valve because it is a common repair. Command it closed and prove that flow continues; then verify its circuit, plumbing and fuel-tank-pressure response.",yearNotes:["Purge valve, canister, vent and filler hardware change across Malibu generations and engines.","Do not claim GM Special Coverage N222369620 for a Malibu; the published coverage identifies specific Cadillac XTS and Chevrolet Impala populations.","Use the VIN to check current warranty or field actions directly with Chevrolet rather than extrapolating another model's bulletin."],deepDive:[{heading:"Post-refuel symptoms narrow—but do not finish—the test",paragraphs:["A leaking purge valve can pull excess vapor into the intake during restart, causing extended cranking, roughness or stalling. Record fuel level and whether the fault followed refueling.","Verify physical sealing with the valve commanded closed. A click only confirms movement or electrical activation; it does not prove the valve seat is vapor-tight."]}],sources:[manuals]},
 {code:"P0521",title:"P0521 Code Chevy Malibu: Oil Pressure Signal and Fuel-Dilution Tests",description:"Diagnose Malibu P0521 safely with oil checks, mechanical pressure measurement, sensor circuits and GM short-trip fuel-dilution bulletin boundaries.",quickAnswer:"P0521 means the oil-pressure signal is outside the ECM's expected performance range. It cannot tell whether mechanical pressure is unsafe or whether oil dilution, viscosity/filter selection, sensor, wiring or calibration is responsible. Shut down for a red warning or engine noise, verify pressure mechanically, and apply GM's short-trip fuel-dilution procedures only to matched 2.0L LTG vehicles with confirmed fuel-enriched oil.",dontReplace:"Do not install an oil-pressure sensor before comparing scan data with a mechanical gauge. A sensor cannot repair diluted oil, an incorrect filter, low oil level or an internal lubrication fault.",yearNotes:["18-NA-246 covers defined 2013–2019 Malibu 2.0L LTG applications/build limits where P0521/P06DE may accompany a short-trip fuel-dilution condition.","22-NA-056 includes a later through-2022 Malibu 2.0L LTG application; it requires evidence of fuel-enriched oil and the specified trim behavior.","Other Malibu engines require their own mechanical-pressure specifications and normal SI diagnosis."],deepDive:[{heading:"Fuel odor is evidence, not permission to skip pressure testing",paragraphs:["The GM bulletins describe frequent short trips allowing fuel to accumulate in the crankcase. Their correction is conditional: confirm the operating pattern, oil condition and diagnostic data rather than automatically changing oil for every P0521.","A red warning, ticking or knocking still demands immediate shutdown and mechanical-pressure verification. If pressure is low, investigate lubrication hardware and damage before running the engine again."]}],sources:[oilOld,oilNew,manuals]},
 {code:"P2135",title:"P2135 Code Chevy Malibu: Throttle Correlation and Reduced Power",description:"Diagnose Malibu P2135 using dual throttle-position graphs, five-volt reference and wiring tests, plus GM's older V6 sensor-cover procedure.",quickAnswer:"P2135 means throttle-position signals 1 and 2 no longer agree within the calibrated relationship. The cause can be sensor electronics, terminals, wiring, reference/ground, contamination or calibration. For covered 2006–2008 Malibu V6 RPOs, GM explicitly directs technicians not to replace the complete throttle body automatically and supplies a sensor-cover service path.",dontReplace:"Do not automatically replace the throttle body. Match the older V6 bulletin when applicable and prove TP signal disagreement, terminal condition and five-volt integrity on every generation.",yearNotes:["12-06-04-003A covers 2006–2008 Malibu with listed V6 RPOs and directs a specific throttle-position sensor-cover procedure.","Later four-cylinder and turbo Malibu throttle bodies do not inherit that repair; use their VIN-specific SI diagnostics.","Multiple five-volt-reference codes raise a shared circuit short above a throttle assembly failure."],deepDive:[{heading:"Graph the two signals before disturbing the connector",paragraphs:["Capture TP1 and TP2 through a controlled sweep and at the moment Reduced Power occurs. A dropout in one trace, especially during harness movement or heat, is more useful than two normal key-on readings after the fault disappears.","On the covered older V6, follow the handling and cleaning cautions in the bulletin. On later cars, use current SI and perform any required setup or relearn after a proven repair."]}],sources:[throttle,manuals]},
 {code:"P0455",title:"P0455 Code Chevy Malibu: Large EVAP Leak Testing",description:"Find Malibu P0455 with filler inspection, regulated smoke, purge and vent commands and fuel-tank-pressure testing instead of guessing a gas cap.",quickAnswer:"P0455 means the EVAP system could not hold its expected vacuum or pressure and interpreted the loss as a gross leak. It does not locate that opening. Inspect the cap or capless filler as equipped, disconnected hoses, purge and vent sealing, canister damage and tank/module seals with regulated smoke and scan-tool commands.",dontReplace:"Do not label every P0455 a gas cap. A purge or vent valve held open can appear as a large leak, and later capless fillers require a different inspection.",yearNotes:["Conventional-cap and capless filler systems, vent location and tank connections differ by Malibu generation.","No universal Malibu purge special coverage should be inferred from another GM vehicle; verify the VIN directly.","Fuel level, soak and ambient-temperature conditions control when the EVAP monitor can verify the repair."],deepDive:[{heading:"A valve can imitate an open hose",paragraphs:["Command the vent closed and purge off, then observe fuel-tank pressure during a regulated smoke/seal test. Electrical activation or an audible click does not prove a valve is physically sealed.","Document the filler seal before moving it, especially when the code followed refueling. Then inspect quick-connects, flexible lines and seams rather than repeatedly installing caps."]}],sources:[manuals]},
 {code:"P0442",title:"P0442 Code Chevy Malibu: Small EVAP Leak Diagnosis",description:"Locate Malibu P0442 small EVAP leaks with careful filler checks, low-pressure smoke, purge and vent sealing tests and fuel-tank-pressure data.",quickAnswer:"P0442 means the EVAP monitor detected leakage below the gross-leak threshold. The location is not encoded. Small filler-seal defects, hairline hoses, quick-connect O-rings, purge seepage, incomplete vent sealing, canister seams and tank/module seals often require a patient regulated smoke test under conditions close to the original failure.",dontReplace:"Do not repeatedly replace the fuel cap. Tiny connector, hose and valve-seat leaks need controlled smoke and sealing tests, and capless Malibu applications have no conventional cap to replace.",yearNotes:["Small-leak thresholds and enabling conditions vary by model year and calibration.","Identify cap versus capless hardware and exact EVAP routing before testing.","A pending P0496 alongside P0442 increases the value of a purge-sealing test but does not prove the valve."],deepDive:[{heading:"Small leaks change with temperature and fuel level",paragraphs:["Rubber joints and seals can open only when cold or when tank vapor pressure changes. Preserve freeze-frame fuel level, ambient temperature and soak duration before clearing.","Use EVAP-regulated pressure; direct shop air can damage the system. Watch each seam patiently and use valve commands plus fuel-tank-pressure response to separate a leak from a biased sensor."]}],sources:[manuals]},
];

function replaceStrings(value:unknown):unknown{
 if(typeof value==="string")return value.replaceAll("Chevrolet Equinox","Chevrolet Malibu").replaceAll("Chevy Equinox","Chevy Malibu").replaceAll("Equinox","Malibu").replaceAll("equinox","malibu");
 if(Array.isArray(value))return value.map(replaceStrings);
 if(value&&typeof value==="object")return Object.fromEntries(Object.entries(value).map(([k,v])=>[k,replaceStrings(v)]));
 return value;
}

export const troubleCodeMalibu:TroubleCodeGuide[]=troubleCodeEquinox.map((source)=>{
 const base=replaceStrings(source) as TroubleCodeGuide;
 const custom=overrides.find((item)=>item.code===source.code);
 if(!custom)throw new Error(`Missing Malibu override for ${source.code}`);
 const slug=`chevrolet/malibu/${source.code.toLowerCase()}`;
 return {...base,...custom,slug,vehicle,deepDive:[...custom.deepDive,...(base.deepDive??[]).filter((section)=>!section.heading.toLowerCase().includes("bulletin"))],sources:custom.sources};
});
