import type { TroubleCodeGuide } from "./trouble-code-data";
import { fordManuals, fordObd2017, fordObd2024 } from "./trouble-code-sources";

const focusVehicle = {
  name: "Ford Focus",
  kicker: "FORD FOCUS · 2.0L GDI · 2.0L ECOBOOST ST · 1.0L ECOBOOST",
  breadcrumb: "Ford Focus",
  about: "Ford Focus gasoline-engine diagnostics",
  yearsIntro:
    "A North American Focus can be a naturally aspirated 2.0L GDI car, a turbocharged Focus ST, a 1.0L EcoBoost, or an RS with a 2.3L EcoBoost. The engine, build date and recall history change the likely causes and the correct pinpoint test, so identify them from the VIN and underhood label before ordering parts.",
};

const focusRecall = {
  label: "Ford Safety Recall 18S32 / NHTSA 18V-735 — Focus purge valve and fuel tank",
  url: "https://static.nhtsa.gov/odi/rcl/2018/RCMN-18V735-5232.pdf",
  note: "Ford dealer instructions for affected 2012–2018 Focus 2.0L GDI/GTDI vehicles; specifically names P0420, P1450, P0456 and P2196 among the relevant DTCs",
};

const focusOwnerManual2018 = {
  label: "2018 Ford Focus Owner's Manual — overheating warning",
  url: "https://www.fordservicecontent.com/Ford_Content/vdirsnet/OwnerManual/Home/Content?ProcUid=G1791805&Uid=G1791804&buildtype=web%2F1000&countryCode=USA&div=f&languageCode=en&moidRef=G539492&userMarket=USA&vFilteringEnabled=False&variantid=6056",
  note: "Ford instruction to stop the engine in an overheat condition and not restart until the cause is resolved",
};

const focusReadiness2017 = {
  label: "2017 Ford Focus Owner's Manual — OBD readiness drive cycle",
  url: "https://www.fordservicecontent.com/Ford_Content/vdirsnet/OwnerManual/Home/Content?ProcUid=G1607493&Uid=G1823822&buildtype=web&countryCode=USA&div=f&languageCode=en&userMarket=USA&vFilteringEnabled=False&variantid=4426",
  note: "Ford's Focus-specific inspection-readiness explanation and mixed highway/stop-and-go drive guidance",
};

type FocusInput = Omit<TroubleCodeGuide, "slug" | "vehicle" | "yearNotes" | "sources"> & {
  slug: string;
  yearNotes: string[];
  sources?: TroubleCodeGuide["sources"];
};

function focusGuide(input: FocusInput): TroubleCodeGuide {
  return {
    ...input,
    slug: `ford/focus/${input.slug}`,
    vehicle: focusVehicle,
    yearNotes: [
      ...input.yearNotes,
      "The 2012–2018 2.0L GDI/GTDI recall population must be checked by VIN; model year and engine description alone do not prove coverage or completion.",
      "Focus ST, RS, 1.0L EcoBoost and naturally aspirated 2.0L cars do not share every sensor, fuel-system test, calibration or service specification.",
      "Save aftermarket tune, intake, exhaust and recent repair details. Returning a modified car to a known calibration can be a valid diagnostic step.",
    ],
    deepDive: [
      ...(input.deepDive ?? []),
      {
        heading: `How to read the scan report before diagnosing ${input.code}`,
        paragraphs: [
          `Start with the first freeze frame associated with ${input.code}, then save confirmed, pending and permanent codes from every module that can communicate. RPM, load, coolant temperature, vehicle speed and time since start describe the moment the PCM objected. A fault that appears only on a cold start needs a different test from one that matures during steady cruise or full operating temperature.`,
          "Next, look for companion codes that change the diagnostic order. Circuit codes move wiring and power checks ahead of component replacement; misfire can make catalyst and mixture results unreliable; low-voltage history can create several implausible signals at once. Record readiness before clearing because it shows which monitors had enough valid operating time to judge their systems.",
          "Use live data as a comparison, not as isolated numbers. Compare cold temperature sensors with ambient, commanded values with actual values, and a suspect signal with the engine's other relevant PIDs. Save graphs or screenshots with units and test conditions. A normal-looking value at warm idle does not disprove a fault that set during refueling, boost, deceleration or an overnight cold soak.",
        ],
      },
      {
        heading: `DIY checks versus professional ${input.code} diagnosis`,
        paragraphs: [
          "A careful owner can inspect fluid levels on a cold car, battery terminals, intake and EVAP hoses, accessible connectors, grounds, air ducts and recent repair areas. A capable scan tool can preserve freeze frame, show pending codes and graph basic PIDs. Those observations often decide which system deserves testing without opening a pressurized fuel, hot cooling or internal engine system.",
          "Professional equipment becomes appropriate when the test requires direct-injection fuel-pressure work, bidirectional purge or fan control, regulated EVAP smoke, oscilloscope cam/crank analysis, exhaust-gas testing, compression/leak-down work or catalyst monitor interpretation. Turbocharged ST and RS cars also need safe charge-system and fuel testing that cannot be replaced by repeated full-throttle road pulls.",
          "Choose a shop when the warning lamp flashes, the engine overheats, stalls, loses oil pressure, makes mechanical noise or shows evidence of raw fuel. Ask the technician which observed result failed and what test proved it. A diagnosis written as only 'code present—replace part' does not separate the component from its circuit, plumbing, calibration or the condition that may have damaged it.",
        ],
      },
      {
        heading: `What a complete ${input.code} repair should document`,
        paragraphs: [
          "The repair order should identify the Focus model year, engine, calibration status and relevant build or recall information. It should preserve the original code list and freeze frame, name the failed inspection or measurement, and record the part number or procedure used. That trail matters when the same warning returns because it separates a repeat fault from a new companion condition.",
          "For a recall-era 2.0L car, record whether 18S32 applies by VIN and whether the complete remedy was already performed. A receipt for one purge valve does not automatically prove PCM programming, canister inspection and fuel-tank checks were completed. For modified cars, document the tune and hardware state used during both failure and verification.",
          "Avoid estimates that bundle several untested parts. Authorize additional components when inspection shows damage, contamination, leakage, failed electrical response or a required one-time-use rule. This protects both repair quality and the ability to challenge a comeback when the evidence does not match the invoiced diagnosis.",
        ],
      },
      {
        heading: `Verification after clearing ${input.code}`,
        paragraphs: [
          "Clear codes only after the original evidence is saved and the proven cause is corrected. Recheck connectors, hose routing, fluid levels, tool removal and any disturbed fasteners before starting. Observe the relevant live data at idle first; stop immediately if temperature, fuel pressure, misfire count or mechanical sound becomes unsafe.",
          "Repeat the safe portion of the original freeze-frame condition. That may mean a true cold start, a warm idle after refueling, steady cruise or moderate load—not an arbitrary five-minute idle. Watch for a pending code and confirm the repaired signal responds normally rather than merely waiting for the dashboard lamp.",
          "Finally, verify readiness progresses without another reset. Some monitors require fuel-level, temperature, soak and driving windows and will not complete immediately. A permanent code clears only after enough passing monitor operation. Keep the before-and-after scan report; it is the strongest proof that the repair corrected the monitored condition.",
        ],
      },
    ],
    closing: input.closing ?? {
      title: `The evidence that closes a ${input.code} diagnosis`,
      paragraphs: [
        `A successful repair is more than an extinguished warning lamp. The condition that set ${input.code} must be reproduced safely, the relevant signals or counters must remain normal, and no pending companion code should return. If the original condition cannot be recreated, describe that limitation instead of claiming certainty.`,
        "Reinspect the area after the verification drive for leaks, loose connectors, chafing or fluid changes. When a catalyst, engine or fuel-system problem was involved, follow any shortened inspection interval recommended by the service procedure and retain the old-part findings.",
        "If the code returns, do not clear it repeatedly. Compare the new freeze frame with the original. A changed temperature, load or companion-code pattern may point to a second fault, while an identical pattern suggests the original cause, wiring path or verification step was incomplete.",
      ],
    },
    sources: [fordObd2017, fordObd2024, ...(input.sources ?? []), fordManuals],
  };
}

export const troubleCodeFocus: TroubleCodeGuide[] = [
  focusGuide({
    slug: "p0300", code: "P0300", title: "P0300 Code Ford Focus: Random Misfire Causes and Diagnosis", description: "Diagnose P0300 on a Ford Focus by engine and symptom. Learn how plugs, coils, purge flow, fuel pressure, compression and timing produce random misfire.", definition: "Random/Multiple Cylinder Misfire Detected", severity: "Stop soon",
    driveAdvice: "Stop if the check-engine light flashes, the engine shakes hard, raw fuel is evident, coolant is disappearing or mechanical noise appears. A flashing lamp indicates an active misfire capable of overheating the catalytic converter. A steady lamp on a smooth-running car may permit a short, gentle trip for testing, but avoid boost, high rpm and extended driving.",
    quickAnswer: "P0300 means the PCM counted misfire on several cylinders or could not assign enough events to one cylinder. It does not identify a bad coil. On a Focus, first separate a single-cylinder ignition fault from a system problem: review P0301–P0304 counters, freeze frame, both short- and long-term fuel trim, purge command, fuel pressure and engine temperature. Engine identity matters because the 2.0L GDI, 2.0L ST, 1.0L and 2.3L RS use different fuel and boost systems.",
    symptoms: [
      {key:"flash",label:"The lamp flashes under acceleration",response:"Release the throttle and stop sustained driving. Check which cylinder counters rise under load, then test plug condition, coil reserve and fuel pressure without repeating a catalyst-damaging event."},
      {key:"idle",label:"Rough only at idle",response:"Compare fuel trims at idle and 2,500 rpm. An intake, PCV or purge-flow problem becomes more likely when positive correction is strongest at idle."},
      {key:"refuel",label:"Hard start after refueling",response:"On a 2012–2018 2.0L recall-era car, check VIN status and test the canister purge valve. A stuck-open valve can feed excessive vapor and disturb the mixture."},
      {key:"cold",label:"Misfire appears only on a cold start",response:"Save cold coolant temperature and early cylinder counts. Inspect plugs, moisture, injector behavior and mechanical sealing before the engine warms and hides the pattern."},
      {key:"boost",label:"ST or RS breaks up under boost",response:"Stop full-load testing. Verify the tune, plug specification and gap, charge-air leaks, commanded versus actual pressure and fuel delivery for that exact engine."},
    ],
    causes: [
      {cause:"Worn, fouled or incorrect spark plugs",evidence:"Excessive gap, deposits or misfire that rises with load",firstTest:"Remove and compare plugs in cylinder order against the VIN-correct Ford specification"},
      {cause:"Weak coil, boot or connector",evidence:"A dominant cylinder follows a controlled known-good coil swap",firstTest:"Inspect the boot and terminals, then move one coil only after counters identify a leader"},
      {cause:"Unmetered air or unintended purge flow",evidence:"Fuel trim is most positive at idle, or the symptom follows refueling",firstTest:"Smoke-test the intake and command/test the purge valve closed"},
      {cause:"Fuel-pressure or injector imbalance",evidence:"Misfire worsens with demand or remains on a cylinder after ignition checks",firstTest:"Graph commanded/actual pressure and perform the engine-specific injector balance test"},
      {cause:"Compression, valve or cam-timing fault",evidence:"Low relative compression, mechanical noise or correlation codes",firstTest:"Run relative compression, then leak-down or mechanical-timing checks as evidence requires"},
    ],
    freezeFrame:["RPM, calculated load and throttle angle","Coolant and intake-air temperature","Cylinder-specific misfire counters or Mode $06 results","Short- and long-term fuel trim","Commanded and actual fuel pressure where supported","Companion ignition, lean, purge, boost or cam-correlation codes"],
    steps:[{title:"Preserve the setting condition",detail:"Save confirmed, pending and permanent codes, freeze frame and readiness before clearing. Note fuel level, recent refueling and whether the lamp flashed."},{title:"Find the pattern",detail:"Compare cylinder counts at idle, a light no-load hold and only a safe road condition. One cylinder calls for a cylinder test; scattered counts call for air, fuel or timing checks."},{title:"Inspect before moving parts",detail:"Check intake and charge ducts, PCV and purge hoses, coil connectors, grounds, oil and coolant. Document modifications and recent repairs."},{title:"Separate ignition from the cylinder",detail:"Inspect the leading cylinder's plug and boot and use one controlled coil swap. If the misfire stays, test injector operation and compression instead of buying more coils."},{title:"Test system causes",detail:"Use smoke, fuel trims, purge command and commanded/actual fuel pressure. ST and RS cars require boost-leak and calibration checks under safe conditions."},{title:"Prove the result",detail:"Repeat the original temperature and load, verify counters remain stable and check for pending codes after monitors begin running."}],
    dontReplace:"Do not install a complete set of coils because P0300 contains the word misfire. The code is a crank-speed observation, not a parts verdict. Random replacement destroys the cylinder pattern and leaves purge, air, fuel, timing or compression faults untouched.",
    deepDive:[{heading:"What changes between Focus engines",paragraphs:["The naturally aspirated 2.0L and turbo engines share the code definition but not the same fuel-pressure, boost or calibration tests. A 1.0L three-cylinder also cannot use a four-cylinder firing diagram.","Identify the engine and model year before using plug gaps, torque values or injector procedures. A scan-tool PID with the same name can represent different strategies across calibrations."]},{heading:"When the Focus purge recall belongs in a misfire diagnosis",paragraphs:["Recall 18S32 is relevant when an affected 2.0L car has hard starting after refueling, an erratic fuel gauge, excessive tank vacuum or companion EVAP codes. It is not proof that every P0300 is a purge valve.","Check recall completion by VIN and follow the recall inspection path. A deformed tank or fuel-soaked canister needs more than a valve replacement."]}],
    yearNotes:["2012–2018 naturally aspirated 2.0L cars use direct injection; plug, injector and purge diagnosis must match the build.","Focus ST and RS add turbocharger, charge-air and calibration variables that ordinary Focus diagnostic trees do not cover."],
    faqs:[{question:"Can I drive a Ford Focus with P0300?",answer:"Stop for a flashing lamp, severe shaking, raw-fuel smell, coolant loss or mechanical noise. A steady lamp may allow a short gentle diagnostic trip, but avoid boost and high load."},{question:"Will spark plugs fix P0300?",answer:"Only when inspection or service history supports them. Read cylinder counters and preserve the old plugs in order so they remain evidence."},{question:"Can the Focus purge valve cause random misfire?",answer:"Yes, unintended purge flow can upset mixture, especially after refueling, but it must be tested and recall applicability confirmed by VIN."},{question:"How do I find the bad cylinder?",answer:"Use Ford-capable live misfire counters or Mode $06 results under the freeze-frame condition; pending P0301–P0304 codes can also localize it."},{question:"Does P0300 mean all cylinders are misfiring?",answer:"No. Events may be spread across several cylinders or insufficiently consistent for one cylinder code to mature."},{question:"Should I clear the code first?",answer:"No. Save freeze frame, counters, fuel trims and monitor status before erasing evidence."},{question:"Can low compression set P0300?",answer:"Yes. A valve, ring, head-gasket or timing problem can produce repeatable misfire that will not follow ignition parts."},{question:"What proves the repair?",answer:"Repeat the original temperature and load, confirm stable misfire counts, and check that no pending code returns as monitors run."}],
    sources:[focusRecall],
  }),

  focusGuide({
    slug:"p0171",code:"P0171",title:"P0171 Code Ford Focus: Bank 1 Lean Causes and Fuel-Trim Tests",description:"P0171 on a Ford Focus means Bank 1 fuel correction exceeded its lean limit. Use idle-versus-load trims, smoke testing, purge checks and fuel pressure to find why.",definition:"System Too Lean (Bank 1)",severity:"Diagnose promptly",
    driveAdvice:"A short trip is usually possible when the engine runs smoothly and the lamp is steady, but stop for a flashing lamp, hesitation, overheating or detonation. Lean operation can become misfire under load, so avoid boost and sustained high rpm until air leaks and fuel delivery are checked.",
    quickAnswer:"P0171 means the PCM had to add more fuel than its calibrated limit to correct the Bank 1 mixture. Focus gasoline engines are inline engines, so Bank 1 represents the engine's only cylinder bank. The useful question is where the correction is largest: positive trim that improves above idle favors a vacuum, PCV or purge leak; trim that worsens with load raises fuel supply, injector delivery or measured-air accuracy.",
    symptoms:[{key:"idle",label:"Trim is highest at idle",response:"Smoke-test the intake, PCV and brake-booster paths and verify the purge valve seals when commanded closed."},{key:"load",label:"Trim grows under acceleration",response:"Graph commanded and actual low/high fuel pressure for the installed engine and check measured airflow and charge plumbing."},{key:"refuel",label:"Hard start or rough idle after refueling",response:"Test unintended purge flow. On recall-era 2.0L cars, check 18S32 status and fuel-tank condition."},{key:"misfire",label:"P0171 appears with P0300/P0301",response:"Correct the mixture fault before judging coils broadly; a lean cylinder can misfire without an ignition failure."},{key:"modified",label:"The Focus has an intake or tune",response:"Inspect every post-MAF joint and restore a known calibration before treating factory fuel-trim expectations as valid."}],
    causes:[{cause:"Intake, PCV or brake-booster air leak",evidence:"Positive trim strongest at idle and improves with rpm",firstTest:"Smoke-test the sealed intake rather than spraying flammable cleaner"},{cause:"Purge valve leaking when commanded closed",evidence:"Post-refuel symptom or trim changes when purge is safely isolated",firstTest:"Command purge closed and verify no flow/vacuum passes"},{cause:"Fuel-pressure or volume shortfall",evidence:"Correction worsens as load and fuel demand rise",firstTest:"Graph commanded versus actual pressure through the setting condition"},{cause:"MAF/airflow error or charge leak",evidence:"Airflow/load PIDs are implausible; turbo car has charge-system evidence",firstTest:"Inspect the entire metered-air path and compare scan data with engine-specific expectations"},{cause:"Exhaust leak or biased upstream sensor",evidence:"Leak ahead of the sensor or response fails a controlled rich/lean test",firstTest:"Inspect cold exhaust sealing and prove sensor response before replacement"}],
    freezeFrame:["Short- and long-term fuel trim","RPM and calculated load","Coolant temperature and closed-loop status","MAF, MAP and throttle data","Commanded/actual fuel pressure","Purge command and companion misfire/EVAP codes"],
    steps:[{title:"Confirm closed-loop lean correction",detail:"Save codes and freeze frame, warm the engine and verify P0171 is not merely historical after another repair."},{title:"Compare idle with higher airflow",detail:"Record combined trim at idle and around 2,500 rpm. Improvement with airflow is a strong leak clue."},{title:"Smoke-test the air path",detail:"Seal and smoke the intake/PCV system. On turbo cars include charge plumbing using the correct low-pressure method."},{title:"Test purge control",detail:"Verify the valve does not flow when closed and review recall status if post-refuel symptoms or named recall codes are present."},{title:"Verify fuel delivery and sensor response",detail:"Graph pressure under the failing load and test the upstream sensor response only after leaks are excluded."},{title:"Confirm trims after repair",detail:"Repeat idle and load comparisons and look for pending lean or misfire codes."}],
    dontReplace:"Do not replace the upstream oxygen sensor because it reports lean. It is often accurately reporting extra air or insufficient fuel. Condemn it only after intake, purge, exhaust and fuel tests show the sensor itself responds incorrectly.",
    deepDive:[{heading:"Why Bank 1 is not a side of the Focus",paragraphs:["The gasoline Focus engines covered here are inline engines with one cylinder bank. Bank 1 therefore means the whole engine, not passenger side versus driver side as on a V engine.","A single-runner leak or injector can still affect one cylinder, so compare misfire counters when P0301–P0304 accompanies the lean code."]},{heading:"Use recall 18S32 as evidence, not a shortcut",paragraphs:["Ford's recall names mixture-related drivability symptoms and several EVAP codes on affected 2.0L cars. A leaking purge valve can act like an intake leak.","VIN coverage, purge testing and tank inspection still matter. Replacing a purge valve without checking a deformed tank or saturated canister is incomplete recall-era diagnosis."]}],
    yearNotes:["The 2.0L GDI and GTDI fuel systems have high-pressure components that require Ford procedures and safety precautions.","A 1.0L or turbocharged performance model needs its own airflow and pressure baseline."],
    faqs:[{question:"What does P0171 mean on a Ford Focus?",answer:"The PCM exceeded its allowed positive fuel correction because Bank 1 appeared lean."},{question:"Which side is Bank 1?",answer:"On an inline Focus engine there is only one bank, so Bank 1 is the whole cylinder row."},{question:"Can a vacuum leak cause P0171?",answer:"Yes. Trim that is most positive at idle and improves with rpm strongly supports a fixed air leak."},{question:"Can the purge valve cause P0171?",answer:"Yes, if it flows when commanded closed. Test it, especially after-refuel symptoms, rather than guessing."},{question:"Can I drive with P0171?",answer:"Only gently if it runs normally and the lamp is steady. Stop for flashing, hesitation, knock or overheating."},{question:"Does P0171 mean a bad O2 sensor?",answer:"No. The sensor may be reporting a real lean condition from air or fuel faults."},{question:"What scan data matters most?",answer:"Compare combined trims at idle and higher airflow, then add fuel pressure, MAF/MAP and purge command."},{question:"How is the repair confirmed?",answer:"Repeat the setting condition and verify trims remain normal with no pending lean or misfire codes."}],
    sources:[focusRecall],
  }),

  focusGuide({
    slug:"p0420",code:"P0420",title:"P0420 Code Ford Focus: Catalyst Tests Before Replacement",description:"Diagnose Ford Focus P0420 without guessing at a catalytic converter. Check misfire, fuel trim, exhaust leaks, sensor response and Focus recall 18S32 first.",definition:"Catalyst System Efficiency Below Threshold (Bank 1)",severity:"Service soon",
    driveAdvice:"A steady P0420 alone usually permits normal short-term driving, but stop for a flashing lamp, severe power loss, a glowing converter, overheating or a sulfur/raw-fuel smell. Active misfire and mixture faults can destroy a replacement converter, so repair them before evaluating catalyst efficiency.",
    quickAnswer:"P0420 means the PCM judged the Bank 1 catalyst's oxygen-storage performance below its calibrated threshold. It does not prove the converter is the first failed part. On affected 2012–2018 2.0L Focus vehicles, Ford recall 18S32 specifically lists P0420 among codes that can accompany a stuck-open purge valve and excessive fuel-tank vacuum. Misfire, rich/lean operation and exhaust leakage must be resolved before the catalyst monitor is trusted.",
    symptoms:[{key:"alone",label:"P0420 is the only code",response:"Inspect exhaust integrity and compare upstream/downstream sensor behavior under the exact catalyst-monitor conditions."},{key:"misfire",label:"Misfire codes are also present",response:"Repair and verify the misfire first; unburned fuel can overheat the substrate and invalidate catalyst diagnosis."},{key:"evap",label:"P1450, P0456 or P2196 is present",response:"Check Focus recall 18S32 by VIN and test purge/tank condition before authorizing a converter."},{key:"rattle",label:"The converter rattles or power is restricted",response:"Stop heavy driving and test for a broken or melted substrate and exhaust backpressure."},{key:"recent",label:"P0420 returned after converter replacement",response:"Check part/emissions certification, exhaust leaks, sensor wiring and the mixture or oil/coolant problem that damaged the original."}],
    causes:[{cause:"Aged or damaged catalytic converter",evidence:"Monitor fails after upstream faults and leaks are excluded",firstTest:"Run the Ford catalyst test and compare sensor switching under enabling conditions"},{cause:"Active misfire or rich/lean operation",evidence:"Companion codes, abnormal trims or rising misfire counters",firstTest:"Diagnose mixture and misfire before judging the converter"},{cause:"Stuck-open purge valve on an affected Focus",evidence:"Recall-era car with named DTCs, tank vacuum/gauge or post-refuel symptoms",firstTest:"Check 18S32 status and follow Ford's purge/tank inspection"},{cause:"Exhaust leak near the catalyst or sensors",evidence:"Cold tick, soot or oxygen entering ahead of/downstream sensor",firstTest:"Perform visual and low-pressure smoke inspection"},{cause:"Sensor, wiring or incorrect replacement part",evidence:"Slow/biased response, damaged harness or noncompliant converter",firstTest:"Prove sensor response and verify VIN/emissions part application"}],
    freezeFrame:["RPM, load and coolant temperature","Fuel-system status and trims","Upstream and downstream sensor data","Misfire counters and companion codes","Vehicle speed and time since start","Recall completion and converter replacement history"],
    steps:[{title:"Save the complete code report",detail:"Do not clear misfire, lean, rich, purge or sensor codes that explain why the catalyst monitor failed."},{title:"Check Focus recall applicability",detail:"For a 2012–2018 2.0L GDI/GTDI car, confirm 18S32 by VIN and look for gauge, tank-vacuum or refueling symptoms."},{title:"Repair upstream faults",detail:"Resolve misfire, fuel trim, oil/coolant consumption and purge problems, then allow monitors to rerun."},{title:"Inspect exhaust integrity",detail:"Check flanges, flex pipe, sensor ports and welds for leakage before interpreting oxygen signals."},{title:"Run the catalyst test",detail:"Use Ford enabling conditions and compare sensor activity; generic idle waveform rules are not a final verdict."},{title:"Verify the replacement path",detail:"Match emissions certification and part number, then prove monitor completion without returning companion codes."}],
    dontReplace:"Do not order a catalytic converter from P0420 alone. A converter fitted before repairing misfire, purge, mixture, oil burning or coolant entry may fail again, and an exhaust leak or sensor fault can leave the same code after an expensive part swap.",
    deepDive:[{heading:"Why recall 18S32 belongs on this page",paragraphs:["Ford's dealer notice explicitly tells technicians to check P0420 with P1450, P0456, P2196 and related codes on affected Focus vehicles. The recall repair can include PCM programming, purge valve, canister, tank and fuel-delivery module inspection or replacement.","That does not make recall coverage automatic. Confirm the VIN and completed remedy before using the recall as the diagnostic path."]},{heading:"Permanent P0420 and monitor verification",paragraphs:["A permanent code cannot be erased simply by disconnecting the battery. It clears after the OBD system observes sufficient passing operation.","Save readiness status and use the applicable Ford drive conditions. A lamp that remains off during one idle period does not prove catalyst efficiency."]}],
    yearNotes:["Federal and California-emissions Focus applications may require different certified converter parts.","ST and RS exhaust layouts, tunes and high-load use change the evidence but not the need to fix upstream faults first."],
    faqs:[{question:"Does P0420 always mean the catalytic converter is bad?",answer:"No. Misfire, mixture faults, purge problems, exhaust leaks and sensor issues must be excluded."},{question:"Can recall 18S32 cause P0420?",answer:"Ford explicitly names P0420 in the affected Focus recall procedure, but VIN coverage and purge/tank evidence must be confirmed."},{question:"Can I drive with P0420?",answer:"Usually briefly if it is the only code and the lamp is steady; stop for flashing, restriction, overheating or strong fuel odor."},{question:"Should oxygen sensors be replaced first?",answer:"Only after response and wiring tests prove a sensor fault. They are measurement devices, not automatic maintenance parts."},{question:"Can a misfire damage the converter?",answer:"Yes. Unburned fuel can overheat and melt the catalyst substrate."},{question:"Why did P0420 return after replacement?",answer:"The root cause, exhaust leak, sensor fault, calibration or incorrect converter application may remain."},{question:"Will clearing P0420 pass inspection?",answer:"No. Clearing resets readiness, and permanent codes require passing monitor operation."},{question:"What should a shop document?",answer:"Companion-code status, exhaust integrity, sensor evidence, emissions application and the completed catalyst-monitor result."}],
    sources:[focusRecall],
  }),

  focusGuide({
    slug:"p0016",code:"P0016",title:"P0016 Code Ford Focus: Cam and Crank Correlation Diagnosis",description:"P0016 on a Ford Focus is a cam/crank relationship fault, not an automatic sensor failure. Check oil, VCT response, wiring, timing and relearn requirements.",definition:"Crankshaft Position–Camshaft Position Correlation (Bank 1, Sensor A)",severity:"Stop soon",
    driveAdvice:"Keep driving to a minimum. Stop immediately for timing noise, low oil pressure, hard starting, stalling or a flashing lamp. A genuine timing error can worsen quickly; repeated starts and high-rpm tests are inappropriate until oil supply and mechanical timing are evaluated.",
    quickAnswer:"P0016 means the measured intake-cam relationship to the crankshaft fell outside Ford's expected window. Sensor A is the intake cam on the engine's only bank, but that wording does not convict the sensor. Incorrect oil, VCT solenoid or phaser response, wiring, trigger-wheel error, a stretched/jumped drive, recent engine work or a missing relearn can all break correlation.",
    symptoms:[{key:"noise",label:"Rattle at startup",response:"Stop repeated starts and check oil pressure and mechanical timing before electrical parts."},{key:"repair",label:"Code appeared after timing or engine work",response:"Recheck timing alignment, trigger handling, connectors, grounds and required crank/cam relearns."},{key:"oil",label:"Oil is low, dirty or wrong viscosity",response:"Correct the verified oil problem and check pressure; do not assume an oil change repairs a jumped drive."},{key:"stall",label:"Hard starting or stalling",response:"Limit operation and test cam/crank signals and mechanical relationship under safe cranking conditions."},{key:"multiple",label:"Several VCT/correlation codes are stored",response:"Look for a common oil-pressure, timing-installation, crank-signal or power/ground issue."}],
    causes:[{cause:"Mechanical timing error or worn drive",evidence:"Noise, repeatable offset, recent work or multiple correlation codes",firstTest:"Verify timing with the exact engine procedure and tools"},{cause:"Oil level, viscosity or pressure problem",evidence:"Low level/pressure, contamination or poor VCT response",firstTest:"Confirm oil specification and measure pressure when indicated"},{cause:"VCT solenoid or phaser control fault",evidence:"Desired and actual intake angle disagree",firstTest:"Graph angle and test solenoid circuit and oil feed"},{cause:"Cam/crank circuit or trigger fault",evidence:"Dropout, companion circuit code or implausible waveform",firstTest:"Inspect wiring and compare synchronized waveforms"},{cause:"Relearn/calibration issue after repair",evidence:"Mechanical timing verifies but code began after component/PCM work",firstTest:"Check Ford relearn and calibration requirements"}],
    freezeFrame:["RPM and load","Coolant and oil condition/temperature","Desired versus actual intake-cam angle","Cam/crank and VCT companion codes","Battery voltage during cranking","Recent repair and calibration history"],
    steps:[{title:"Check oil and noise before running",detail:"Verify level and specification. Do not repeatedly start an engine with chain/belt, phaser or low-pressure noise."},{title:"Map Sensor A correctly",detail:"Treat it as the intake cam location, not a failed sensor diagnosis, and record all related codes."},{title:"Inspect wiring and basics",detail:"Check battery voltage, grounds, connectors, pin fit and harness damage near recent work."},{title:"Compare desired and actual cam angle",detail:"Use a capable scan tool under controlled conditions and compare behavior with Ford expectations."},{title:"Verify control and mechanical timing",detail:"Test the solenoid and oil feed; move to exact mechanical timing/waveform checks when offset persists."},{title:"Relearn and recheck",detail:"Complete Ford-required relearns and reproduce the original setting condition without aggressive operation."}],
    dontReplace:"Do not replace the intake cam sensor solely because P0016 names camshaft position. A perfect new sensor still reports a phaser, oil-pressure, trigger or mechanical timing error.",
    deepDive:[{heading:"Timing hardware changes with the Focus engine",paragraphs:["The 1.0L EcoBoost, 2.0L naturally aspirated, ST and RS engines do not share one timing layout or locking procedure. Internet timing marks from another Focus engine can create the fault you are trying to repair.","Select workshop information from VIN and engine code, including one-time fasteners, timing tools and relearn steps."]},{heading:"Waveform and scan data answer different questions",paragraphs:["Desired-versus-actual cam angle shows control response; synchronized cam/crank waveforms show the measured mechanical/electrical relationship. Neither should be read without correct reference data.","If oil pressure or timing noise is abnormal, mechanical safety takes priority over extended waveform collection."]}],
    yearNotes:["The Focus engine family includes belt- and chain-driven timing systems; never transfer marks or torque procedures between them.","Recent cylinder-head, timing, engine or PCM work moves installation and relearn checks to the top."],
    faqs:[{question:"Is P0016 just a bad cam sensor?",answer:"No. It is a cam/crank relationship test affected by oil, VCT control, wiring, triggers, timing and relearn."},{question:"What is Bank 1 Sensor A?",answer:"On the inline Focus engine, Bank 1 is the only bank and Sensor A refers to the intake cam."},{question:"Can wrong oil cause P0016?",answer:"Oil level, viscosity and pressure affect VCT, but oil service cannot repair mechanical misalignment."},{question:"Can I drive with P0016?",answer:"Minimize driving and stop for noise, stalling, hard starting or low oil pressure."},{question:"Does the Focus use a belt or chain?",answer:"It depends on engine. Identify the exact engine before using timing information."},{question:"What data should be graphed?",answer:"Desired and actual intake-cam angle, engine speed, voltage and relevant VCT/cam/crank PIDs."},{question:"Why did it appear after repair?",answer:"Timing installation, connector placement, trigger damage or an omitted relearn may be responsible."},{question:"What proves the fix?",answer:"Correct oil pressure/timing, completed relearn, normal cam tracking and no pending correlation code under the original condition."}],
  }),

  focusGuide({
    slug:"p1450",code:"P1450",title:"P1450 Code Ford Focus: Purge Valve, Recall and Tank Vacuum",description:"P1450 on a Ford Focus means the PCM cannot bleed fuel-tank vacuum. Learn the purge-valve tests, recall 18S32 implications and tank/canister checks.",definition:"Unable to Bleed Up Fuel Tank Vacuum",severity:"Diagnose promptly",
    driveAdvice:"Do not ignore stalling, an erratic fuel gauge, a tank that will not accept fuel or a strong vacuum sound at the cap. Ford's Focus recall warns that a stuck purge valve can deform the tank and cause an engine stall. Maintain a safe fuel level and arrange VIN-specific recall/service inspection.",
    quickAnswer:"P1450 means tank vacuum did not decrease as expected when the EVAP system tried to vent it. On affected 2012–2018 Focus 2.0L GDI/GTDI cars, Ford safety recall 18S32 centers on a canister purge valve that can stick open, draw excessive vacuum and deform the plastic tank. The proper path checks recall completion, purge leakage, vent/canister restriction, pressure-sensor data and physical tank condition—not the gas cap alone.",
    symptoms:[{key:"stall",label:"Stall or hard start after refueling",response:"Stop treating this as a loose cap. Test purge flow and check recall status immediately."},{key:"gauge",label:"Fuel gauge or distance-to-empty is erratic",response:"Inspect for tank deformation under the recall procedure; gauge error is a named warning symptom."},{key:"vacuum",label:"Strong inrush when the cap opens",response:"Excessive retained vacuum supports purge/vent diagnosis but is not a stand-alone parts test."},{key:"fill",label:"Pump repeatedly shuts off",response:"Check vent restriction, canister saturation and tank shape rather than forcing more fuel."},{key:"codes",label:"P0456, P2196 or P0420 accompanies P1450",response:"Those codes are named in 18S32; preserve the complete report for the recall inspection."}],
    causes:[{cause:"Canister purge valve stuck/leaking open",evidence:"Vacuum continues with purge commanded closed; post-refuel symptoms",firstTest:"Command closed and measure flow/vacuum across the valve"},{cause:"Restricted vent path or vent valve",evidence:"Tank cannot equalize and filling is difficult",firstTest:"Command the vent and inspect filter/hoses for blockage"},{cause:"Fuel-soaked or restricted canister",evidence:"Liquid fuel, repeated topping-off history or flow restriction",firstTest:"Inspect using Ford's EVAP/recall procedure"},{cause:"Deformed fuel tank or delivery module effect",evidence:"Erratic gauge/DTE and recall-era vacuum history",firstTest:"Check VIN and measure tank deformation as Ford directs"},{cause:"Pressure-sensor or circuit error",evidence:"FTP reading is implausible or does not respond to controlled pressure/vacuum",firstTest:"Test reference, signal, ground and response before replacement"}],
    freezeFrame:["Fuel level and fuel-tank pressure","Purge and vent commands","Time/distance since refueling","Fuel gauge/DTE behavior","P0456, P2196, P0420, P0443, P0452 or P0460","Recall completion and prior EVAP repairs"],
    steps:[{title:"Check 18S32 by VIN",detail:"Confirm whether the Focus is affected and whether the complete remedy was performed."},{title:"Preserve pressure and command data",detail:"Save freeze frame and observe FTP response before opening the cap or clearing codes."},{title:"Test purge sealing",detail:"With purge commanded closed, verify that manifold vacuum cannot continue pulling through the valve."},{title:"Test the vent path",detail:"Command the vent and inspect hoses, filter and canister for restriction or liquid fuel."},{title:"Inspect tank and fuel module",detail:"Follow Ford's recall measurements when gauge error, deformation or a leaking purge valve is present."},{title:"Verify pressure release",detail:"After repair, confirm tank vacuum decays normally and the EVAP monitor runs without pending codes."}],
    dontReplace:"Do not stop at a gas cap. P1450 concerns the system's inability to release vacuum, and the Focus recall documents purge valve, canister, tank and fuel-delivery consequences that a new cap cannot correct.",
    deepDive:[{heading:"What recall 18S32 requires",paragraphs:["Ford's dealer procedure includes PCM software review, DTC/complaint checks, purge-valve replacement when indicated, canister inspection for liquid fuel and tank deformation inspection. Tank and fuel-delivery components may also require replacement.","Recall eligibility and remedy status are VIN-specific. A previous valve-only repair does not prove the complete recall inspection was performed."]},{heading:"Why topping off can complicate EVAP diagnosis",paragraphs:["Adding fuel after the nozzle shuts off can push liquid into the vapor canister. A saturated canister changes purge behavior and can create restriction.","Stop at the first automatic shutoff and record whether filling difficulty began before or after other EVAP repairs."]}],
    yearNotes:["Recall 18S32 covers certain 2012–2018 Focus 2.0L GDI/GTDI vehicles; check VIN rather than assuming.","A Focus Electric has a different powertrain and is outside this gasoline EVAP guide."],
    faqs:[{question:"What does P1450 mean on a Ford Focus?",answer:"The PCM could not reduce fuel-tank vacuum as expected during EVAP control."},{question:"Is there a Ford Focus recall for P1450?",answer:"Recall 18S32 covers certain 2012–2018 2.0L GDI/GTDI cars and names P1450; eligibility is VIN-specific."},{question:"Can P1450 cause stalling?",answer:"Yes. Ford warns the stuck purge condition can lead to stalling and inability to restart."},{question:"Can a gas cap fix P1450?",answer:"Usually not; the code concerns retained vacuum and requires purge, vent, canister, sensor and tank checks."},{question:"Why is my fuel gauge wrong?",answer:"Excessive vacuum can deform the tank and affect fuel-level indication in the recall condition."},{question:"Should I replace the purge valve immediately?",answer:"Test it and follow the recall path; related tank or canister damage may also need correction."},{question:"Can topping off cause problems?",answer:"Yes. It can saturate the vapor canister with liquid fuel."},{question:"What confirms repair?",answer:"Normal FTP response, proper vacuum decay, stable gauge operation and a completed EVAP monitor without pending codes."}],
    sources:[focusRecall],
  }),

  focusGuide({
    slug:"p1299",code:"P1299",title:"P1299 Code Ford Focus: Cylinder-Head Overtemperature Protection",description:"P1299 on a Ford Focus means overtemperature protection activated. Stop safely, verify coolant and fan operation, and diagnose the cause before restarting.",definition:"Cylinder Head Overtemperature Protection Active",severity:"Stop soon",
    driveAdvice:"Pull over safely, switch the engine off and allow it to cool. Ford's Focus manual says not to restart until the cause of overheating is determined and resolved. Never remove the reservoir cap hot. Continuing can warp the cylinder head, damage the gasket or seize the engine.",
    quickAnswer:"P1299 records that Ford's cylinder-head temperature strategy reached the protection threshold. It is not automatically a bad temperature sensor. Low coolant, leakage, a failed fan or control circuit, thermostat/water-pump trouble, blocked airflow, severe engine load or a genuine head-gasket problem can all create the event. Start with coolant level only when cold, evidence of leakage, fan operation and temperature plausibility.",
    symptoms:[{key:"steam",label:"Steam or coolant loss",response:"Do not restart. Allow full cooling and pressure-test for the leak before adding coolant and driving."},{key:"fan",label:"Temperature rises in traffic",response:"Check fan command, fan control, fuses, connectors and airflow through the radiator."},{key:"speed",label:"Overheats mainly at highway load",response:"Check coolant circulation, thermostat, pump, combustion-gas leakage and airflow restriction."},{key:"false",label:"Code appears immediately on a cold engine",response:"Compare cylinder-head/coolant and ambient temperature PIDs and inspect the sensor circuit for implausibility."},{key:"limp",label:"Power is limited",response:"That can be Ford's protective strategy. Do not defeat it or continue loading the engine."}],
    causes:[{cause:"Low coolant or external leak",evidence:"Reservoir low when cold, pressure loss or visible residue",firstTest:"Pressure-test the cold system and inspect all leak points"},{cause:"Cooling-fan/control failure",evidence:"Overheat at low speed; commanded fan does not run",firstTest:"Compare command with operation and test power, ground and control"},{cause:"Thermostat, water pump or circulation problem",evidence:"Abnormal hose/radiator temperature pattern or poor circulation",firstTest:"Follow engine-specific cooling-system flow tests"},{cause:"Combustion leak or internal engine fault",evidence:"Repeated pressurization, coolant loss, misfire or gas in coolant",firstTest:"Use pressure, combustion-gas and leak-down evidence"},{cause:"CHT/ECT sensor or wiring fault",evidence:"Cold reading implausible or signal jumps electrically",firstTest:"Compare cold-soak PIDs and test circuit continuity/reference"}],
    freezeFrame:["Cylinder-head and coolant temperature","Vehicle speed, load and rpm","Fan command and A/C state","Ambient temperature","Coolant level/leak history","Companion sensor, misfire or voltage codes"],
    steps:[{title:"Shut down and cool completely",detail:"Do not open the pressurized reservoir or restart simply to see whether the warning returns."},{title:"Inspect coolant and leaks cold",detail:"Check level, residue, hoses, radiator, pump and cabin-heater evidence."},{title:"Validate temperature data",detail:"After a cold soak, compare CHT/ECT with ambient and inspect for sudden electrical jumps."},{title:"Test fan and airflow",detail:"Verify commanded fan operation, control circuits and unobstructed heat-exchanger airflow."},{title:"Test circulation and sealing",detail:"Evaluate thermostat, pump, pressure retention and combustion leakage by the exact engine procedure."},{title:"Prove thermal stability",detail:"After repair and refill/bleed, monitor temperature through idle and road load without exceeding safe limits."}],
    dontReplace:"Do not replace the cylinder-head temperature sensor because P1299 mentions cylinder-head temperature. The code records a protection event; first prove whether the engine truly overheated and why.",
    deepDive:[{heading:"Protection mode is a warning, not a way to continue",paragraphs:["Ford may limit power or alter cylinder operation to reduce heat, depending on the application. That margin is intended to help reach safety, not finish a journey.","Continued operation can turn a hose, fan or thermostat repair into cylinder-head and catalyst damage."]},{heading:"A proper refill includes bleeding and verification",paragraphs:["Air trapped after cooling-system service can create hot spots and misleading level changes. Use the exact fill and bleed method for the engine.","Recheck cold level after heat cycles and verify heater operation, fan control and stable scan temperatures."]}],
    yearNotes:["Cooling-system layouts and fan controls differ among the 1.0L, 2.0L, ST and RS engines.","Any recent coolant, thermostat, water-pump or engine work raises air entrapment and installation errors in the diagnostic order."],
    faqs:[{question:"What does P1299 mean on a Ford Focus?",answer:"Ford's cylinder-head overtemperature protection strategy activated."},{question:"Can I keep driving?",answer:"No. Stop safely and determine the cause before restarting."},{question:"Can low coolant set P1299?",answer:"Yes, and the source of coolant loss must be found rather than repeatedly topping up."},{question:"Does P1299 mean a bad sensor?",answer:"No. It may be a real overheat or an implausible sensor/circuit signal."},{question:"Why does it overheat in traffic?",answer:"Low-speed overheating raises fan operation and radiator airflow high on the list."},{question:"Can a thermostat cause it?",answer:"Yes, as can a pump, leak, trapped air, fan fault or internal sealing problem."},{question:"When can the cap be opened?",answer:"Only after the engine is fully cool and system pressure is gone."},{question:"What confirms repair?",answer:"Stable coolant/CHT data, correct fan operation, no leaks and normal temperature through the original load condition."}],
    sources:[focusOwnerManual2018],
  }),

  focusGuide({
    slug:"p1000",code:"P1000",title:"P1000 Code Ford Focus: OBD Monitors Not Yet Complete",description:"P1000 on a Ford Focus means readiness testing is incomplete, often after battery disconnection or code clearing. Learn what to check before the drive cycle.",definition:"OBD Systems Readiness Test Not Complete",severity:"Informational",
    driveAdvice:"P1000 by itself does not indicate a failed component and normally does not change how the car drives. Do not attempt an inspection until required monitors show ready. If another code, warning lamp or drivability symptom exists, diagnose that condition before trying to complete readiness.",
    quickAnswer:"P1000 means the Focus has not completed all required OBD monitor checks since memory was cleared, power was lost or operating conditions were not met. It is a status code, not a request for a sensor. Ford's 2017 Focus manual explains that readiness can take several days and gives a mixed highway and stop-and-go drive sequence after an eight-hour key-off soak.",
    symptoms:[{key:"battery",label:"Appeared after battery work",response:"Normal monitor reset is likely. Confirm charging voltage and drive normally through required conditions."},{key:"clear",label:"Appeared after codes were cleared",response:"Expected. Clearing erases readiness evidence; do not clear again before inspection."},{key:"inspection",label:"Inspection says not ready",response:"Read the individual monitor list to learn exactly which tests remain incomplete."},{key:"stuck",label:"One monitor never completes",response:"Check pending codes, fuel level, temperatures and enable conditions rather than replacing parts blindly."},{key:"lamp",label:"The warning lamp is also on",response:"P1000 is not the cause of the lamp; retrieve and diagnose the other confirmed code."}],
    causes:[{cause:"Recent code clearing or battery disconnection",evidence:"Readiness reset immediately after service",firstTest:"Check monitor status and avoid another reset"},{cause:"Insufficient drive conditions",evidence:"Only short trips, no cold soak or no steady cruise",firstTest:"Follow the Focus manual's mixed drive guidance safely"},{cause:"Pending fault blocks a monitor",evidence:"Monitor stays incomplete and a pending code returns",firstTest:"Diagnose the pending fault before more drive cycles"},{cause:"Fuel level/temperature outside enable window",evidence:"EVAP or other monitor repeatedly remains not ready",firstTest:"Review Ford enabling conditions and freeze/PID data"},{cause:"Power or charging interruption",evidence:"Clock/memory resets or low-voltage history",firstTest:"Test battery, terminals and charging stability"}],
    freezeFrame:["Individual readiness monitor status","Confirmed, pending and permanent codes","Battery voltage and recent disconnect history","Fuel level","Coolant/ambient temperature","Trip pattern since the last reset"],
    steps:[{title:"Scan every monitor",detail:"Record which tests are ready, incomplete or unsupported and retrieve all pending codes."},{title:"Correct other faults first",detail:"A fault that blocks a monitor must be repaired before readiness can complete."},{title:"Verify battery and fuel level",detail:"Prevent another memory reset and place fuel within the monitor's required range."},{title:"Begin after a cold soak",detail:"Ford's Focus guidance calls for at least eight hours key-off before the mixed drive."},{title:"Drive safely through mixed conditions",detail:"Use about 15 minutes steady highway followed by 20 minutes stop-and-go with at least four 30-second idle periods where legal and safe."},{title:"Rescan without clearing",detail:"Confirm monitor progress. Repeat only when needed; clearing starts over."}],
    dontReplace:"Do not buy an oxygen sensor, catalyst, purge valve or PCM for P1000 alone. It reports unfinished testing, not the component that prevented it. The individual monitor and any companion code provide the useful direction.",
    deepDive:[{heading:"Why repeated clearing guarantees inspection trouble",paragraphs:["Erasing codes also erases monitor completion. The lamp may be off while the inspection computer still sees the car as not ready.","Save the original diagnostic report, repair the fault and allow the appropriate monitor to pass instead of clearing immediately before the test."]},{heading:"A drive cycle is not a public-road performance test",paragraphs:["Complete only legal, safe speed and idle conditions. Do not coast, accelerate or stop in a way that endangers traffic merely to force a monitor.","If conditions cannot be reproduced safely, normal varied driving or a professional controlled test is the right choice."]}],
    yearNotes:["Inspection allowances for incomplete monitors vary by jurisdiction; check the current local rule.","A hybrid/electric readiness procedure does not apply to a gasoline Focus, and Focus Electric is outside this guide."],
    faqs:[{question:"Is P1000 a fault?",answer:"Usually no. It means one or more OBD monitors have not completed."},{question:"Will P1000 turn on the check-engine light?",answer:"P1000 alone generally is not the underlying MIL fault; scan for other codes."},{question:"How long does it take to clear?",answer:"It may take several days or one successful drive cycle, depending on which monitor remains."},{question:"Can I clear P1000 with a scanner?",answer:"Clearing resets readiness again. The code resolves when required monitors run successfully."},{question:"Will P1000 fail emissions inspection?",answer:"Incomplete required monitors can cause a not-ready result under local rules."},{question:"What is the Focus drive guidance?",answer:"Ford describes an eight-hour soak, about 15 minutes highway and 20 minutes stop-and-go with four 30-second idles."},{question:"Why is EVAP still not ready?",answer:"Fuel level, ambient temperature, soak time or a pending EVAP fault may be blocking it."},{question:"Should the battery be disconnected?",answer:"No. That resets monitor status and can prolong the problem."}],
    sources:[focusReadiness2017],
  }),

  focusGuide({
    slug:"p2196",code:"P2196",title:"P2196 Code Ford Focus: Upstream O2 Signal Stuck Rich",description:"Diagnose P2196 on a Ford Focus by testing purge flow, injector leakage, fuel pressure, sensor response and recall 18S32 before replacing the upstream sensor.",definition:"O2 Sensor Signal Biased/Stuck Rich (Bank 1, Sensor 1)",severity:"Diagnose promptly",
    driveAdvice:"Avoid extended driving if the engine runs rich, misfires, smells strongly of fuel or the lamp flashes. Excess fuel can wash cylinder walls and overheat the catalyst. On recall-era 2.0L cars with gauge errors, post-refuel trouble or stalling, arrange VIN-specific 18S32 inspection.",
    quickAnswer:"P2196 means the Bank 1 Sensor 1 signal remained on the rich side when the PCM expected it to move. On a Focus inline engine, Bank 1 is the only bank and Sensor 1 is upstream of the catalyst. A stuck-open purge valve, leaking injector, excessive fuel pressure, restricted air, biased sensor or wiring can all create the result. Ford recall 18S32 explicitly names P2196 on affected 2012–2018 2.0L cars.",
    symptoms:[{key:"refuel",label:"Rough or stalls after refueling",response:"Test purge sealing and recall status; do not start with the oxygen sensor."},{key:"gauge",label:"Fuel gauge or DTE is erratic",response:"This matches the excessive-vacuum recall concern and calls for tank inspection."},{key:"fuel",label:"Fuel smell or black exhaust",response:"Limit driving and test injector leakage, pressure and purge flow before catalyst damage."},{key:"misfire",label:"P0300/P0301 accompanies P2196",response:"Use plug condition and cylinder counters to localize a leaking injector or mixture problem."},{key:"none",label:"No obvious running symptom",response:"Test sensor response and wiring under the setting condition; intermittent purge can disappear by inspection time."}],
    causes:[{cause:"Purge valve stuck open",evidence:"Post-refuel symptoms, EVAP codes or recall-era tank evidence",firstTest:"Command purge closed and verify no vacuum/flow"},{cause:"Leaking fuel injector",evidence:"Pressure decay, fuel-fouled plug or one cylinder rich/misfiring",firstTest:"Run injector leak/balance tests using GDI safety procedures"},{cause:"Excessive fuel pressure or control error",evidence:"Actual pressure exceeds command",firstTest:"Graph low/high-side pressure and commands"},{cause:"Biased upstream oxygen sensor or circuit",evidence:"Signal fails controlled rich/lean response after mixture faults are excluded",firstTest:"Test response, reference/ground and harness integrity"},{cause:"Restricted intake or contaminated airflow input",evidence:"Airflow implausible, filter/duct restriction or incorrect load data",firstTest:"Inspect intake and compare MAF/MAP with engine-specific expectations"}],
    freezeFrame:["Upstream sensor/lambda signal","Short- and long-term fuel trim","Commanded and actual fuel pressure","Purge command and FTP","Misfire counters","Fuel level and time since refueling"],
    steps:[{title:"Save companion codes and recall evidence",detail:"Record EVAP, misfire, fuel-pressure and catalyst codes plus gauge/refueling symptoms."},{title:"Check purge with the valve closed",detail:"Verify manifold vacuum cannot draw vapor continuously through the valve."},{title:"Compare fuel trims and pressure",detail:"A true rich condition usually drives correction negative; graph pressure against command."},{title:"Check cylinders for injector evidence",detail:"Compare plugs, misfire counts and safe injector leak/balance results."},{title:"Prove sensor response",detail:"Only after mixture causes are excluded, test whether Sensor 1 moves correctly with controlled mixture change."},{title:"Verify recall repair and monitors",detail:"Complete applicable 18S32 work and confirm normal trim/sensor behavior without pending codes."}],
    dontReplace:"Do not replace Bank 1 Sensor 1 because its signal says rich. It may be accurately reporting fuel from a purge valve or injector. Prove that the mixture is not rich and that the sensor fails a response/circuit test first.",
    deepDive:[{heading:"Why the Focus recall changes P2196 priorities",paragraphs:["Ford names P2196 in the 18S32 inspection list because a leaking purge valve can feed vapor, distort mixture and create drivability problems while excessive tank vacuum develops.","The remedy may extend beyond the purge valve when the canister contains liquid fuel or the tank is deformed."]},{heading:"Sensor 1 and catalyst diagnosis are linked",paragraphs:["Sensor 1 controls mixture feedback and Sensor 2 helps evaluate the catalyst. A biased upstream signal or true rich condition can later contribute to P0420.","Correct P2196 and verify fuel trims before condemning a converter."]}],
    yearNotes:["The 2.0L direct-injection system operates at hazardous pressure; use Ford depressurization and test procedures.","Aftermarket tunes and performance fueling on ST/RS cars change expected lambda and pressure behavior."],
    faqs:[{question:"What does P2196 mean?",answer:"The upstream Bank 1 oxygen/lambda signal stayed biased rich when the PCM expected movement."},{question:"Where is Bank 1 Sensor 1?",answer:"The Focus has one inline bank; Sensor 1 is the upstream sensor before the catalyst."},{question:"Does P2196 mean the sensor is bad?",answer:"No. Purge flow, injector leakage and pressure errors can make it report a genuinely rich mixture."},{question:"Is P2196 included in Focus recall 18S32?",answer:"Yes, Ford names it in the affected-vehicle DTC list; VIN coverage must still be confirmed."},{question:"Can I drive with P2196?",answer:"Limit driving and stop for flashing, severe misfire or strong raw-fuel symptoms."},{question:"Can a purge valve cause it?",answer:"Yes. Test for flow while the valve is commanded closed."},{question:"Can it damage the converter?",answer:"Persistent rich operation or misfire can overheat and contaminate the catalyst."},{question:"What proves a bad sensor?",answer:"Incorrect circuit or response behavior after real mixture faults, exhaust issues and wiring are excluded."}],
    sources:[focusRecall],
  }),

  focusGuide({
    slug:"p0456",code:"P0456",title:"P0456 Code Ford Focus: Small EVAP Leak and Recall Checks",description:"Find a Ford Focus P0456 small EVAP leak with cap inspection, smoke testing, purge/vent tests and the recall 18S32 tank-vacuum checks.",definition:"Evaporative Emission System Leak Detected (Very Small Leak)",severity:"Service soon",
    driveAdvice:"P0456 alone normally does not change drivability, but do not delay when it accompanies stalling, post-refuel hard starting, an erratic gauge or strong tank vacuum. Those symptoms overlap Ford Focus safety recall 18S32 and deserve VIN-specific inspection.",
    quickAnswer:"P0456 means the EVAP monitor detected a leak too small to maintain the expected pressure or vacuum. A loose/damaged cap, cracked hose, seal, vent valve or purge leakage can cause it. On affected 2012–2018 Focus 2.0L cars, Ford also names P0456 in recall 18S32; excessive vacuum and a purge fault can produce a more serious system problem than a cap leak.",
    symptoms:[{key:"cap",label:"Code followed refueling",response:"Inspect cap seal and filler neck and confirm the cap is correctly installed, but save post-refuel drivability clues."},{key:"stall",label:"Hard start or stall after filling",response:"Test purge sealing and check 18S32 by VIN rather than repeatedly replacing caps."},{key:"gauge",label:"Gauge/DTE is erratic",response:"Check tank deformation under the recall procedure."},{key:"smell",label:"Fuel vapor odor",response:"Inspect promptly for vapor/liquid leakage in a ventilated area; avoid ignition sources."},{key:"alone",label:"No symptoms beyond the lamp",response:"Use a low-pressure smoke test and commanded purge/vent testing to find the small leak."}],
    causes:[{cause:"Loose, damaged or wrong fuel cap/seal",evidence:"Seal cracked or code followed cap disturbance",firstTest:"Inspect cap and filler sealing surface; install correctly"},{cause:"Small hose or connection leak",evidence:"Smoke appears at hose, quick-connect or seal",firstTest:"Smoke-test at Ford-specified low pressure"},{cause:"Purge valve does not seal",evidence:"Flow with valve commanded closed; post-refuel symptoms",firstTest:"Bench/on-car sealing test and recall check"},{cause:"Vent valve/filter problem",evidence:"Valve fails command or dirt prevents sealing",firstTest:"Command vent and inspect circuit, valve and filter"},{cause:"Canister, tank or FTP sensor issue",evidence:"Liquid fuel/deformation or implausible pressure response",firstTest:"Follow recall/EVAP inspection and circuit response tests"}],
    freezeFrame:["Fuel level","FTP signal","Purge and vent command","Ambient/coolant temperature","Time since refueling","Companion P1450, P2196, P0420 or gauge codes"],
    steps:[{title:"Record the full report",detail:"Save freeze frame and recall-related companion codes before touching the cap."},{title:"Inspect cap and filler",detail:"Check seal, threads and filler surface without assuming this is the final cause."},{title:"Check recall status and symptoms",detail:"For an affected 2.0L car, include purge, canister and tank inspection when Ford's criteria are present."},{title:"Smoke-test safely",detail:"Use regulated EVAP pressure and command vent/purge valves as the procedure requires."},{title:"Test pressure-sensor response",detail:"Verify FTP changes smoothly with controlled pressure/vacuum and its circuit is sound."},{title:"Run the EVAP monitor",detail:"After repair, maintain suitable fuel/temperature conditions and check pending status without clearing repeatedly."}],
    dontReplace:"Do not keep buying fuel caps when P0456 returns. A small hose leak, purge or vent valve, canister seal, pressure circuit or recall-related tank problem can produce the same code.",
    deepDive:[{heading:"Small leak does not always mean small consequence",paragraphs:["P0456 describes the monitor result, not the size or cost of the failed component. In recall 18S32, it appears among codes associated with a purge valve and excessive tank vacuum.","Gauge error, stalling and tank deformation change the urgency even if the DTC label says very small leak."]},{heading:"Why fuel level and temperature matter",paragraphs:["EVAP monitors run only inside calibrated enable windows. A nearly empty/full tank or unsuitable ambient temperature can delay verification.","Do not clear repeatedly; preserve readiness and allow the monitor to run under safe normal conditions."]}],
    yearNotes:["Capless and conventional filler hardware must be identified before using seal procedures.","Recall 18S32 status is VIN-specific for affected 2012–2018 2.0L GDI/GTDI cars."],
    faqs:[{question:"Can I drive with P0456?",answer:"Usually yes if it is alone, but recall-related stalling, gauge error or strong vacuum requires prompt inspection."},{question:"Is P0456 always a gas cap?",answer:"No. Hoses, purge/vent valves, canister, tank seals and pressure sensing can cause it."},{question:"Is P0456 included in recall 18S32?",answer:"Yes, Ford names it for affected vehicles; confirm VIN coverage."},{question:"Can a purge valve set P0456?",answer:"Yes, a valve that will not seal can fail the leak test."},{question:"How is a small leak found?",answer:"With visual inspection, commanded valve tests and regulated low-pressure smoke testing."},{question:"Why won't the EVAP monitor run?",answer:"Fuel level, soak and ambient temperature may be outside enabling conditions."},{question:"Can topping off damage the canister?",answer:"Yes. Liquid fuel can saturate the vapor canister."},{question:"What confirms repair?",answer:"No smoke/pressure loss at the repaired point and a completed EVAP monitor without pending P0456."}],
    sources:[focusRecall],
  }),

  focusGuide({
    slug:"p0301",code:"P0301",title:"P0301 Code Ford Focus: Cylinder 1 Misfire Tests and Fixes",description:"Diagnose a Ford Focus P0301 cylinder 1 misfire with plug and coil swaps, injector testing, compression checks and year-specific engine identification.",definition:"Cylinder 1 Misfire Detected",severity:"Stop soon",
    driveAdvice:"Stop for a flashing lamp, severe shaking, fuel odor, mechanical noise or coolant loss. A steady lamp with mild symptoms may allow a short diagnostic trip, but avoid boost and load; unburned fuel can overheat the catalyst.",
    quickAnswer:"P0301 means the PCM localized misfire to cylinder 1. That narrows the test but does not identify the part. Inspect cylinder 1's plug, coil boot, connector and well, then use a controlled coil swap. If the count remains on cylinder 1, test injector command/delivery and mechanical sealing. Confirm cylinder location from the exact Focus engine diagram rather than assuming every three- and four-cylinder engine is numbered alike.",
    symptoms:[{key:"load",label:"Misfire appears under load",response:"Check plug condition/gap and coil reserve first, then fuel pressure on the installed engine."},{key:"cold",label:"Cold-start-only cylinder 1 misfire",response:"Preserve early counts and inspect plug deposits, injector leakage and compression/sealing."},{key:"wet",label:"Plug is wet with fuel",response:"Stop repeated running and separate no-spark from injector leakage before catalyst damage."},{key:"oil",label:"Oil or water is in the plug well",response:"Correct the leak and inspect the boot/connector; contamination can create carbon tracking."},{key:"stays",label:"Misfire stays after a coil swap",response:"Move to plug comparison, injector tests and compression instead of replacing more coils."}],
    causes:[{cause:"Cylinder 1 plug worn/fouled/damaged",evidence:"Abnormal gap, deposits or cracked insulator compared with others",firstTest:"Remove and compare all plugs in cylinder order"},{cause:"Coil, boot or connector fault",evidence:"Misfire follows the coil or tracking/terminal damage is visible",firstTest:"Perform one controlled known-good coil swap"},{cause:"Cylinder 1 injector fault",evidence:"Ignition tests pass; injector command/delivery or leakage differs",firstTest:"Run safe electrical, balance and leak tests"},{cause:"Local intake leak",evidence:"Lean correction and smoke near cylinder 1 runner",firstTest:"Smoke-test intake/PCV seals"},{cause:"Low compression or valve/timing fault",evidence:"Misfire never moves and relative compression is low",firstTest:"Run relative compression then leak-down/mechanical inspection"}],
    freezeFrame:["Cylinder 1 and other misfire counters","RPM/load and coolant temperature","Fuel trims","Fuel pressure","Coil/injector circuit companion codes","Recent plug, engine or coolant repair history"],
    steps:[{title:"Confirm cylinder localization",detail:"Save freeze frame and verify cylinder 1 dominates rather than relying on a stored code after an old repair."},{title:"Inspect the well and connector",detail:"Look for oil, water, tracking, loose pins and harness damage before swapping."},{title:"Read the plug",detail:"Compare cylinder 1 with the others and verify correct part/gap for the exact engine."},{title:"Move one coil",detail:"Swap with a known-good cylinder, then see whether the misfire follows under the same condition."},{title:"Test injector and compression",detail:"If it stays on cylinder 1, verify injector command/delivery and mechanical sealing."},{title:"Verify under the original condition",detail:"Recheck counters and pending codes at the recorded temperature/load without extended damaging operation."}],
    dontReplace:"Do not replace all coils for a localized P0301. One controlled swap provides evidence. If the misfire stays on cylinder 1, repeated coil purchases delay injector, wiring or mechanical diagnosis.",
    deepDive:[{heading:"Keep removed parts in cylinder order",paragraphs:["Plug deposits, boot tracking and injector evidence are comparative. Mixing parts destroys that comparison.","Photograph cylinder 1 and label each removed component before cleaning or replacement."]},{heading:"A successful swap must reproduce the symptom",paragraphs:["If the fault only occurs cold or under load, one warm idle after moving a coil is not a valid test. Reproduce the safe portion of the freeze-frame condition.","Stop immediately if the lamp flashes; professional load testing may be safer than repeated road acceleration."]}],
    yearNotes:["Confirm cylinder numbering from the exact 1.0L, 2.0L, ST or RS service diagram.","Direct-injection injector work requires depressurization and cleanliness beyond an ordinary port-injection test."],
    faqs:[{question:"What does P0301 mean?",answer:"The PCM detected misfire localized to cylinder 1."},{question:"Is it usually a coil?",answer:"A coil or plug is a logical early test, but injector, wiring, air leak and compression faults can remain on cylinder 1."},{question:"How do I test the coil?",answer:"Move it to a known-good cylinder and see whether the misfire follows under the same setting condition."},{question:"Can I drive with P0301?",answer:"Stop for flashing or severe symptoms; otherwise limit driving and avoid load until diagnosed."},{question:"Why did the misfire stay after a new coil?",answer:"The plug, injector, connector, local leak or mechanical sealing may be the cause."},{question:"Can low compression cause P0301?",answer:"Yes. Relative compression and leak-down testing separate mechanical faults."},{question:"Should plugs be changed as a set?",answer:"Follow the service plan, but preserve and compare the old plugs before discarding evidence."},{question:"What proves repair?",answer:"Cylinder 1 counts remain stable and no pending misfire returns under the original temperature/load."}],
  }),
];
